### ISSUE TITLE
bug回報

### ISSUE THREAD

**Issue by h9052300** [Byaidu/PDFMathTranslate#1]
1. 翻譯的過程中會卡住
2. 翻譯出的pdf輸出結果有很多空白頁

**Comment by Byaidu** [comment]
1. pdf 文档中可能会有部分 obj 比较大，导致 pdfminer 解析时间比较长，后续会考虑用 mupdf 重写这部分
2. 空白页可能是文档渲染指令异常，刚才修改了渲染顺序，现在应该可以了

可以 update 到新版本看看有没有解决，另外想问一下是否方便提供测试用的 pdf 呢

**Comment by h9052300** [comment]
效果有大幅的提升! 非常感謝您的更新
以下是我测试用的 pdf 

https://1drv.ms/b/s!AlwPWrxUxxlCmjmTKSRKgslk3JFk?e=EBgdkr
