### ISSUE TITLE
部分pdf无法翻译

### ISSUE THREAD

**Issue by ethanxyzhu** [Byaidu/PDFMathTranslate#100]
## 问题描述
翻译前后内容无变化，如图
![图片](https://github.com/user-attachments/assets/6ab19999-958c-41fe-acb2-2efd0c805de0)

## 测试文档
[Kubus和Wahl - 2009 - Scaling and eliminating non-contact forces and torques to improve bilateral teleoperation.pdf](https://github.com/user-attachments/files/17854056/Kubus.Wahl.-.2009.-.Scaling.and.eliminating.non-contact.forces.and.torques.to.improve.bilateral.teleoperation.pdf)

**Comment by reycn** [comment]
已复现，文档格式不符合 PDF/A 标准解析失败。
在手动转换为 PDF/A 标准后，翻译成功，如图：
<img width="1366" alt="image" src="https://github.com/user-attachments/assets/725ca8c4-50c0-4612-8e66-4bd5dfc90c26">

单独开启 feature issue，关闭此 issue。
