### ISSUE TITLE
"Command output: ERROR:pdf2zh.converter:Empty translation result" infinitely

### ISSUE THREAD

**Issue by gettinwet** [Byaidu/PDFMathTranslate#114]
<img width="713" alt="image" src="https://github.com/user-attachments/assets/96561950-1c58-4035-ad43-d5ba7b24b458">
<img width="800" alt="image" src="https://github.com/user-attachments/assets/5e76ac3c-d5e8-4bb3-932b-bb977d8d86a2">

**Comment by Byaidu** [comment]
**本项目不处理网络环境引发的问题**（例如 empty translation result/connection reset/check_hostname requires server_hostname/certificate verify failed/unable to connect to proxy）
