### ISSUE TITLE
翻译为空白

### ISSUE THREAD

**Issue by whxqyhz** [Byaidu/PDFMathTranslate#118]
## 问题描述
翻译看预览是翻译成中文的，但实际文件却是空白内容。
python version：3.10.15
![Screenshot 2024-11-23 203029](https://github.com/user-attachments/assets/1cf3200b-1d07-4af2-82bc-c511d37cf1e9)
![image](https://github.com/user-attachments/assets/94489fb3-0fc7-492a-be8f-f39deda2923b)

## 测试文档
[aa.pdf](https://github.com/user-attachments/files/17879666/aa.pdf)

**Comment by Byaidu** [comment]
麻烦按照模板反馈

**Comment by whxqyhz** [comment]
> 麻烦按照模板反馈

已改，抱歉

**Comment by Byaidu** [comment]
![image](https://github.com/user-attachments/assets/f8fc343e-6d27-48a7-aa58-c931affc871d)

我这里所有主流阅读器 acrobat/wps/chrome 都可以正常打开，不知道你是什么环境

**Comment by whxqyhz** [comment]
ok，我发现问题了，可以用chrome打开，但是microsoft edge显示不出中文。

**Comment by Byaidu** [comment]
我这里 edge 也是正常的，可能你需要升个级
