### ISSUE TITLE
  File "D:\Python\lib\urllib\request.py", line 1351, in do_open     raise URLError(err) urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>

### ISSUE THREAD

**Issue by 2429853510** [Byaidu/PDFMathTranslate#12]
这咋回事呀，大佬，我安装之后运行的翻译命令

**Comment by Byaidu** [comment]
默认使用 google 翻译服务，需要科学上网

**Comment by Byaidu** [comment]
新版本改成 http 了，更新下试试呢

**Comment by Byaidu** [comment]
看起来没更新好的样子，pdf2zh -v 应该显示 1.6.1

**Comment by Byaidu** [comment]
> 俺又更新啦 PS F:\PDFMathTranslate\PDFMathTranslate> pdf2zh -v pdf2zh v1.6.0

这个显示 1.6.0 就是没更新的意思，你需要 --upgrade 更新到 1.6.1

**Comment by xxsunyxx** [comment]
python 3.12 anaconda
ERROR: Could not find a version that satisfies the requirement doclayout-yolo (from versions: none)
ERROR: No matching distribution found for doclayout-yolo

**Comment by xxsunyxx** [comment]
解决了，需要build doclayout-yolo

**Comment by Byaidu** [comment]
删了重装呢

**Comment by Byaidu** [comment]
pip install pdf2zh==1.6.1

**Comment by Byaidu** [comment]
诶怎么 http 都没办法正常请求了

“certificate verify failed: unable to get local issuer certificate”

应该就是你系统的本地证书配置出错了吧，建议 google 一下怎么修

**Comment by xxsunyxx** [comment]
还是强强的事

**Comment by Byaidu** [comment]
啊这，我也没测试的环境，你多试试肯定有一个方案是对的

**Comment by Byaidu** [comment]
等下……你这个改的位置好像都不对，需要改的应该是下面这一行

```py
File "D:\Python\lib\site-packages\pdf2zh\pdf2zh.py", line 73, in extract_text
urllib.request.urlretrieve("[http://huggingface.co/juliozhao/DocLayout-YOLO-DocStructBench/resolve/main/doclayout_yolo_docstructbench_imgsz1024.pt",pth](http://huggingface.co/juliozhao/DocLayout-YOLO-DocStructBench/resolve/main/doclayout_yolo_docstructbench_imgsz1024.pt%22,pth))
```

我建议还是直接开个虚拟机或者 wsl 之类的吧
