### ISSUE TITLE
部分专有名词翻译有误

### ISSUE THREAD

**Issue by LouisNuh** [Byaidu/PDFMathTranslate#120]
## 功能描述
是否可以提供一个词典类文件，可以让使用者自行添加翻译时遇到的专有名词

**Comment by reycn** [comment]
@Byaidu deepl 应该支持自定义专业词典，但好像其他的服务不支持？如果服务不支持，应该会影响翻译上下文 。
需求倒是明确且合理。

**Comment by Byaidu** [comment]
要不然直接把pdf的标题喂给大模型好了，感觉加额外的字典文件有点费事费力

**Comment by reycn** [comment]
大模型是不是直接 prompting 就好了。

类似“请将 xx 翻译为 xxx 就行”

**Comment by LouisNuh** [comment]
考虑到同一个词可能会在不同领域中翻译成不同的意思，可不可以搞一个空白文件，用户如果需要自己往里添加即可，不需要一个个的和大模型说，直接安文件批量

**Comment by Byaidu** [comment]
prompt加上文档标题就相当于给定领域了吧
