### ISSUE TITLE
参考文献的 点击转跳绿色框 完全没有对上

### ISSUE THREAD

**Issue by cathy345345** [Byaidu/PDFMathTranslate#123]
参考文献的 点击转跳绿色框 完全没有对上

<img width="717" alt="2024-11-25_110607" src="https://github.com/user-attachments/assets/24ddc7a0-5b49-4c59-8b96-aa15551a7166">
<img width="522" alt="2024-11-25_110557" src="https://github.com/user-attachments/assets/adce5b15-d516-4023-9a5a-11e791c3d851">
<img width="623" alt="2024-11-25_110547" src="https://github.com/user-attachments/assets/9593b02b-dea2-4695-8a5f-a9a285fee8e7">

**Comment by cathy345345** [comment]
复现测试的 PDF 文档 https://arxiv.org/pdf/2409.10542

**Comment by Byaidu** [comment]
可以暂时先用双语文档跳转

**Comment by reycn** [comment]
这个暂时不修复吧？因为按链接来识别的话，会影响翻译的上下文进而影响翻译的效果

**Comment by cathy345345** [comment]
> 可以暂时先用双语文档跳转
嗯嗯，好的
