### ISSUE TITLE
希望可以使用国内的qwen模型，qwen-long的API使用起来非常实惠，还不会有网络限制

### ISSUE THREAD

**Issue by cathy345345** [Byaidu/PDFMathTranslate#124]
希望可以使用国内的qwen模型，qwen-long的API使用起来非常实惠，还不会有网络限制
<img width="768" alt="2024-11-25_112611" src="https://github.com/user-attachments/assets/f34dc1c4-ba78-4adb-a5df-a54fc9965f92">
<img width="587" alt="2024-11-25_112410" src="https://github.com/user-attachments/assets/b03e40b6-1b4f-4ac5-a692-40cc79e12825">

**Comment by Byaidu** [comment]
感谢感谢，方便的话可以发个pr

**Comment by reycn** [comment]
Qwen 支持 OpenAI 接口，可以尝试直接自定义 open-ai 服务地址即可。

参考资料：https://help.aliyun.com/zh/dashscope/developer-reference/qwen-long-api
