### ISSUE TITLE
feat (gui): translate file via link

### ISSUE THREAD

**Issue by Byaidu** [Byaidu/PDFMathTranslate#126]
## 功能描述
翻译页面支持文档链接，省去下载和上传的操作

**Comment by reycn** [comment]
- [x] CLI supported [@feat (main): support online PDF file(s)](https://github.com/Byaidu/PDFMathTranslate/commit/1263568a31bfb798dc90e068d8222ba88e1e68a8)
- [ ] GUI to be implemented in the next refactored version
