### ISSUE TITLE
加载了DocLayoutModel但未使用

### ISSUE THREAD

**Issue by RonaldJEN** [Byaidu/PDFMathTranslate#129]
## 问题描述
加载了DocLayoutModel但未使用

``
from pdf2zh.doclayout import DocLayoutModel
from pdf2zh import high_level
model = DocLayoutModel.load_available()
``

**Comment by RonaldJEN** [comment]
在代码中未看到调用model的痕迹，想问下大佬，加载这个的作用主要是哪一步呢

**Comment by reycn** [comment]
`obj_patch: dict = pdf2zh.high_level.extract_text_to_fp(fp, **locals())`
