### ISSUE TITLE
大佬，我想问一下，如果要替换google翻译，使用百度翻译的api这种的应该在哪里替换代码呢？

### ISSUE THREAD

**Issue by clareliu1234** [Byaidu/PDFMathTranslate#13]

**Comment by Byaidu** [comment]
translator.py 下面有 BaseTranslator，继承就可以了

**Comment by clareliu1234** [comment]
您好，想问一下，有时候会出现公式没有正常解析出来，这种情况是咋回事呢
![image](https://github.com/user-attachments/assets/8b73eb62-cb72-4441-bf2a-1983908eb916)
![image](https://github.com/user-attachments/assets/5d51bbc3-da62-469b-a7e0-a1d75d552516)

**Comment by Byaidu** [comment]
翻译器的毛病，把 $v16$ 翻译成 16美元 了

**Comment by zhgng** [comment]
你好，礼貌问问你是怎么运行成功的啊？我这边总是显示pdf文件不存在。我是电脑小白，完全不懂这些，但是马上要做毕业论文，必须看文献……求帮忙看看是不是我哪里输入的有问题
![a](https://github.com/user-attachments/assets/74e54e64-c34d-4e74-9203-3304f91e123c)

**Comment by reycn** [comment]
> 你好，礼貌问问你是怎么运行成功的啊？我这边总是显示pdf文件不存在。我是电脑小白，完全不懂这些，但是马上要做毕业论文，必须看文献……求帮忙看看是不是我哪里输入的有问题 ![a](https://private-user-images.githubusercontent.com/109174689/388214798-74e54e64-c34d-4e74-9203-3304f91e123c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNzAyNzEsIm5iZiI6MTczMjE2OTk3MSwicGF0aCI6Ii8xMDkxNzQ2ODkvMzg4MjE0Nzk4LTc0ZTU0ZTY0LWMzNGQtNGU3NC05MjAzLTMzMDRmOTFlMTIzYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMVQwNjE5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MWNhYTIwMmIyYTAyZGFjZWIyMzg2NzY5NTJkYjJjNzJhNzBkY2EwZDA0ZTAyZWM4NzFhOTVmNDhkMGRjZDkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-77mAwWM53oDA8N0mCnFkopUaieqUtBttJPhFbAzt9s)

https://github.com/Byaidu/PDFMathTranslate/wiki/FAQ---%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#the-following-files-do-not-exist-examplepdf--%E4%BB%A5%E4%B8%8B%E6%96%87%E4%BB%B6%E4%B8%8D%E5%AD%98%E5%9C%A8-examplepdf

**Comment by clareliu1234** [comment]
> > 你好，礼貌问问你是怎么运行成功的啊？我这边总是显示pdf文件不存在。我是电脑小白，完全不懂这些，但是马上要做毕业论文，必须看文献……求帮忙看看是不是我哪里输入的有问题 ![a](https://private-user-images.githubusercontent.com/109174689/388214798-74e54e64-c34d-4e74-9203-3304f91e123c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNzAyNzEsIm5iZiI6MTczMjE2OTk3MSwicGF0aCI6Ii8xMDkxNzQ2ODkvMzg4MjE0Nzk4LTc0ZTU0ZTY0LWMzNGQtNGU3NC05MjAzLTMzMDRmOTFlMTIzYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMVQwNjE5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MWNhYTIwMmIyYTAyZGFjZWIyMzg2NzY5NTJkYjJjNzJhNzBkY2EwZDA0ZTAyZWM4NzFhOTVmNDhkMGRjZDkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-77mAwWM53oDA8N0mCnFkopUaieqUtBttJPhFbAzt9s)
> 
> https://github.com/Byaidu/PDFMathTranslate/wiki/FAQ---%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#the-following-files-do-not-exist-examplepdf--%E4%BB%A5%E4%B8%8B%E6%96%87%E4%BB%B6%E4%B8%8D%E5%AD%98%E5%9C%A8-examplepdf

你的文件路径不对  输入pdf的绝对路径试试呢
