### ISSUE TITLE
feat (test): unit tests for modules and in ci

### ISSUE THREAD

**Issue by Wybxc** [Byaidu/PDFMathTranslate#130]
## 功能描述

项目目前没有单元测试，这不利于新的贡献者验证自己引入更改的正确性，也不利于理解每个模块的功能。

## TODOs

- [x] 梳理项目的模块结构
- [x] 为每个模块编写单元测试
- [x] 在 CI 中设置测试运行

**Comment by Byaidu** [comment]
项目结构大概是这样子，可能有点粗糙（
- cache.py
  - 缓存翻译
- translator.py
  - 提供多种翻译服务
- doclayout.py
  - 提供 onnx/torch 模型
- converter.py
  - 解析原页面，拆分成不同的段落并解析公式
  - 翻译并缓存段落，调用 translator 和 cache
  - 排版新页面，将公式插入到翻译后的段落
  - 返回页面的新指令流
- high_level.py
  - 解析布局，调用 doclayout
  - 解析页面集合，调用 convertor
  - 返回页面集合的新指令流
- pdf2zh.py
  - 解析命令行
  - 插入新字体
  - 解析文档，调用 high_level
  - 插入页面集合的新指令流
  - 排列双语文档页面
- gui.py
  - 提供用户界面，可配置 recaptcha
- *.py
  - 其余文件继承自 pdfminer，用于解析指令流，基本不需要进行改动，lic 位于 docs

**Comment by Byaidu** [comment]
只有 init 提交的部分都和上游一模一样，只有 converter、high_level 和 pdfinterp 是魔改过来的

converter 负责解析和排版，应该可以把 TextConverter 剥离出来
pdfinterp 负责解析指令流，应该也可以剥离 PDFPageInterpreter
high_level 这里我们把 TextConverter 和 PDFPageInterpreter 替换成自己的，然后调用上游库应该就行

分离之后项目结构应该能简单很多，我这几天试试

**Comment by Byaidu** [comment]
重构完成

**Comment by awwaawwa** [comment]
建议先搞个最基础的CI自动测试，提交PR时简单测测cli和gui能不能跑起来，会不会直接报错

**Comment by reycn** [comment]
- CLI [cmt#550025134a08b18cf507839fa698404179698990](https://github.com/Byaidu/PDFMathTranslate/commit/550025134a08b18cf507839fa698404179698990)
- GUI [cmt#550025134a08b18cf507839fa698404179698990](https://github.com/Byaidu/PDFMathTranslate/commit/550025134a08b18cf507839fa698404179698990)
- Converter [pr#282](https://github.com/Byaidu/PDFMathTranslate/pull/282)

**Comment by Byaidu** [comment]
unit test https://github.com/Byaidu/PDFMathTranslate/pull/282
