### ISSUE TITLE
python翻译功能问题

### ISSUE THREAD

**Issue by wangdp9918** [Byaidu/PDFMathTranslate#131]
python我已经安装好了，“pip install pdf2zh”我也安装好了，在进行翻译得时候遇到了一个问题。
![9c1b6c3172d177b7ebec120c68e75372](https://github.com/user-attachments/assets/de64f54e-91a1-446e-a7ee-1ad866767964)
如上图所示
我选择了一个位于E盘的222.pdf做实验，待程序运行完成 之后，我并没有在E盘中找到翻译后的文档
![501f8e202013a741857b04568935d133](https://github.com/user-attachments/assets/cdbc7553-7816-4e3d-b261-20abbc233f02)
E盘里面还是只有翻译前的原文档
我是不是哪里做错了，劳烦执政，感激不尽
如有可能，希望您能提供一个实际使用的视频

**Comment by Byaidu** [comment]
译文输出在工作目录下

**Comment by Byaidu** [comment]
有 up 主上传的视频教程 https://www.bilibili.com/video/BV1k7BzYEEuk

**Comment by wangdp9918** [comment]
> 有 up 主上传的视频教程 https://www.bilibili.com/video/BV1k7BzYEEuk

老哥您好，up上传的这个视频只有第二种使用方式的讲解，第一种使用方式以及我遇到的问题好像没有涉及到，所以还想劳烦您一下，翻译后的pdf我应该去哪里找呀，不胜感激

**Comment by wangdp9918** [comment]
> 就工作目录啊，C:\User\26258

对不起对不起，我不知道啥叫工作目录，我找到了，就在您说的那里
