### ISSUE TITLE
腾讯机翻服务未找到

### ISSUE THREAD

**Issue by Soclatos** [Byaidu/PDFMathTranslate#133]
已经pip install 了最新的 1.8.0，但用了使用说明中的 -s tencent 的参数，发现报错 ValueError: Unsupported translation service，服务不支持，然后我特意去看了下包的 translator.py 中也没发现 腾讯相关的翻译接口，是啥问题……

![Snipaste_2024-11-27_00-15-25](https://github.com/user-attachments/assets/36b47e35-5071-4ef4-b913-fb820f299dd7)

**Comment by Byaidu** [comment]
这个是下个版本的功能
