### ISSUE TITLE
翻译格式以及无法完全翻译问题

### ISSUE THREAD

**Issue by wangdp9918** [Byaidu/PDFMathTranslate#136]
使用Method II. GUI方法进行翻译，选择openai的gpt-4进行翻译，
部分英文部分未成功翻译，且汉语格式”加粗“与”不加粗“十分杂乱，无法统一
[222-dual.pdf](https://github.com/user-attachments/files/17931579/222-dual.pdf)
翻译完毕文档如上
![image](https://github.com/user-attachments/assets/c1feb248-4f61-4a1c-8e1e-e22c4b15558c)
部分错误如上

**Comment by Byaidu** [comment]
![image](https://github.com/user-attachments/assets/1ba1e054-ad00-4783-9d04-bfacf6d53a13)

我这里所有阅读器（Acrobat/Chrome/WPS）的显示样式都是正常的，没有加粗情况，不知道你是什么环境

没翻译的部分应该是大模型的问题，google 是正常的：

![image](https://github.com/user-attachments/assets/f412d54a-03c4-44c6-94d3-7c430ae9a588)
