### ISSUE TITLE
显示无法在本地缓存中找到请求的文件  

### ISSUE THREAD

**Issue by xiamumaomi** [Byaidu/PDFMathTranslate#137]
图形化的界面里细节显示的是正确配置 
可是进行到百分之30%就会终止
然后就是翻译失败：没有找到请求的文件
## 测试文档
> [!IMPORTANT]
[Pioneering_Chiplet_Technology_and_Design_for_the_AMD_EPYC_and_Ryzen_Processor_Families__Industrial_Product.pdf](https://github.com/user-attachments/files/17932070/Pioneering_Chiplet_Technology_and_Design_for_the_AMD_EPYC_and_Ryzen_Processor_Families__Industrial_Product.pdf)
之前用的日语不行  英语也没法翻译

**Comment by Byaidu** [comment]
![image](https://github.com/user-attachments/assets/6fbf6ad2-302d-4e37-8704-7d1dd3465355)

我这里正常，应该是网络问题

**Comment by xiamumaomi** [comment]
大佬  我挂了全局代理结果显示gui错误让我不要开启全局代理 咋办呀

**Comment by xiamumaomi** [comment]
> 挂代理或者VPN了吗？这个好像也是网络问题，设置了全局代理就正常了。

大佬  我挂了全局代理结果却显示gui错误 让我不要开启全局代理咋办呀

**Comment by milk2715093695** [comment]
> > 挂代理或者VPN了吗？这个好像也是网络问题，设置了全局代理就正常了。
> 
> 大佬 我挂了全局代理结果却显示gui错误 让我不要开启全局代理咋办呀

我也遇到了，如果需要启动GUI的话可以在启动前先关掉代理，此时GUI能正常启动并上传文件，然后再重新打开GUI，最后按翻译，就可以正常用了。

或者干脆直接不启动GUI在命令行操作就不会有这个问题了，代理全程挂着就行。
