### ISSUE TITLE
增加文本翻译的功能

### ISSUE THREAD

**Issue by chensyo** [Byaidu/PDFMathTranslate#141]
非常棒的项目，感谢您的付出！
可以请求增加文本翻译的功能么，类似这种[argos-translate 翻译](https://github.com/argosopentech/argos-translate)

**Comment by hellofinch** [comment]
没太明白需求。可以在详细描述一下吗？

**Comment by chensyo** [comment]
就是直接输入文本，然后就可以翻译，类似百度或者谷歌在线翻译的那种

**Comment by reycn** [comment]
项目需求场景是对复杂 PDF 翻译，文本比这个好的工具有很多，主要是在什么样的场景想要一起在这个工具使用呢？

**Comment by chensyo** [comment]
就是不想搞那么多工具，想要一个界面能处理大部分需求
