### ISSUE TITLE
feat (gui): standalone application

### ISSUE THREAD

**Issue by Wybxc** [Byaidu/PDFMathTranslate#144]
## 功能描述

打包一个可以独立运行的版本，方便直接下载使用。

## 相关技术

可以使用 Pyinstaller 或 nuitka 等工具进行打包。

## 问题

- 目前的配置方式多使用环境变量进行，不太适合在桌面环境中独立运行。

**Comment by reycn** [comment]
哈哈之前尝试过一次，发现打包有点问题，没有深入看，以后考虑！

**Comment by hellofinch** [comment]
可以先尝试把目前使用环境变量的方式转换为使用配置文件的方式。

**Comment by Byaidu** [comment]
pyinstaller 依赖分析好像有点问题，试了下没打包成功

刚才加了个功能差不多的一键启动脚本 `start.bat`，这样也方便之后交互式设置环境变量什么的

**Comment by hellofinch** [comment]
不给个shell脚本吗？：）
