### ISSUE TITLE
feat(doc): contributing guide

### ISSUE THREAD

**Issue by Wybxc** [Byaidu/PDFMathTranslate#145]
## 功能描述

补充一份贡献指南，以指导新的开发者加入对项目的贡献。

贡献指南的内容应包括：
- 如何反馈问题
	- 如何报告一个新问题。
	- 如何提出新功能或改进建议。
- 代码贡献流程
	- 如何设置开发环境。
	- 如何获取项目的源代码。
	- 如何创建分支、提交更改以及发起拉取请求。
- 编码规范：
	- 代码风格指南，包括命名约定、注释风格等。
	- 代码格式化工具和代码质量检查工具的使用。
- 测试指南 (#130)：
	- 如何运行测试。
	- 如何编写和提交新的测试用例。

**Comment by Wybxc** [comment]
> 我自己实践的编译步骤是：
> 
> * 创建虚拟环境（venv）
> * python -m pip install .

可以用 `pip install -e .`，这样安装的是开发版本的符号链接，方便即时开发修改

**Comment by hellofinch** [comment]
提交代码之前使用black对修改的内容进行格式化，方便通过action的check。

**Comment by reycn** [comment]
Draft: https://github.com/Byaidu/PDFMathTranslate/issues/145
Please drop your suggestions here, if any

**Comment by Byaidu** [comment]
https://github.com/Byaidu/PDFMathTranslate/wiki/Contribution-Guide---%E8%B4%A1%E7%8C%AE%E6%8C%87%E5%8D%97
