### ISSUE TITLE
佬儿常用命令是啥

### ISSUE THREAD

**Issue by ZhiYuan1688** [Byaidu/PDFMathTranslate#15]
佬儿常用命令是啥

顺便可以贴一下赞助码

**Comment by Byaidu** [comment]
指哪方面的常用命令？

**Comment by ZhiYuan1688** [comment]
> 指哪方面的常用命令？

pdf2zh 我没加命令感觉效果没演示好

**Comment by Byaidu** [comment]
可以具体描述哪方面没演示好吗，我一般都是不带参数跑的

**Comment by ZhiYuan1688** [comment]
> 可以具体描述哪方面没演示好吗，我一般都是不带参数跑的

一些小问题 没记录 偶尔会碰到 贴个赞助码 支持开源🤣
