### ISSUE TITLE
所以腾讯的环境变量到底该如何设置, 折腾半天总报错

### ISSUE THREAD

**Issue by dowier** [Byaidu/PDFMathTranslate#151]
命令行输入实际的ID和Key(以下做了省略), 报错啊
set TENCENT_SECRET_ID=AKIDOhv4Kpxxxxxxxxxxxxxxxxxxxx
set TENCENT_SECRET_KEY=veUEpDndxxxxxxxxxxxxxxxxxxxx

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\vaelaila\anaconda3\Scripts\pdf2zh.exe\__main__.py", line 7, in <module>
  File "C:\Users\vaelaila\anaconda3\Lib\site-packages\pdf2zh\pdf2zh.py", line 279, in main
    extract_text(**vars(parsed_args))
  File "C:\Users\vaelaila\anaconda3\Lib\site-packages\pdf2zh\pdf2zh.py", line 121, in extract_text
    obj_patch: dict = pdf2zh.high_level.extract_text_to_fp(fp, **locals())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vaelaila\anaconda3\Lib\site-packages\pdf2zh\high_level.py", line 99, in extract_text_to_fp
    device = TextConverter(
             ^^^^^^^^^^^^^^
  File "C:\Users\vaelaila\anaconda3\Lib\site-packages\pdf2zh\converter.py", line 398, in __init__
    raise ValueError("Unsupported translation service")
ValueError: Unsupported translation service

**Comment by dowier** [comment]
- **Tencent Machine Translation**

  See [Tencent Machine Translation](https://www.tencentcloud.com/products/tmt?from_qcintl=122110104)

  Following ENVs are required:
  - `TENCENT_SECRET_ID`, e.g., `export TENCENT_SECRET_ID=xxx`
  - `TENCENT_SECRET_KEY`, e.g, `export TENCENT_SECRET_KEY=xxx`

  ```bash
  pdf2zh example.pdf -s tencent
  ```

我该如何理解这个配置说明,完全不知道key和id该放在哪里,能说清楚一点吗

**Comment by milk2715093695** [comment]
#133 
这里有说，腾讯翻译是下个版本的功能

> * **Tencent Machine Translation**
>   See [Tencent Machine Translation](https://www.tencentcloud.com/products/tmt?from_qcintl=122110104)
>   Following ENVs are required:
>   
>   * `TENCENT_SECRET_ID`, e.g., `export TENCENT_SECRET_ID=xxx`
>   * `TENCENT_SECRET_KEY`, e.g, `export TENCENT_SECRET_KEY=xxx`
>   
>   ```shell
>   pdf2zh example.pdf -s tencent
>   ```
> 
> 我该如何理解这个配置说明,完全不知道key和id该放在哪里,能说清楚一点吗

**Comment by dowier** [comment]
好的,谢谢

**Comment by dowier** [comment]
> 
> 
> #133 
> 这里有说，腾讯翻译是下个版本的功能
> 
> > * **Tencent Machine Translation**
> >   See [Tencent Machine Translation](https://www.tencentcloud.com/products/tmt?from_qcintl=122110104)
> >   Following ENVs are required:
> >   
> >   * `TENCENT_SECRET_ID`, e.g., `export TENCENT_SECRET_ID=xxx`
> >   * `TENCENT_SECRET_KEY`, e.g, `export TENCENT_SECRET_KEY=xxx`
> >   
> >   ```shell
> >   pdf2zh example.pdf -s tencent
> >   ```
> > 
> > 我该如何理解这个配置说明,完全不知道key和id该放在哪里,能说清楚一点吗
> 
> 


那deepl和deeplx的配置呢，能不能做一个文件，或者GUI，只需要填url或者api接口就行了？

**Comment by wangdp9918** [comment]
> > #133
> > 这里有说，腾讯翻译是下个版本的功能
> > > * **Tencent Machine Translation**
> > >   See [Tencent Machine Translation](https://www.tencentcloud.com/products/tmt?from_qcintl=122110104)
> > >   Following ENVs are required:
> > >   
> > >   * `TENCENT_SECRET_ID`, e.g., `export TENCENT_SECRET_ID=xxx`
> > >   * `TENCENT_SECRET_KEY`, e.g, `export TENCENT_SECRET_KEY=xxx`
> > >   
> > >   ```shell
> > >   pdf2zh example.pdf -s tencent
> > >   ```
> > > 
> > > 我该如何理解这个配置说明,完全不知道key和id该放在哪里,能说清楚一点吗
> 
> 那deepl和deeplx的配置呢，能不能做一个文件，或者GUI，只需要填url或者api接口就行了？

deep只用输入key就行了，再用命令行pdf2zh example.pdf -s deepl就可以了，deeplx同理

**Comment by dowier** [comment]
> > > #133
> > > 这里有说，腾讯翻译是下个版本的功能
> > > > * **Tencent Machine Translation**
> > > >   See [Tencent Machine Translation](https://www.tencentcloud.com/products/tmt?from_qcintl=122110104)
> > > >   Following ENVs are required:
> > > >   
> > > >   * `TENCENT_SECRET_ID`, e.g., `export TENCENT_SECRET_ID=xxx`
> > > >   * `TENCENT_SECRET_KEY`, e.g, `export TENCENT_SECRET_KEY=xxx`
> > > >   
> > > >   ```shell
> > > >   pdf2zh example.pdf -s tencent
> > > >   ```
> > > > 
> > > > 我该如何理解这个配置说明,完全不知道key和id该放在哪里,能说清楚一点吗
> > 
> > 那deepl和deeplx的配置呢，能不能做一个文件，或者GUI，只需要填url或者api接口就行了？
> 
> deep只用输入key就行了，再用命令行pdf2zh example.pdf -s deepl就可以了，deeplx同理

关键是这个key输到哪里呢，直接在命令行set key=xxx?

**Comment by hellofinch** [comment]
export TENCENT_SECRET_KEY=xxxx && export TENCENT_SECRET_ID=AKIDxxxxx && pdf2zh xxx
这样的命令试一下，这两个环境变量都是需要的，后续可能这些密钥的设置会换其他的方式导入。

**Comment by dowier** [comment]
> 这个是linux的用法`export TENCENT_SECRET_KEY=xxxx && export TENCENT_SECRET_ID=AKIDxxxxx && pdf2zh xxx`。windows下类似。
> 这样的命令试一下，这两个环境变量都是需要的，后续可能这些密钥的设置会换其他的方式导入。
> 谢谢反馈：）
> 如果使用过程中有bug请及时反馈，我再调整代码。

多谢，我试试

**Comment by reycn** [comment]
hellofinch 这里应该能解决这个问题，暂时关闭 issue。如未解决再打开 issue 即可。
