### ISSUE TITLE
韩文文献的翻译结果与原文一模一样没变化

### ISSUE THREAD

**Issue by AnnaKomnenos** [Byaidu/PDFMathTranslate#153]
## 韩文文献的翻译结果与原文一模一样没变化
在翻译韩文PDF的过程中有些PDF翻译的结果与原文一模一样。
![K(DLF7VZ4}BLB`CX{Z1UDF0](https://github.com/user-attachments/assets/cd8f4164-e4f5-48ab-be37-102b6c77bd7f)
## 测试文档
> [!IMPORTANT]
> 这是是翻译失败的文档。
[translated_The Relationship Between Baekje and Southern-North.pdf](https://github.com/user-attachments/files/17959666/translated_The.Relationship.Between.Baekje.and.Southern-North.pdf)

**Comment by Byaidu** [comment]
他这个韩文的字体名开头是MS，和latex撞了，之后会改进一下匹配规则

**Comment by Byaidu** [comment]
![image](https://github.com/user-attachments/assets/946e2dc9-a0f7-48fa-8e3b-2b1bd967da9f)

你这个版本看起来有点旧，建议更新一下用命令行翻译

**Comment by AnnaKomnenos** [comment]
![image](https://github.com/user-attachments/assets/fe49dc24-4609-4f27-90c0-2ad5c9638171)
更新至1.8.7之后依然无法翻译出来，无论是命令行还是可视化窗口，请问一下上图成功翻译使用了什么参数
原pdf如下：
[ex.pdf](https://github.com/user-attachments/files/18056917/ex.pdf)

**Comment by Byaidu** [comment]
转成pdf/a再翻译
