### ISSUE TITLE
[Enhancement] Bullet point display

### ISSUE THREAD

**Issue by BiboyQG** [Byaidu/PDFMathTranslate#154]
## 问题描述
在对通过PPT导出后的PDF进行翻译的时候，分点符号会被处理成"煉"。
目前测试了Google和OpenAI，都出现了如图所示的问题，因此应该不是translator所引起的问题。

## 图例
左边为测试源文档，右侧为处理后的文档：
<img width="1956" alt="image" src="https://github.com/user-attachments/assets/0b479846-acb4-4dec-8752-d11c7eb13e1e">

## 测试文档
[input.pdf](https://github.com/user-attachments/files/17960893/input.pdf)

**Comment by Byaidu** [comment]
![image](https://github.com/user-attachments/assets/d32f1328-c2ce-4b58-a24d-eff0e6015525)

问题应该解决了，请等待下个版本发布

**Comment by BiboyQG** [comment]
太牛逼了！我立马速速打赏！
