### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by dowier** [Byaidu/PDFMathTranslate#157]
(myenv) λset DEEPLX_SERVER_URL=http://localhost:6119/translate

E:\AI\github\PDFMathTranslate (main -> origin)
(myenv) λpdf2zh "2015Cerium Anomaly at Microscale in Fossils.pdf" -f "(CM[^RT].|MS.|.*Ital)" -c "((|||)|+|= |\d|[\u0080-\ufaff])" -s deeplx
0%| | 0/10 [00:00<?, ?it/s]ERROR:pdf2zh.converter:HTTP error: 404
ERROR:pdf2zh.converter:HTTP error: 404
ERROR:pdf2zh.converter:HTTP error: 404
ERROR:pdf2zh.converter:HTTP error: 404
ERROR:pdf2zh.converter:HTTP error: 404
ERROR:pdf2zh.converter:HTTP error: 404
ERROR:pdf2zh.converter:HTTP error: 404
ERROR:pdf2zh.converter:HTTP error: 404
ERROR:pdf2zh.converter:HTTP error: 404
ERROR:pdf2zh.converter:HTTP error: 404
ERROR:pdf2zh.converter:HTTP error: 404
ERROR:pdf2zh.converter:HTTP error: 404
ERROR:pdf2zh.converter:HTTP error: 404
ERROR:pdf2zh.converter:HTTP error: 404
ERROR:pdf2zh.converter:HTTP error: 404
ERROR:pdf2zh.converter:HTTP error: 404

**Comment by Byaidu** [comment]
建议给readme多读两遍再来

**Comment by hellofinch** [comment]
地址填错了。。。。。没有/translate
