### ISSUE TITLE
MAC系统翻译后能下载对应的-zh和-dual

### ISSUE THREAD

**Issue by Jia-h1** [Byaidu/PDFMathTranslate#165]
python环境为3.11.16，mac为m3。
pdf2zh已经更新到最新版本，运行后，能下载文件，但是文档还是原文档。
## [测试文档]
![输出如图](https://github.com/user-attachments/assets/cbf37993-294d-4d55-a7d3-fbec470e0bf8)
![运行如图](https://github.com/user-attachments/assets/effc9a3e-05d1-4b24-b137-42711fd1f7e9)

[1.pdf](https://github.com/user-attachments/files/17987123/1.pdf)

**Comment by Byaidu** [comment]
目前只能翻译可编辑文档，你下份数字版的就可以正常翻译了：

![image](https://github.com/user-attachments/assets/5ef16254-0b02-46f8-a2f3-3aa2e18fe94e)
