### ISSUE TITLE
请问能否增加一个停止翻译的选项或者按钮

### ISSUE THREAD

**Issue by yang478** [Byaidu/PDFMathTranslate#167]
## 功能描述
现在翻译过程没法被强制打断，有时候参数选错了需要强制停止进程，能否增加一个停止翻译的功能

**Comment by Byaidu** [comment]
现在 threadpool 那里实现的有问题，等有缘人来改 async 了

**Comment by yang478** [comment]
> 现在 threadpool 那里实现的有问题，等有缘人来改 async 了

好的，谢谢回答

**Comment by ios-ios** [comment]
> > 现在 threadpool 那里实现的有问题，等有缘人来改 async 了
> 
> 好的，谢谢回答

请教下，你是在本地部署的吗，我在本地服务器部署了，设置翻译服务器ollana：qwen2.57：72b  不生效，总是报连接异常，可是ollama的服务都是好的，没找到原因

**Comment by yang478** [comment]
> > > 现在 threadpool 那里实现的有问题，等有缘人来改 async 了
> > 
> > 
> > 好的，谢谢回答
> 
> 请教下，你是在本地部署的吗，我在本地服务器部署了，设置翻译服务器ollana：qwen2.57：72b 不生效，总是报连接异常，可是ollama的服务都是好的，没找到原因

我本地docker部署的。ollama不生效的原因有几种，如果是本机，那要用127.0.0.1，如果是不是同一个台机子，那ollama要设置跨域，另外看他终端里怎么报错的，另外确认自己模型id是不是正确的

**Comment by Byaidu** [comment]
supported
