### ISSUE TITLE
Docker运行十几秒后自动退出

### ISSUE THREAD

**Issue by Zxis233** [Byaidu/PDFMathTranslate#168]
## 问题描述
执行`docker run -d --name pdf -p 7860:7860 byaidu/pdf2zh`后，docker运行十几秒后自动退出，且查看日志发现未输出内容

**Comment by Byaidu** [comment]
你访问localhost:7860呢

**Comment by Zxis233** [comment]
> 你访问localhost:7860呢

没有结果。Connection refused.

**Comment by Byaidu** [comment]
啊那就不知道了，我本地和服务器都能正常启动

**Comment by Zxis233** [comment]
是否有办法使docker运行时打印输出日志？

**Comment by Byaidu** [comment]
你不加-d就行

**Comment by Zxis233** [comment]
重启服务器并重新拉取镜像后解决。
