### ISSUE TITLE
在docker运行时,翻译后中文出现乱码

### ISSUE THREAD

**Issue by RonaldJEN** [Byaidu/PDFMathTranslate#170]
## 问题描述
在docker运行时,翻译后中文出现乱码。windows翻译功能正常
是linux 上要额外配置什么吗

**Comment by Byaidu** [comment]
你试试在线demo会不会乱码呢

**Comment by Byaidu** [comment]
在线demo就是最新版镜像，没加额外字体什么的

或者你可以参考下 https://github.com/Byaidu/PDFMathTranslate/issues/168 ，重启再拉镜像试试

**Comment by RonaldJEN** [comment]
@Byaidu 大佬好我经过排查发现主要是这个原因。
在使用 PDFCIDFont 插入文本时，发现生成的 PDF 文件中，文本在某些 PDF 查看器中显示正常，但复制或提取文本时出现乱码。经过排查，问题可能与 ToUnicode CMap 缺失或编码处理不当有关。后面我自己全部替换成noto或msyh.ttf就正常了。

#pdf2zzh.py
        # if lang_out in resfont_map:  # CJK
        #     resfont = resfont_map[lang_out]
        #     font_list.append((resfont, None))
#converter.py
        def raw_string(fcur: str, cstk: str):  # 编码字符串
            if fcur == 'noto':
                return "".join(["%04x" % self.noto.has_glyph(ord(c)) for c in cstk])
            elif isinstance(self.fontmap[fcur], PDFCIDFont):  # 判断编码长度
                return "".join(["%04x" % ord(c) for c in cstk])
            else:
                return "".join(["%02x" % ord(c) for c in cstk])
