### ISSUE TITLE
现在是默认输出两份（一份纯中文，一份双语对照），能否自定义输出纯中文或者双语的？

### ISSUE THREAD

**Issue by Arnold133** [Byaidu/PDFMathTranslate#174]
## 功能描述
现在是默认输出两份（一份纯中文，一份双语对照），能否自定义输出纯中文或者双语的？

**Comment by leegang** [comment]
<img width="1828" alt="image" src="https://github.com/user-attachments/assets/62b8fb3c-b327-4922-9ad1-799ce3928873" /> 参考
https://github.com/WildDataX/Suppr.ai
