### ISSUE TITLE
OpenAI的配置 总是出错

### ISSUE THREAD

**Issue by leoncool23** [Byaidu/PDFMathTranslate#175]
使用最新的版本，Huggingface上使用，将OpenAI配置到环境变量了，总是报错 

===== Application Startup at 2024-12-06 07:47:05 =====

* Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
{'Google': (None, None, None), 'DeepL': ('DEEPL_SERVER_URL', 'DEEPL_AUTH_KEY', None), 'DeepLX': ('DEEPLX_SERVER_URL', 'DEEPLX_AUTH_KEY', None), 'Ollama': ('OLLAMA_HOST', None, None), 'OpenAI': ('OPENAI_BASE_URL', None, 'OPENAI_API_KEY'), 'Azure': ('AZURE_APIKEY', 'AZURE_ENDPOINT', 'AZURE_REGION'), 'Tencent': ('TENCENT_SECRET_KEY', 'TENCENT_SECRET_ID', None)} OpenAI
OPENAI_BASE_URL sk-xxxxx
OPENAI_API_KEY 
Files before translation:

像是API_KEY和Base_URL 参数顺序有问题

**Comment by Byaidu** [comment]
不要clone开发版本……

直接运行pip的发布版就行
