### ISSUE TITLE
feat (gui): option for gui authentication

### ISSUE THREAD

**Issue by MingfuYAN** [Byaidu/PDFMathTranslate#177]
## 功能描述
请描述需要添加的功能，以及是否有类似项目可以参考

首先非常感谢如此优秀的项目！

想要为gradio添加访问密码，只需要在`launch`的时候添加`auth`参数即可，具体可见官方文档。
[https://www.gradio.app/docs/gradio/interface#methods](https://www.gradio.app/docs/gradio/interface#methods)

**Comment by reycn** [comment]
好的，可以作为可选项

**Comment by reycn** [comment]
This feature has been implemented by @hellofinch at [pr#246](https://github.com/Byaidu/PDFMathTranslate/pull/246)
