### ISSUE TITLE
ERROR:pdf2zh.converter:Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by utopeadia** [Byaidu/PDFMathTranslate#179]
## 问题描述
docker部署日志出现大量：ERROR:pdf2zh.converter:Expecting value: line 1 column 1 (char 0)
<img width="582" alt="image" src="https://github.com/user-attachments/assets/7d33a531-683f-47f3-8120-4763930f4993">

## 测试文档
文件超过25M使用onedrive共享
https://1drv.ms/b/s!AhmYn7H9CZIKgorkKtX05lumRFHuOes?e=rUQe7W

**Comment by Byaidu** [comment]
![image](https://github.com/user-attachments/assets/2c826f32-2f63-4cd3-a4ed-c901b218bbed)

我这里没问题，建议检查下网络环境……

**Comment by yifeigit** [comment]
我也出现这种情况，使用的是deepseek的api
