### ISSUE TITLE
deeplx提示ERROR:pdf2zh.converter:'data'

### ISSUE THREAD

**Issue by GeorgeRudd** [Byaidu/PDFMathTranslate#181]
## 问题描述
win11

$env:DEEPLX_ENDPOINT = "https://mydomain.com/translate?token=123"

提示ERROR:pdf2zh.converter:'data'

用谷歌正常

## 测试文档

[1.pdf](https://github.com/user-attachments/files/18052579/1.pdf)

**Comment by Byaidu** [comment]
你需要使用支持高并发的deeplx服务，我这里测试是没问题的

**Comment by Simon-Zhang017** [comment]
> 你需要使用支持高并发的deeplx服务，我这里测试是没问题的

那么这个deeplx需要自己部署吗
