### ISSUE TITLE
系统host修改之后，浏览器可直接打开http://translate.google.com/m，不用科学上网了。为啥用这个就是不能直接用呢？还是要科学上网才能用

### ISSUE THREAD

**Issue by BruceLeeX** [Byaidu/PDFMathTranslate#183]
## 问题描述
系统host修改之后，浏览器可直接打开http://translate.google.com/m，不用科学上网了。
为啥用这个就是不能直接用google翻译呢？还是要科学上网才能用

120.25.234.79 translate.googleapis.com

## 测试文档
> [!IMPORTANT]
> 请提供用于复现测试的 PDF 文档

**Comment by Byaidu** [comment]
这你应该去 requests 库官方下面问怎么不走 hosts，反正 bing 也能不翻墙用

**Comment by BruceLeeX** [comment]
> 这你应该去 requests 库官方下面问怎么不走 hosts，反正 bing 也能不翻墙用

google的解决了，加个s解决了！http变https就可以了

**Comment by Liung** [comment]
上述问题，主要是GoogleTranslator的translate里面，self.session.get中，未提供代理端口，所以requests库使用默认端口连接google。懒的做法是在get方法中增加proxies参数，即：

···
    proxy = {
          'https': "127.0.0.1:", # 你自己的代理端口
          'http': "127.0.0.1:",
    
    }
    response = self.session.get(
        ......
        proxies=proxy,      # 增加代理选项
    )
···
