### ISSUE TITLE
无法正常翻译

### ISSUE THREAD

**Issue by jssdwang06** [Byaidu/PDFMathTranslate#185]
## 问题描述
翻译后的中文和原文档中的英语重叠
![翻译后的文档](https://github.com/user-attachments/assets/ec32cec7-1d80-435c-b59a-e17013df2826)

## 测试文档

[原文档1](https://github.com/user-attachments/files/18053990/1997_Hanisch.et.al_Modeling.of.PLC.behavior.by.means.of.timed.net.condition-event.systems.pdf)

[原文档1翻译后](https://github.com/user-attachments/files/18054002/fananyi.pdf)

## 本地测试

本地测试也会出现类似的问题

操作系统：Windows 10
python 版本：3.9.20
pdf2zh 版本 1.8.7

![翻译后的文档_本地测试](https://github.com/user-attachments/assets/011043f0-238b-4d5c-b4f2-19d5df4eb536)

## 测试文档
[原文档2](https://github.com/user-attachments/files/18053995/1995_Rausch_Hanisch_Net.condition-event.systems.with.multiple.condition.outputs.pdf)

[翻译后的文档_本地测试原文档2](https://github.com/user-attachments/files/18054005/1995_Rausch_Hanisch_Net.condition-event.systems.with.multiple.condition.outputs-zh.pdf)

**Comment by hellofinch** [comment]
扫描件目前处理不了，详见https://github.com/Byaidu/PDFMathTranslate/issues/19
