### ISSUE TITLE
不能翻译

### ISSUE THREAD

**Issue by lhj1304** [Byaidu/PDFMathTranslate#186]
## 问题描述
请对问题进行描述，并提供日志或截图
请确认 issues 中没有相同问题且完整阅读 wiki
**本项目不处理网络环境引发的问题**（例如 empty translation result/connection reset/check_hostname requires server_hostname/certificate verify failed/unable to connect to proxy/LocalEntryNotFoundError）

## 测试文档
> [!IMPORTANT]
无法翻译
[2023.findings-eacl.22.pdf](https://github.com/user-attachments/files/18055400/2023.findings-eacl.22.pdf)

> 请提供用于复现测试的 PDF 文档

**Comment by Byaidu** [comment]
![image](https://github.com/user-attachments/assets/600155da-55a9-4a35-8575-215ee5fc394e)

怎么就不能翻译了，反馈连个截图都不放，浪费别人时间

**Comment by lhj1304** [comment]
![image](https://github.com/user-attachments/assets/6ef8489c-484a-40ef-9583-d7af3af540ca)
[2023.findings-eacl.22-zh (4).pdf](https://github.com/user-attachments/files/18057480/2023.findings-eacl.22-zh.4.pdf)
我刚在官网翻译结果如下
