### ISSUE TITLE
对应字体不一样,导致翻译文字重叠

### ISSUE THREAD

**Issue by noenif** [Byaidu/PDFMathTranslate#187]
![image](https://github.com/user-attachments/assets/237c4cf6-204b-46b0-914e-9f73a79dd282)

**Comment by noenif** [comment]
文件有47M.不知道如何解决.能否提供一个网盘或者啥的,我可以传递过来.

**Comment by Byaidu** [comment]
没事我这里有神经认知科学这本书（

**Comment by Byaidu** [comment]
它原文尺寸不一样，译文尺寸不一样也正常吧，反正这个重叠的情况也不是很多

**Comment by hl-gl** [comment]
请问这个问题解决了吗
