### ISSUE TITLE
这个pdf用google 翻译正常,用bing有问题.

### ISSUE THREAD

**Issue by noenif** [Byaidu/PDFMathTranslate#189]
老哥这个pdf有问题,第六页就报
![image](https://github.com/user-attachments/assets/217c396d-e602-4111-8349-93081e9c5afb)
我用google 翻译正常,google我是全部都翻译了的,用bing有问题.

**Comment by noenif** [comment]
排除网络问题,是pdf问题.

**Comment by noenif** [comment]
我用bing翻译另外一个pdf是正常的.

**Comment by Byaidu** [comment]
可以发下pdf文件看看

**Comment by Byaidu** [comment]
要不然还是google翻译吧，这个bing太菜了我都懒得修

**Comment by noenif** [comment]
> 要不然还是google翻译吧，这个bing太菜了我都懒得修

好像不是bing问题,我把您的代码回退到1.8.6他就正常了.
我截取了问题pdf
[Cognitive Neuroscience, 5th ed The Biology of the Mind (Michael S. Gazzaniga, Richard B. Ivry etc.)-en_1-10.pdf](https://github.com/user-attachments/files/18090302/Cognitive.Neuroscience.5th.ed.The.Biology.of.the.Mind.Michael.S.Gazzaniga.Richard.B.Ivry.etc.-en_1-10.pdf)

**Comment by noenif** [comment]
> 要不然还是google翻译吧，这个bing太菜了我都懒得修

不好意思,搞错了bing有问题.

**Comment by noenif** [comment]
> 要不然还是google翻译吧，这个bing太菜了我都懒得修

大佬这个还能修吗?不止一个pdf.

**Comment by Byaidu** [comment]
emmm所以它是pdf问题还是bing问题

**Comment by noenif** [comment]
> emmm所以它是pdf问题还是bing问题

特定pdf.比如我上传的这个文件.

**Comment by Byaidu** [comment]
bing还是算了吧，或者你要是修好了可以发个pr
