### ISSUE TITLE
能不能在报错的时候,保存退出.然后下次翻译继续原来的地方.

### ISSUE THREAD

**Issue by noenif** [Byaidu/PDFMathTranslate#190]
能不能在报错的时候,保存退出.然后下次翻译继续原来的地方.通过配置文件之类恢复.

现在报错,就是必须强制退出.

**Comment by Byaidu** [comment]
现在差不多就是，有配置翻译缓存的

**Comment by noenif** [comment]
> 现在差不多就是，有配置翻译缓存的
大佬,报错了,他必须要关闭cmd.会一直循环.报那个error.
