### ISSUE TITLE
大佬,能不能做一个书籍管理管理系统,让大家把翻译过的书放上来.

### ISSUE THREAD

**Issue by noenif** [Byaidu/PDFMathTranslate#191]
大佬,能不能做一个书籍管理管理系统,让大家把翻译过的书放上来.这样就不必要坐重复工作了.

添加分类,出版社.作者.用户可以评论这本书翻译的问题,模仿github issue.

对于同一本书可以添加多次上传,让他们传网盘链接.,让用户下载后评分.模拟豆瓣然后选择最好的一本直接下载.这样是建立了一个完善的翻译pdf生态.

然后你可以直接查看这个BUG,类似的.这样就对BUG,还是这个产品都有帮助,后续,还能做to  b ,to  c 的就是收集用户体验.

**Comment by Byaidu** [comment]
那怕不是第二天就DMCA警告了（
