### ISSUE TITLE
某个pdf页面没有被翻译！还是原来的英文

### ISSUE THREAD

**Issue by BruceLeeX** [Byaidu/PDFMathTranslate#192]
## 问题描述
某个pdf页面没有被翻译！还是原来的英文。其余页面仍然正常翻译。

把这一页单独提取出来，还是不能翻译，换了其他的模型api还是这个结果

![9999999](https://github.com/user-attachments/assets/2c6d0cf4-0455-4283-9d33-f455e31e249d)

## 测试文档
> [!IMPORTANT]
> 
[12s.pdf](https://github.com/user-attachments/files/18056697/12s.pdf)

**Comment by Byaidu** [comment]
可能整个页面被识别成图片了，所以里面的内容没有翻译

**Comment by BruceLeeX** [comment]
> 可能整个页面被识别成图片了，所以里面的内容没有翻译

但是里面的英文单词，到了译文这里，您注意下字体的颜色也变了，说明还是提取到了英文

**Comment by BruceLeeX** [comment]
而且译文这里的英文也是可以编辑复制的

**Comment by Byaidu** [comment]
即便图片里的文字也是先提取再贴回去原处的（不保留颜色）
