### ISSUE TITLE
大佬您好我翻译一个3700页的书籍遇到的问题

### ISSUE THREAD

**Issue by noenif** [Byaidu/PDFMathTranslate#193]
![image](https://github.com/user-attachments/assets/21404ee3-a945-4a54-a964-1983d4829db2)
亲爱的大佬,我想问一个问题,对于里面的报错,是否有重试机制,还是直接跳过了这处翻译,或是直接把文本抛弃了.

能否让我们在翻译完毕后,对pdf中报错内容进行检测,可以通过日志输出.

**Comment by Byaidu** [comment]
默认是无限重试的，所以不用担心翻译不完整的问题
