### ISSUE TITLE
请问新版取消输出双语版本了吗？

### ISSUE THREAD

**Issue by Slmtdhy** [Byaidu/PDFMathTranslate#195]
## 问题描述
今天在docker中部署了最新版，测试发现没有输出双语对照版本了，印象里之前是默认输出两个版本的？新版是需要什么参数设置一下吗

## 结果如下

![image](https://github.com/user-attachments/assets/366276b7-c5f7-4a2b-a7eb-c39c833b66fc)

**Comment by Byaidu** [comment]
![image](https://github.com/user-attachments/assets/75749c62-40a2-42a6-ae0d-9d440f36c5b0)

你是不是下错版本了

**Comment by Slmtdhy** [comment]
刚检查了下，确实，不知道docker为什么拉的是1.7.6，谢谢
