### ISSUE TITLE
翻译后的文件中英文重叠

### ISSUE THREAD

**Issue by GH-white** [Byaidu/PDFMathTranslate#197]
可以翻译成功，但是翻译之后中英文出现重叠
![image](https://github.com/user-attachments/assets/dfa39e59-52f1-4489-b3cd-cfddc3173528)

相关文档如下
[Massa - 2018 - Private Antitrust Enforcement without Punitive Damages A Half-Baked Reform.pdf](https://github.com/user-attachments/files/18061631/Massa.-.2018.-.Private.Antitrust.Enforcement.without.Punitive.Damages.A.Half-Baked.Reform.pdf)

**Comment by Byaidu** [comment]
暂时不支持扫描件翻译

**Comment by GH-white** [comment]
这个pdf不是可编辑的吗

**Comment by Byaidu** [comment]
> 这个pdf不是可编辑的吗

你放大看一下，确实不是可编辑的

**Comment by GH-white** [comment]
噢噢，原来是这样！期待以后的版本可以支持扫描件翻译！谢谢大佬！

**Comment by jianboy** [comment]
**pdf 可以编辑，不是扫描件，但是翻译依然重叠。**

pdf文件如下：

[JASA-Importance Sampling.pdf](https://github.com/user-attachments/files/18145221/JASA-Importance.Sampling.pdf)

翻译结果：
![image](https://github.com/user-attachments/assets/87c75410-ed0e-4c79-86e8-cd979b8d8318)

**Comment by Byaidu** [comment]
> **pdf 可以编辑，不是扫描件，但是翻译依然重叠。**
> 
> pdf文件如下：
> 
> [JASA-Importance Sampling.pdf](https://github.com/user-attachments/files/18145221/JASA-Importance.Sampling.pdf)
> 
> 翻译结果： ![image](https://private-user-images.githubusercontent.com/11532015/395971382-87c75410-ed0e-4c79-86e8-cd979b8d8318.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMjc0OTUsIm5iZiI6MTczNDMyNzE5NSwicGF0aCI6Ii8xMTUzMjAxNS8zOTU5NzEzODItODdjNzU0MTAtZWQwZS00Yzc5LTg2ZTgtY2Q5NzliOGQ4MzE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA1MzMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2YThjOWFjMDkxZGQwOTdjZjk3NDJkMWRiZGNlN2Q3M2U5YWQ0MmU3NTI4YzBlMTgzMDVjMDhhOTIxYzMxM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TPOvNsP21XOF1na16nBOBk1j97WcDvLmYp1dEPb3qkc)

![image](https://github.com/user-attachments/assets/a81bcaa6-5b22-4bda-b088-97d02e2f82ae)

怎么看都是扫描件吧

**Comment by jianboy** [comment]
不是扫描件：

![image](https://github.com/user-attachments/assets/e15512af-95bd-4bb3-a5f8-0b99f3816228)

所有文本都可以搜索：
![image](https://github.com/user-attachments/assets/11a64214-cf85-4de7-971d-85b6f8aee4b7)

**Comment by jianboy** [comment]
并且：

![image](https://github.com/user-attachments/assets/31211f12-1099-439c-8995-f2ec4f668ff1)

布局出现了问题，有些字体突然很大。
