### ISSUE TITLE
翻译不了

### ISSUE THREAD

**Issue by WhitZard55** [Byaidu/PDFMathTranslate#199]
Executing command: cd "C:\Users\23582\AppData\Local\Temp\tmpvwxn7ar8" && pdf2zh "C:\Users\23582\AppData\Local\Temp\tmpvwxn7ar8\input.pdf" -lo zh-CN -s google 
Files in temp directory: ['input.pdf']
Command output: urllib3.exceptions.SSLError: TLS/SSL connection has been closed (EOF) (_ssl.c:1149)
Command output: 
Command output: The above exception was the direct cause of the following exception:
Command output:
Command output: urllib3.exceptions.ProxyError: ('Unable to connect to proxy', SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1149)')))
Command output:
Command output: The above exception was the direct cause of the following exception:
Command output:
Command output: Traceback (most recent call last):
Command output: File "D:\MiniConda\envs\torch\lib\site-packages\requests\adapters.py", line 667, in send
Command output: resp = conn.urlopen(
Command output: File "D:\MiniConda\envs\torch\lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
Command output: retries = retries.increment(
Command output: File "D:\MiniConda\envs\torch\lib\site-packages\urllib3\util\retry.py", line 519, in increment
Command output: raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
Command output: urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /juliozhao/DocLayout-YOLO-DocStructBench/resolve/main/doclayout_yolo_docstructbench_imgsz1024.pt (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1149)'))))
Command output:
Command output: During handling of the above exception, another exception occurred:
Command output:
Command output: Traceback (most recent call last):
Command output: File "D:\MiniConda\envs\torch\lib\runpy.py", line 194, in _run_module_as_main
Command output: return _run_code(code, main_globals, None,
Command output: File "D:\MiniConda\envs\torch\lib\runpy.py", line 87, in _run_code
Command output: exec(code, run_globals)
Command output: File "D:\MiniConda\envs\torch\Scripts\pdf2zh.exe\__main__.py", line 7, in <module>
Command output: sys.exit(main())
Command output: File "D:\MiniConda\envs\torch\lib\site-packages\pdf2zh\pdf2zh.py", line 274, in main
Command output: extract_text(**vars(parsed_args))
Command output: File "D:\MiniConda\envs\torch\lib\site-packages\pdf2zh\pdf2zh.py", line 89, in extract_text
Command output: pth = hf_hub_download(
Command output: File "D:\MiniConda\envs\torch\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
Command output: return fn(*args, **kwargs)
Command output: File "D:\MiniConda\envs\torch\lib\site-packages\huggingface_hub\file_download.py", line 862, in hf_hub_download
Command output: return _hf_hub_download_to_cache_dir(
Command output: File "D:\MiniConda\envs\torch\lib\site-packages\huggingface_hub\file_download.py", line 925, in _hf_hub_download_to_cache_dir
Command output: (url_to_download, etag, commit_hash, expected_size, head_call_error) = _get_metadata_or_catch_error(
Command output: File "D:\MiniConda\envs\torch\lib\site-packages\huggingface_hub\file_download.py", line 1376, in _get_metadata_or_catch_error
Command output: metadata = get_hf_file_metadata(
Command output: File "D:\MiniConda\envs\torch\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
Command output: return fn(*args, **kwargs)
Command output: File "D:\MiniConda\envs\torch\lib\site-packages\huggingface_hub\file_download.py", line 1296, in get_hf_file_metadata
Command output: r = _request_wrapper(
Command output: File "D:\MiniConda\envs\torch\lib\site-packages\huggingface_hub\file_download.py", line 277, in _request_wrapper
Command output: response = _request_wrapper(
Command output: File "D:\MiniConda\envs\torch\lib\site-packages\huggingface_hub\file_download.py", line 300, in _request_wrapper
Command output: response = get_session().request(method=method, url=url, **params)
Command output: File "D:\MiniConda\envs\torch\lib\site-packages\requests\sessions.py", line 589, in request
Command output: resp = self.send(prep, **send_kwargs)
Command output: File "D:\MiniConda\envs\torch\lib\site-packages\requests\sessions.py", line 703, in send
Command output: r = adapter.send(request, **kwargs)
Command output: File "D:\MiniConda\envs\torch\lib\site-packages\huggingface_hub\utils\_http.py", line 93, in send
Command output: return super().send(request, *args, **kwargs)
Command output: File "D:\MiniConda\envs\torch\lib\site-packages\requests\adapters.py", line 694, in send
Command output: raise ProxyError(e, request=request)
Command output: requests.exceptions.ProxyError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /juliozhao/DocLayout-YOLO-DocStructBench/resolve/main/doclayout_yolo_docstructbench_imgsz1024.pt (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1149)'))))"), '(Request ID: 84002130-1160-486a-97e1-2ebabc446058)')
Command completed with return code: 1
Files after translation: ['input.pdf']
Translation failed: No output files found

**Comment by Byaidu** [comment]
https://github.com/Byaidu/PDFMathTranslate/issues/134
