### ISSUE TITLE
1.6.4 bug

### ISSUE THREAD

**Issue by xxsunyxx** [Byaidu/PDFMathTranslate#20]
every translated pages appears 
翻译后的文本：源文本中的公式表示法$v*$保持不变。直接输出翻译内容，不添加其他文字。$$v_*$$其他正文
翻译后的文本：   公式表示法$v*$保持不变

seems prompts problem
the bug is generated with ollama with qwen2.5
I will try other LLM model for test
![image](https://github.com/user-attachments/assets/5d125ac0-5ca9-42b6-b98d-f6f295cb8ece)

**Comment by Byaidu** [comment]
调教 LLM 太困难了，如果搞定了可以考虑发个 PR

**Comment by xxsunyxx** [comment]
你可以考虑说让他latex保持原样，绝大部分llm对latex的识别度非常高，这种纯规则语言，友好到不要不要的，不用以$分

**Comment by Byaidu** [comment]
```Translate the following markdown source text to {lang_to}. Keep the formula notation $v*$ unchanged.```

原文写的是 markdown 保持原样，感觉改成 latex 区别不大吧
