### ISSUE TITLE
未翻译

### ISSUE THREAD

**Issue by zangxyyds** [Byaidu/PDFMathTranslate#201]
## 问题描述
请对问题进行描述，并提供日志或截图
命令行指令：pdf2zh test1.pdf -li zh-CN -lo en -s openai:qwen

修改了加载本地的模型文件
<img width="1002" alt="截屏2024-12-09 23 35 22" src="https://github.com/user-attachments/assets/0a09d268-55de-4683-b1aa-9c4843a118cd">

修改调用部署的openai方式请求的大模型
<img width="1002" alt="截屏2024-12-09 23 45 06" src="https://github.com/user-attachments/assets/cc08d9be-8ac6-49c9-8bff-7e2ea9e78ee8">

输出中间过程有test1-en.pdf，指令结束后，只有test1-zh.pdf和test1-dual.pdf，但是文章未翻译为英文。

## 测试文档
> [!IMPORTANT]
> 请提供用于复现测试的 PDF 文档
[test1.pdf](https://github.com/user-attachments/files/18064060/test1.pdf)

**Comment by Byaidu** [comment]
目前只能翻译可编辑pdf，你这个是扫描件
