### ISSUE TITLE
是否有支持API 的计划

### ISSUE THREAD

**Issue by haodaohong** [Byaidu/PDFMathTranslate#202]
## 功能描述
请描述需要添加的功能，以及是否有类似项目可以参考

主要是希望服务提供api 接口和其他系统对接

**Comment by Byaidu** [comment]
短期内不会

不过等项目热度上去了，自然会有人来加这个功能（

**Comment by RonaldJEN** [comment]
可以自己改造下,主要注意几点
1.把extract_text/extract_text_to_fp都改为异步的
2.converter.py里的线程执行把它拿掉
news = [worker(item) for item in sstk]
# with concurrent.futures.ThreadPoolExecutor(
#     max_workers=self.thread
# ) as executor:
#     news = list(executor.map(worker, sstk))
3.pdf2zh.py的模型加载放在最外层进行模型导入

**Comment by Byaidu** [comment]
感谢反馈，已添加 https://github.com/Byaidu/PDFMathTranslate?tab=readme-ov-file#api
