### ISSUE TITLE
部分文件未翻译

### ISSUE THREAD

**Issue by lhj1304** [Byaidu/PDFMathTranslate#204]
## 问题描述
官网测试和本地使用Qwen72B模型
![image](https://github.com/user-attachments/assets/4a53a1fd-9440-484d-95a9-290c044710c7)

## 测试文档
[2023.findings-eacl.22-zh (5).pdf](https://github.com/user-attachments/files/18076029/2023.findings-eacl.22-zh.5.pdf)
[2023.findings-eacl.22.pdf](https://github.com/user-attachments/files/18076032/2023.findings-eacl.22.pdf)
[2023.findings-eacl.22-dual (1).pdf](https://github.com/user-attachments/files/18076040/2023.findings-eacl.22-dual.1.pdf)

**Comment by lhj1304** [comment]
官网链接https://pdf2zh.com/

**Comment by hellofinch** [comment]
@Byaidu  我在本地使用deeplx能够正常翻译，但是文字有重叠。

**Comment by Byaidu** [comment]
确实，它这个用webui翻译不了，很神奇

**Comment by hellofinch** [comment]
我在本地用的是webui，deeplx的服务，可以出结果。

**Comment by reycn** [comment]
> 确实，它这个用webui翻译不了，但是命令行就可以，很神奇

还有这种 case，gui 目前调用的就是命令行啊，我研究研究……

**Comment by lhj1304** [comment]
这个文件我用webui和本地命令行都不行，使用的是自己部署的qwen72b模型

**Comment by reycn** [comment]
> 这个文件我用webui和本地命令行都不行，使用的是自己部署的qwen72b模型

好，我也用 qwen 复现

**Comment by hellofinch** [comment]
> > 这个文件我用webui和本地命令行都不行，使用的是自己部署的qwen72b模型
> 
> 好，我也用 qwen 复现

可以考虑看一下大模型返回的内容是什么，我自己部署的deeplx service是可以翻译出内容的，我把出来的PDF放在上边了。
我推测有可能是大模型返回的内容不对劲，我这里用的设备的树莓派5，大模型不好测试。

**Comment by Byaidu** [comment]
![image](https://github.com/user-attachments/assets/6f8d31e9-e7ee-4224-bc93-0e9387720c45)

新版本重新试了一下应该是没问题的

**Comment by hellofinch** [comment]
![image](https://github.com/user-attachments/assets/af37c6db-0aca-4423-b0f2-406c9a38e9da)
同样的，没问题。但是deeplx翻译出来的内容会有一部分重叠。 我认为是段落起始位置的问题。
