### ISSUE TITLE
feat (main, gui): add option for converting non pdf/a to pdf/a

### ISSUE THREAD

**Issue by starxjys** [Byaidu/PDFMathTranslate#206]
## 问题描述
感觉是pdf的问题，其他文档正常

google日志如下，gpt的也试过，也是没有翻译的。官网的一样。

看日志有翻译过程，合成出了问题？

<details>
<summary>google日志</summary>

~\Desktop via 🅒 pdf2zh took 6m24s
❯ pdf2zh -d -p 1 .\1.pdf
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]DEBUG:pdf2zh.converter:
==========[VSTACK]==========

DEBUG:pdf2zh.converter:< 235.0 320.7 217.7 65 KFOLAT+ArialMT 0 > $v0$ = AncillaData AData BData CData DEntangling operationsAncilla readoutτroτcyclem
DEBUG:pdf2zh.converter:
==========[SSTACK]==========

DEBUG:pdf2zh.converter:< 217.69395547199997 320.698124958 320.698124958 555.73606589475 8.503995000000003 False > $v0$ | $v0$
DEBUG:pdf2zh.converter:
==========[VSTACK]==========

DEBUG:pdf2zh.converter:< 12.6 119.1 709.3 49 KGVHWY+SFRM0700 0 > $v0$ = 1,∗
DEBUG:pdf2zh.converter:< 12.6 170.6 709.3 49 KGVHWY+SFRM0700 0 > $v1$ = 1,∗
DEBUG:pdf2zh.converter:< 4.0 242.7 709.3 49 KGVHWY+SFRM0700 0 > $v2$ = 1
DEBUG:pdf2zh.converter:< 4.0 325.0 709.3 49 KGVHWY+SFRM0700 0 > $v3$ = 1
DEBUG:pdf2zh.converter:< 4.0 373.3 709.3 49 KGVHWY+SFRM0700 0 > $v4$ = 1
DEBUG:pdf2zh.converter:< 4.0 429.6 709.3 49 KGVHWY+SFRM0700 0 > $v5$ = 1
DEBUG:pdf2zh.converter:< 12.2 520.9 709.3 49 KGVHWY+SFRM0700 0 > $v6$ = 1,†
DEBUG:pdf2zh.converter:< 3.7 125.3 695.6 49 WMNOAL+SFRM0600 0 > $v7$ = 1
DEBUG:pdf2zh.converter:< 9.0 354.8 642.9 84 EXHJPU+CMMI9 0 > $v8$ = T1
DEBUG:pdf2zh.converter:< 2.6 428.1 580.1 58 EXHJPU+CMMI9 0 > $v9$ = .
DEBUG:pdf2zh.converter:< 2.6 285.9 569.6 58 EXHJPU+CMMI9 0 > $v10$ = .
DEBUG:pdf2zh.converter:< 2.6 111.4 559.2 58 EXHJPU+CMMI9 0 > $v11$ = .
DEBUG:pdf2zh.converter:< 7.2 125.2 559.2 6 UZHLDS+CMSY9 0 > $v12$ = ±
DEBUG:pdf2zh.converter:< 2.6 139.0 559.2 58 EXHJPU+CMMI9 0 > $v13$ = .
DEBUG:pdf2zh.converter:< 9.4 299.5 563.0 0 VPCYBV+CMSY6 0 > $v14$ = −1
DEBUG:pdf2zh.converter:< 13.8 282.6 263.9 31 ARPBMW+CMMI10 0 > $v15$ = χqr
DEBUG:pdf2zh.converter:< 9.4 256.1 251.9 20 ARPBMW+CMMI10 0 > $v16$ = κr
DEBUG:pdf2zh.converter:< 20.0 11.9 216.9 97 Times-Roman 0 > $v17$ = arXiv:2407.10934v1  [quant-ph]  15 Jul 2024
DEBUG:pdf2zh.converter:
==========[SSTACK]==========

DEBUG:pdf2zh.converter:< 730.1200826099999 63.94310679000001 63.94310679000001 73.50697761762241 11.960818944000039 False > B | 乙
DEBUG:pdf2zh.converter:< 730.1200826099999 73.50697761762241 73.50697761762241 548.2952738453856 11.960818944000039 False > enchmarking the readout of a superconducting qubit for repeated measurements | 对超导量子比特的读数进行重复测量的基 准测试
DEBUG:pdf2zh.converter:< 705.69961038 78.64901531999999 78.64901531999999 533.0963816819267 9.96728242200004 True > S. Hazra,$v0$ W. Dai,$v1$ T. Connolly,$v2$ P. D. Kurilovich,$v3$ Z. Wang,$v4$ L. Frunzio,$v5$ and M. H. Devoret$v6$ $v7$Department of Applied Physics, Yale University, New Haven, Connecticut 06520, USA and Yale Quantum Institute, Yale University, New Haven, Connecticut 06520, USA (Dated: July 16, 2024) | S. Hazra、$v0$ W. Dai、$v1$ T. Connolly、$v2$ P. D. Kurilovich、$v3$ Z. Wang、$v4$ L. Frunzio、$v5$ 和 M. H. Devoret$v6$ $v7$耶鲁大学应用物理系，美国康涅狄格州纽黑文 06520 和耶鲁大学耶鲁量子研究所，美国康涅狄格州纽黑文 06520（日期：2024 年 7 月 16 日）
DEBUG:pdf2zh.converter:< 653.3710275 115.99255853999999 106.7752284299999 505.4723827817181 8.970614208000029 True > Readout of superconducting qubits faces a trade-off between measurement speed and unwanted back-action on the qubit caused by the readout drive, such as $v8$ degradation and leakage out of the computational subspace. The readout is typically benchmarked by integrating the readout signal and choosing a binary threshold to extract the “readout fidelity”. We show that such a charac- terization may significantly overlook readout-induced leakage errors. We introduce a method to quantitatively assess this error by repeatedly executing a composite operation —a readout preceded by a randomized qubit-flip. We apply this technique to characterize the dispersive readout of an intrinsically Purcell-protected qubit. We report a binary readout fidelity of 99$v9$63% and quantum non-demolition (QND) fidelity exceeding 99$v10$00% which takes into account a leakage error rate of 0$v11$12 $v12$ 0$v13$03%, under a repetition rate of (380ns)$v14$ for the composite operation. | 超导量子比特的读出面临着测量速度与读出驱动对量子比特造成的不必要的反向作用（例如 $v8$ 退化和计算子空间泄漏）之间的权衡。通常通过积分读出信号并选择二进制阈值来提取“读出保真度”来对读出进行基准测试。我们表明，这种表征可能会大大忽略读出引起的泄漏误差。我们介绍了一种通过重复执行复合操作（读出之前是随机量子比特翻转）来定量评估此误差的方法。我们应用这种技术来表征本质上受 Purcell 保护的量子比特的色散读出。我们报告的二进制读出保真度为 99$v9$63%，量子非破坏 (QND) 保真度超过 99$v10$00%，其中考虑到泄漏错误率为 0$v11$12 $v12$ 0$v13$03%，在复合操作的重复率为 (380ns)$v14$ 的情况下。
DEBUG:pdf2zh.converter:< 527.0356777799998 61.92215739 51.955475249999964 297.15460974416885 9.96728242200004 True > Fast and accurate single-shot qubit readout is crucial for a multitude of quantum computing experiments in- cluding, measurement-based state preparation [1], entan- glement generation [2–4] and quantum error correction (QEC) [5–10]. Recent advancements in superconducting qubit readout coupled with near-quantum-limited mea- surement efficiency have made it possible to demonstrate quantum error correction with both surface code [8, 9] and bosonic codes [5–7]. In these experiments, efficient entropy removal from the quantum system is achieved by repeated application of high fidelity readout and reset of the physical ancilla qubits. A quantum non-demolition (QND) measurement [11] perfectly correlates the post- readout state of the qubit with the readout outcome, alle- viating the need for unconditional reset [12] of the ancilla. A purely dispersive interaction between a qubit and its readout resonator would yield a QND readout scheme. In reality, this interaction is approximately realized in superconducting circuits [13] when an artificial atom is linearly coupled to the readout resonator. The linear hy- bridization of the qubit and the readout resonator leads to Purcell decay of the qubit. This prevents arbitrary increase of the qubit-resonator dispersive interaction $v15$ and the external coupling rate of the resonator $v16$, which sets a maximum speed of the readout for a given power. Moreover, at higher readout power, the dispersive ap- proximation breaks down [14], causing readout-induced leakage [15, 16] into the non-computational states of the physical qubit. These limitations prohibit the simultane- ous pursuit of the readout speed, fidelity and QND-ness. | 快速准确的单次量子比特读出对于大量量子计算实验至关重要，包括基于测量的状态准备 [1]、纠缠生成 [2–4] 和量子误差校正 (QEC) [5–10]。超导量子比特读出方面的最新进展加上接近量子极限的测量效率，使得使用表面码 [8, 9] 和玻色子码 [5–7] 展示量子误差校正成为可能。在这些实验中，通过反复应用高保真读出和物理辅助量子比特的复位，可以有效地从量子系统中去除熵。量子非拆除 (QND) 测量 [11] 将量子比特的读出后状态与读出结果完美关联，从而无需对辅助量子比特进行无条件复位 [12]。量子比特与其读出谐振器之间的纯色散相互作用将产生 QND 读出方案。实际上，当人造原子线性耦合到读出谐振器时，这种相互作用在超导电路 [13] 中近 似实现。量子比特和读出谐振器的线性杂化导致量子比特的珀塞尔衰变。这阻止了量子比特-谐振器色散相互作用 $v15$ 和谐振器外部耦合率 $v16$ 的任意增加，这设定了给定功率下读出的最大速度。此外，在较高的读出功率下，色散近似会失效 [14]，导致读出引起的泄漏 [15, 16] 进入物理量子比特的非计算状态。这些限制禁止同时追求读出速度、保真度和 QND 性。
DEBUG:pdf2zh.converter:< 163.97511947999988 61.92215738999996 51.955475249999964 297.1543878599321 9.967282422000011 True > In QEC, entangling operations and ancilla readouts are repeated, as illustrated in Fig.1. The readout-induced leakage errors can leave the ancilla in undesirable highly- excited states for multiple cycles, and can also spread into neighbouring qubits [17]. Thus, even a small leak- age probability poses a greater threat compared to dis- crimination error or Pauli error. Often, the “readout fi- delity” [1, 18–23] extracted from the binary-thresholded outcomes is used as the only metric to experimentally | 在 QEC 中，纠缠操作和辅助读出重复进行，如图 1 所示。读出引起的泄漏误差可能会使辅助处于 不良的高激发态多个周期，并且还会扩散到相邻的量子位 [17]。因此，即使是很小的泄漏概率也会比鉴别误差或泡利误差造成更大的威 胁。通常，从二进制阈值结果中提取的“读出保真度”[1, 18–23] 被用作实验性地检测辅助量子位的唯一指标。
DEBUG:pdf2zh.converter:< 527.0356777799998 315.0920913599999 315.0920913599999 560.2912258541688 9.96728242200004 True > optimize the readout parameters. While such a metric is sufficient to quantify the Pauli error (occurring during the readout process) and the discrimination error, it fails to faithfully identify readout-induced leakage, especially if the latter occurs with a low probability compared to other readout errors. The standard measure of QND-ness as the correlation of two successive binary readout out- comes [21–23] also overlooks leakage when the readout outcomes of the leakage states predominantly fall on one side of the threshold. Therefore, such methods do not reflect the true character of the repeated readout opera- tions. Is there a complete way to benchmark the readout operation with binary outcome? | 优化读 出参数。虽然这种度量足以量化泡利误差（发生在读出过程中）和鉴别误差，但它无法如实地识别读出引起的泄漏，特别是当后者发生的概率与其他读出误差相比较低时。QND 性的标准度量是两个连续二进制读出结果的相关性 [21–23]，当泄漏状态的读出结果主要落在阈值的一侧时，它也会忽略泄漏。因此，这种方法不能反映重复读出操作的真实特性。有没有一种完整的方法可以用二进制结果对读出操作进行基准测试？
DEBUG:pdf2zh.converter:< 367.4477066699999 325.05977397 315.0920913599999 560.2932193106531 9.967282421999982 True > In this Letter, we demonstrate a novel readout bench- marking technique, “pseudo-syndrome detection”, where we mimic a syndrome detection cycle in QEC by repeat- ing a composite operation—a readout preceded by a ran- dom qubit flip. This method offers a faithful character- ization of the readout under repeated implementations and provides an accurate estimation of the readout QND- ness. We perform the dispersive readout on a Purcell- protected transmon. We optimize the readout pulses | 在本信中，我们展示了一种新颖的读出基准测试技术“伪综合征检测”，其中我们通过重复复合操作（读出之前是随机量子比特翻转）来模拟 QEC 中的综合征检测周期。此方法在重复实施下提供了对读出的忠实表征，并提供了对读出 QND 的准确估计。我们在 Purcell 保护的 transmon 上执行色散读出。我们优化了读出脉冲
DEBUG:pdf2zh.converter:< 134.82142367999998 315.09209136 315.09209136 560.2912718757887 8.970614208 True > Figure 1. A syndrome detection cycle in QEC. Each cycle consists of an ancilla readout preceded by entangling opera- tions with data qubits, mapping the syndrome onto the an- cilla. We characterize the readout performance by mimicing this experiment on a single ancilla, with the “syndrome” arti- ficially generated by randomly applying identity and bit-flip operations. | 图 1. QEC 中的综合征检测周期。每个周期由辅助设备读出组成，随后进行数据量子位纠缠操作，将综合征映射到辅助设备上。我们通过在单个辅助设备上模拟此实验来表征读出性能，其中“综合征”是通过随机应用身份和位翻转操作人工生成的。
DEBUG:pdf2zh.converter:< 216.91599 11.861640000000001 11.861640000000001 31.87104 8.884173599999997 False > $v17$ | $v17$
DEBUG:pdf2zh.converter:
==========[VSTACK]==========

DEBUG:pdf2zh.converter:
==========[SSTACK]==========

100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.64it/s]
(pdf2zh)

</details>

## 测试文档
> [!IMPORTANT]
> [1.pdf](https://github.com/user-attachments/files/18078190/1.pdf)

**Comment by Byaidu** [comment]
可以先转pdf/a再试一下

**Comment by starxjys** [comment]
试了几个在线转的，只有[这个](https://tools.pdf24.org/zh/pdf-to-pdfa#s=1733828720164)可以，但是转换后有黑线，其他的还是英语


[1 (1)-zh.pdf](https://github.com/user-attachments/files/18078399/1.1.-zh.pdf)

<details>
<summary>不知道有没有用的日志</summary>

❯ pdf2zh -d -p 1 '.\1 (1).pdf'
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]DEBUG:pdf2zh.converter:
==========[VSTACK]==========

DEBUG:pdf2zh.converter:< 12.6 119.1 709.3 49 FKODPV+SFRM0700 0 > $v0$ = 1,∗
DEBUG:pdf2zh.converter:< 12.6 170.6 709.3 49 FKODPV+SFRM0700 0 > $v1$ = 1,∗
DEBUG:pdf2zh.converter:< 4.0 242.7 709.3 49 FKODPV+SFRM0700 0 > $v2$ = 1
DEBUG:pdf2zh.converter:< 4.0 325.0 709.3 49 FKODPV+SFRM0700 0 > $v3$ = 1
DEBUG:pdf2zh.converter:< 4.0 373.3 709.3 49 FKODPV+SFRM0700 0 > $v4$ = 1
DEBUG:pdf2zh.converter:< 4.0 429.6 709.3 49 FKODPV+SFRM0700 0 > $v5$ = 1
DEBUG:pdf2zh.converter:< 12.2 520.9 709.3 49 FKODPV+SFRM0700 0 > $v6$ = 1,†
DEBUG:pdf2zh.converter:< 3.7 125.3 695.6 49 ICQQWH+SFRM0600 0 > $v7$ = 1
DEBUG:pdf2zh.converter:< 9.0 354.8 642.9 84 QALLXJ+CMMI9 0 > $v8$ = T1
DEBUG:pdf2zh.converter:< 2.6 428.1 580.1 58 QALLXJ+CMMI9 0 > $v9$ = .
DEBUG:pdf2zh.converter:< 2.6 285.9 569.6 58 QALLXJ+CMMI9 0 > $v10$ = .
DEBUG:pdf2zh.converter:< 2.6 111.4 559.2 58 QALLXJ+CMMI9 0 > $v11$ = .
DEBUG:pdf2zh.converter:< 7.2 125.2 559.2 6 WZXFKJ+CMSY9 0 > $v12$ = ±
DEBUG:pdf2zh.converter:< 2.6 139.0 559.2 58 QALLXJ+CMMI9 0 > $v13$ = .
DEBUG:pdf2zh.converter:< 9.4 299.5 563.0 0 QTOSNN+CMSY6 0 > $v14$ = −1
DEBUG:pdf2zh.converter:< 13.8 282.6 263.9 31 OFIUVC+CMMI10 0 > $v15$ = χqr
DEBUG:pdf2zh.converter:< 9.4 256.1 251.9 20 OFIUVC+CMMI10 0 > $v16$ = κr
DEBUG:pdf2zh.converter:< 235.0 320.7 217.7 65 BRLTET+ArialMT 0 > $v17$ = (cid:65)(cid:110)(cid:99)(cid:105)(cid:108)(cid:108)(cid:97)(cid:68)(cid:97)(cid:116)(cid:97)(cid:32)(cid:65)(cid:68)(cid:97)(cid:116)(cid:97)(cid:32)(cid:66)(cid:68)(cid:97)(cid:116)(cid:97)(cid:32)(cid:67)(cid:68)(cid:97)(cid:116)(cid:97)(cid:32)(cid:68)(cid:69)(cid:110)(cid:116)(cid:97)(cid:110)(cid:103)(cid:108)(cid:105)(cid:110)(cid:103)(cid:32)(cid:111)(cid:112)(cid:101)(cid:114)(cid:97)(cid:116)(cid:105)(cid:111)(cid:110)(cid:115)(cid:65)(cid:110)(cid:99)(cid:105)(cid:108)(cid:108)(cid:97)(cid:32)(cid:114)(cid:101)(cid:97)(cid:100)(cid:111)(cid:117)(cid:116)τ(cid:114)(cid:111)τ(cid:99)(cid:121)(cid:99)(cid:108)(cid:101)(cid:109)
DEBUG:pdf2zh.converter:< 20.0 11.9 216.9 97 GETVBG+Times-Roman 0 > $v18$ = arXiv:2407.10934v1  [quant-ph]  15 Jul 2024
DEBUG:pdf2zh.converter:
==========[SSTACK]==========

DEBUG:pdf2zh.converter:< 730.12 63.943 63.943 73.51164 11.96079999999995 False > B | 乙
DEBUG:pdf2zh.converter:< 730.12 73.51164 73.51164 548.2516350508171 11.96079999999995 False > enchmarking the readout of a superconducting qubit for repeated measurements | 对超导量子比特的读数进行重复测量的基准测试
DEBUG:pdf2zh.converter:< 705.6993 78.6489 78.6489 533.0908428399999 9.96727999999996 True > S. Hazra,$v0$ W. Dai,$v1$ T. Connolly,$v2$ P. D. Kurilovich,$v3$ Z. Wang,$v4$ L. Frunzio,$v5$ and M. H. Devoret$v6$ $v7$Department of Applied Physics, Yale University, New Haven, Connecticut 06520, USA and Yale Quantum Institute, Yale University, New Haven, Connecticut 06520, USA (Dated: July 16, 2024) | S. Hazra、$v0$ W. Dai、$v1$ T. Connolly、$v2$ P. D. Kurilovich、$v3$ Z. Wang、$v4$ L. Frunzio、$v5$ 和 M. H. Devoret$v6$ $v7$耶鲁大学应用物理系，美国康涅狄格州纽黑文 06520 和耶鲁大学耶鲁量子研究所，美国康涅狄格州纽黑文 06520（日期：2024 年 7 月 16 日）
DEBUG:pdf2zh.converter:< 653.37082 115.99251000000001 106.77520000000004 505.54524191706 8.970609999999965 True > Readout of superconducting qubits faces a trade-oﬀ between measurement speed and unwanted back-action on the qubit caused by the readout drive, such as $v8$ degradation and leakage out of the computational subspace. The readout is typically benchmarked by integrating the readout signal and choosing a binary threshold to extract the “readout ﬁdelity”. We show that such a charac- terization may signiﬁcantly overlook readout-induced leakage errors. We introduce a method to quantitatively assess this error by repeatedly executing a composite operation —a readout preceded by a randomized qubit-ﬂip. We apply this technique to characterize the dispersive readout of an intrinsically Purcell-protected qubit. We report a binary readout ﬁdelity of 99$v9$63% and quantum non-demolition (QND) ﬁdelity exceeding 99$v10$00% which takes into account a leakage error rate of 0$v11$12 $v12$ 0$v13$03%, under a repetition rate of (380ns)$v14$ for the composite operation. |  超导量子比特的读出面临着测量速度与读出驱动对量子比特造成的不必要的反向作用（例如 $v8$ 退化和计算子空间泄漏）之间的权衡。通常通过积分读出信号并选择二进制阈值来提取“读出保真度”，以此对读出进行基准测试。我们表明，这种表征可能会显著忽略读出引起的泄漏误差。我们介绍了一种通过重复执行复合操作（读出之前是随机量子比特翻转）来定量评估此误差的方法。我们应用这种技术来表征本质上受 Purcell 保护的量子比特的色散读出。我们报告称，在复合操作的重复率为 (380ns)$v14$ 的情况下，二进制读出保真度为 99$v9$63%，量子非破坏 (QND) 保真度超过 99$v10$00%，其中考虑到泄漏错误率为 0$v11$12 $v12$ 0$v13$03%。
DEBUG:pdf2zh.converter:< 527.03512 61.92318999999995 51.95596999999995 297.1729040418512 9.96727999999996 True > Fast and accurate single-shot qubit readout is crucial for a multitude of quantum computing experiments in- cluding, measurement-based state preparation [1], entan- glement generation [2–4] and quantum error correction (QEC) [5–10]. Recent advancements in superconducting qubit readout coupled with near-quantum-limited mea- surement eﬃciency have made it possible to demonstrate quantum error correction with both surface code [8, 9] and bosonic codes [5–7]. In these experiments, eﬃcient entropy removal from the quantum system is achieved by repeated application of high ﬁdelity readout and reset of the physical ancilla qubits. A quantum non-demolition (QND) measurement [11] perfectly correlates the post- readout state of the qubit with the readout outcome, alle- viating the need for unconditional reset [12] of the ancilla. A purely dispersive interaction between a qubit and its readout resonator would yield a QND readout scheme. In reality, this interaction is approximately realized in superconducting circuits [13] when an artiﬁcial atom is linearly coupled to the readout resonator. The linear hy- bridization of the qubit and the readout resonator leads to Purcell decay of the qubit. This prevents arbitrary increase of the qubit-resonator dispersive interaction $v15$ and the external coupling rate of the resonator $v16$, which sets a maximum speed of the readout for a given power. Moreover, at higher readout power, the dispersive ap- proximation breaks down [14], causing readout-induced leakage [15, 16] into the non-computational states of the physical qubit. These limitations prohibit the simultane- ous pursuit of the readout speed, ﬁdelity and QND-ness. | 快速而准确的单次量子比特读出对于大量量子计算实验至关重要，包括基于测量的状态准备 [1]、纠缠生成 [2–4] 和量子误差校正 (QEC) [5–10]。超导量子比特读出方面的最新进展，加上近量子极限的测量效率，使得使用表面码 [8, 9] 和玻色子码 [5–7] 展示量子误差校正 成为可能。在这些实验中，通过反复应用高保真读出和物理辅助量子比特的复位，可以有效地从量子系统中去除熵。量子非破坏 (QND)  测量 [11] 将量子比特的读出后状态与读出结果完美关联，从而无需对辅助量子比特进行无条件复位 [12]。量子比特与其读出谐振器之 间的纯色散相互作用将产生 QND 读出方案。实际上，当人造原子线性耦合到读出谐振器时，这种相互作用在超导电路 [13] 中近似实现 。量子比特和读出谐振器的线性杂化导致量子比特的 Purcell 衰变。这阻止了量子比特-谐振器色散相互作用 $v15$ 和谐振器外部耦合 率 $v16$ 的任意增加，这设定了给定功率下读出的最大速度。此外，在较高的读出功率下，色散近似会失效 [14]，导致读出引起的泄漏 [15, 16] 进入物理量子比特的非计算状态。这些限制禁止同时追求读出速度、保真度和 QND 性。
DEBUG:pdf2zh.converter:< 163.97649999999956 61.92276999999995 51.95596999999995 297.16340556057594 9.967279999999988 True > In QEC, entangling operations and ancilla readouts are repeated, as illustrated in Fig.1. The readout-induced leakage errors can leave the ancilla in undesirable highly- excited states for multiple cycles, and can also spread into neighbouring qubits [17]. Thus, even a small leak- age probability poses a greater threat compared to dis- crimination error or Pauli error. Often, the “readout ﬁ- delity” [1, 18–23] extracted from the binary-thresholded outcomes is used as the only metric to experimentally | 在 QEC 中，纠缠操作和辅助读出重复进行，如图 1 所示。读出引起的泄漏误差可能会使辅助处于不良的高激发态多个周期，并且还会扩散到相邻的量子位 [17]。因此，与鉴别误差或泡利误差相比，即使是很小的泄漏概率也会造成更大 的威胁。通常，从二进制阈值结果中提取的“读出保真度”[1, 18–23] 被用作实验性地检测辅助量子位的唯一指标。
DEBUG:pdf2zh.converter:< 527.0372999999995 315.0929699999999 315.0929699999999 560.288891264608 9.96727999999996 True > optimize the readout parameters. While such a metric is suﬃcient to quantify the Pauli error (occurring during the readout process) and the discrimination error, it fails to faithfully identify readout-induced leakage, especially if the latter occurs with a low probability compared to other readout errors. The standard measure of QND-ness as the correlation of two successive binary readout out- comes [21–23] also overlooks leakage when the readout outcomes of the leakage states predominantly fall on one side of the threshold. Therefore, such methods do not reﬂect the true character of the repeated readout opera- tions. Is there a complete way to benchmark the readout operation with binary outcome? | 优化读出参 数。虽然这样的指标足以量化泡利误差（发生在读出过程中）和鉴别误差，但它无法如实地识别读出引起的泄漏，特别是当后者发生的概率与其他读出误差相比较低时。QND 性的标准度量是两个连续二进制读出结果的相关性 [21–23]，当泄漏状态的读出结果主要落在阈值的一侧时，它也会忽略泄漏。因此，这种方法不能反映重复读出操作的真实特性。有没有一种完整的方法可以用二进制结果对读出操作进行基准测试？
DEBUG:pdf2zh.converter:< 367.4502999999993 325.0605499999999 315.0929699999999 560.2680979018352 9.967280000000017 True > In this Letter, we demonstrate a novel readout bench- marking technique, “pseudo-syndrome detection”, where we mimic a syndrome detection cycle in QEC by repeat- ing a composite operation—a readout preceded by a ran- dom qubit ﬂip. This method oﬀers a faithful character- ization of the readout under repeated implementations and provides an accurate estimation of the readout QND- ness. We perform the dispersive readout on a Purcell- protected transmon. We optimize the readout pulses | 在本信中，我们展示了一种新颖的读出基准测试技术“伪综合征检测”，其中我们通过重复复合操作（读出之前是随机量子比 特翻转）来模拟 QEC 中的综合征检测周期。此方法在重复实施下提供了对读出的忠实表征，并提供了对读出 QND 的准确估计。我们在 Purcell 保护的 transmon 上执行色散读出。我们优化了读出脉冲
DEBUG:pdf2zh.converter:< 217.694 320.694 320.694 555.7364908 8.50399999999999 False > $v17$ | $v17$
DEBUG:pdf2zh.converter:< 134.821 315.092 315.092 560.3218049058747 8.970609999999994 True > Figure 1. A syndrome detection cycle in QEC. Each cycle consists of an ancilla readout preceded by entangling opera- tions with data qubits, mapping the syndrome onto the an- cilla. We characterize the readout performance by mimicing this experiment on a single ancilla, with the “syndrome” arti- ﬁcially generated by randomly applying identity and bit-ﬂip operations. | 图 1. QEC 中的综 合征检测周期。每个周期由辅助设备读出组成，随后进行与数据量子位的纠缠操作，将综合征映射到辅助设备上。我们通过在单个辅助设备上模拟此实验来表征读出性能，其中“综合征”是通过随机应用身份和位翻转操作人工生成的。
DEBUG:pdf2zh.converter:< 216.916 11.861699999999999 11.861699999999999 31.8711 8.884173599999997 False > $v18$ | $v18$
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.78it/s]
(pdf2zh)

</details>

**Comment by Byaidu** [comment]
有黑线是因为你加了-d参数，这是个调试功能

**Comment by leegang** [comment]
<img width="1898" alt="image" src="https://github.com/user-attachments/assets/62e48dee-57ed-4f0b-9a8c-ead61b9f0b91" />

我用这个项目翻译的  https://github.com/WildDataX/Suppr.ai

**Comment by reycn** [comment]
The feature has been implemented in [CMT#6b293ab38e9d4c67b82a7fbb4837fa4e80416012](https://github.com/Byaidu/PDFMathTranslate/commit/6b293ab38e9d4c67b82a7fbb4837fa4e80416012).

For now, auto-converting is not enabled; in other words, users have to explicitly specify `-cp` or `--compatible` to enable the conversion.
