### ISSUE TITLE
页面选择能否增加自定义页数

### ISSUE THREAD

**Issue by Phosphenenene** [Byaidu/PDFMathTranslate#207]
## 功能描述
RT. 希望能增加页面选择自定义页数。
比如 书封面 书信息之类的页面并不需要翻译，
可以自定义页面，例如5-100页这样，
减少不必要的翻译。谢谢。

**Comment by Byaidu** [comment]
https://github.com/Byaidu/PDFMathTranslate?tab=readme-ov-file#full--partial-document-translation
