### ISSUE TITLE
阿拉伯数字显示乱码

### ISSUE THREAD

**Issue by Soclatos** [Byaidu/PDFMathTranslate#21]
发现pdf翻译后，有些阿拉伯数字和字符显示乱码，感觉是不同的字体有关，通篇还是挺多乱码的。原始pdf我贴在附件里了
<img width="1739" alt="image" src="https://github.com/user-attachments/assets/cd0ca825-ef22-46e3-bafa-b6659699127c">
[excample.pdf](https://github.com/user-attachments/files/17657875/excample.pdf)

**Comment by Byaidu** [comment]
感谢反馈，已修复
