### ISSUE TITLE
部署在vps上，可以后台运行翻译完成后再提取文档吗？

### ISSUE THREAD

**Issue by Cohen8s** [Byaidu/PDFMathTranslate#210]
## 功能描述
请描述需要添加的功能，以及是否有类似项目可以参考
现在好像要保持网页才行，刷新文档就没有了

**Comment by Cohen8s** [comment]
类似于彩云小译的翻译模式

**Comment by Byaidu** [comment]
之后会有API支持这个功能，https://github.com/Byaidu/PDFMathTranslate/issues/202
