### ISSUE TITLE
翻译后仍是英语, 并且与原文堆叠在一起

### ISSUE THREAD

**Issue by SEML04** [Byaidu/PDFMathTranslate#212]
### 问题

翻译过程正常,能输出文件.

但是输出文件仍然是英语,并且直接堆叠在原文上:

![img](https://github.com/user-attachments/assets/4218f3d5-4d12-46ae-b2b5-9f3324557a8a)

试着转换为pdf/a模式但仍然无效.

### 附件

待翻译文献:

[Primes in Tuple I - G.P.Y.pdf](https://github.com/user-attachments/files/18095928/Primes.in.Tuple.I.-.G.P.Y.pdf)

翻译后:

[Primes in Tuple I - G.P.Y-zh.pdf](https://github.com/user-attachments/files/18095951/Primes.in.Tuple.I.-.G.P.Y-zh.pdf)

**Comment by Byaidu** [comment]
目前只能翻译可编辑文档，https://github.com/Byaidu/PDFMathTranslate/issues/19

**Comment by SEML04** [comment]
> 目前只能翻译可编辑文档，#19

OK,十分感谢!
