### ISSUE TITLE
从缓存读取结果的功能建议默认关闭

### ISSUE THREAD

**Issue by ozil56** [Byaidu/PDFMathTranslate#214]
我用的是本地ollama来执行翻译。我尝试用不同模型对同一本书进行翻译，以对比不同模型的效果。
但我发现，第二次它实际上没有执行真正的翻译：而是直接从某个缓存处读取了已经翻译过的结果——这个路径位于%temp%\cache。当我把cache目录中的一个子目录删掉后，大模型真正重新开始工作了。

从生产力的角度，从缓存中读取已经存在的结果，这似乎是一个很好的设置，可以节约资源。但是：
1、真正的生产场景，不太可能出现完全相同的待翻译原文，从缓存中读取的设置对资源的节约效果有限；
2、不能确保翻译质量的一致性：当使用较大、较好的模型翻译时，它可能会错误地读取了之前用较小、较差模型翻译的结果。

而这种设置对测试来说很不友好。

建议：缓存机制默认关闭，可以通过开关手动打开。

**Comment by ozil56** [comment]
目前可以通过临时性地修改 \lib\site-packages\pdf2zh\cache.py 来解决。

**Comment by Byaidu** [comment]
感谢反馈，已修复cache，请等待版本更新
