### ISSUE TITLE
针对AI翻译，是否支持模型的temperature等值？

### ISSUE THREAD

**Issue by BaseBlank** [Byaidu/PDFMathTranslate#215]
## 功能描述
目前的各大模型都支持temperature、topk等参数，是否可以将这些参数作为超参数嵌入命令行中，允许设置。

Current major models all support parameters such as temperature and top-k. Is it possible to embed these parameters as hyperparameters into the command line, allowing them to be set?

Thanks!!!

**Comment by Byaidu** [comment]
温度参数有时破坏公式标记，所以暂时不考虑支持
