### ISSUE TITLE
这个数学公式无法翻译

### ISSUE THREAD

**Issue by noenif** [Byaidu/PDFMathTranslate#217]
这是原文的pdf.
[Encyclopedia of Algorithms (Ming-Yang Kao (Editor)) (Z-Library)_189-198.pdf](https://github.com/user-attachments/files/18113891/Encyclopedia.of.Algorithms.Ming-Yang.Kao.Editor.Z-Library._189-198.pdf)
![dd85458667aa874dbc9c65cf2b124c8c](https://github.com/user-attachments/assets/e7d7edc4-e2ed-4f72-b23f-ca395de128c9)
![image](https://github.com/user-attachments/assets/6e8c7b7a-a54e-4b86-ae6c-db6e98fccdcf)
这是中英对照的pdf.
[Uploading Encyclopedia of Algorithms Ming-Yang Kao Editor _189-19-dual.pdf…]()

**Comment by noenif** [comment]
![image](https://github.com/user-attachments/assets/6e8c7b7a-a54e-4b86-ae6c-db6e98fccdcf)

**Comment by noenif** [comment]
还不少,很多相似的.这是中英对照的pdf.
[Uploading Encyclopedia of Algorithms Ming-Yang Kao Editor _189-19-dual.pdf…]()

**Comment by Byaidu** [comment]
可以加上字体过滤参数-f ".*MT2"

**Comment by noenif** [comment]
> 可以加上字体过滤参数-f ".*MT2"

大佬厉害,请问以后遇到类似问题,不打扰您,我如何排查呢.就是查看字体就行了嘛?

**Comment by Byaidu** [comment]
对的，比如用WPS编辑模式看一下公式的字体名就行

**Comment by noenif** [comment]
> 对的，比如用WPS编辑模式看一下公式的字体名就行



> MT2

![image](https://github.com/user-attachments/assets/cf7e3609-67b8-4608-a5e8-969223b907d8)
大佬但是我wps显示的是这个

**Comment by Byaidu** [comment]
你看着后面不是有个MT2MIT

**Comment by noenif** [comment]
> 你看着后面不是有个MT2MIT

懂了,我现在把你的f加上了之前有几本出现乱码的搞定了,那c是 保留的吗 .

**Comment by Byaidu** [comment]
-c是按字符过滤，这个一般不用设置，用默认的就行

**Comment by noenif** [comment]
> -c是按字符过滤，这个一般不用设置，用默认的就行

ok

**Comment by noenif** [comment]
> -c是按字符过滤，这个一般不用设置，用默认的就行

老哥你好,当我加上了"(CM[^RT].*|MS.*|.*Ital|.*MT2)"之后好像就有点问题,有些书是因为*MT2,有些因为.*Ital,但我翻译只需要*MT2的书籍但是我带上了.*Ital之后,所有.*Ital字体都不翻译了.
![image](https://github.com/user-attachments/assets/da6a8e50-c523-495a-be7c-d997784d75b6)
![image](https://github.com/user-attachments/assets/caf119ee-156c-41a3-a17f-b9329236bc1b)



这个是我只有  -f "*MT2"那怎么办,就算一个pdf,可能也会遇到多个不同的字体吧
![image](https://github.com/user-attachments/assets/105410b1-0cc2-4810-809a-120a3d64a345)

**Comment by Byaidu** [comment]
这个确实不太好处理，默认策略是直接跳过斜体的

**Comment by noenif** [comment]
> 这个确实不太好处理，默认策略是直接跳过斜体的

默认跳过吗.我本来有一本书斜体翻译会多出来
![image](https://github.com/user-attachments/assets/3190a4bc-6072-45e4-9196-33d08ed5ba49)
然后我去设置了"(CM[^RT].*|MS.*|.*Ital)",他就正常了翻译.
![image](https://github.com/user-attachments/assets/99ae6174-a914-4ed6-84c2-b16cba55d0f4)
但这种情况他是正常翻译的啊.

然后我再那本算法书上.使用"(CM[^RT].|MS.|.*Ital|.MT2)"就导致Ital不翻译了.

**Comment by Byaidu** [comment]
> > 这个确实不太好处理，默认策略是直接跳过斜体的
> 
> 默认跳过吗.我本来有一本书斜体翻译会多出来 ![image](https://private-user-images.githubusercontent.com/25174520/395480318-3190a4bc-6072-45e4-9196-33d08ed5ba49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNzc3NTUsIm5iZiI6MTczNDA3NzQ1NSwicGF0aCI6Ii8yNTE3NDUyMC8zOTU0ODAzMTgtMzE5MGE0YmMtNjA3Mi00NWU0LTkxOTYtMzNkMDhlZDViYTQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDA4MTA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5YzQ3NGUzOTgyOGZkMDAxMTM3MWJiMDI5YzQ0YmFiMTY5NjBlOTM0YjRlNTMwYWQyNmU3Nzc5NGFjMzcwNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QKn4w6vVQITwEZ6vktiPT83RZKaMe82otFVIfXCEhzI) 然后我去设置了"(CM[^RT]._|MS._|.*Ital)",他就正常了翻译. ![image](https://private-user-images.githubusercontent.com/25174520/395481048-99ae6174-a914-4ed6-84c2-b16cba55d0f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNzc3NTUsIm5iZiI6MTczNDA3NzQ1NSwicGF0aCI6Ii8yNTE3NDUyMC8zOTU0ODEwNDgtOTlhZTYxNzQtYTkxNC00ZWQ2LTg0YzItYjE2Y2JhNTVkMGY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDA4MTA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4ZjFjOWNlMDU3ZWVkNzgxM2E3MzM3YzcxM2NlOGYyZTc3NzI5MzI3MjM4YTMyZDFkOWQ4ZTMzNTUzMWMzM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bK6cyVXfsqn_eIzFOyn8JBg9PDBsQ4gi5HuP_jZM6d4) 但这种情况他是正常翻译的啊.
> 
> 然后我再那本算法书上.使用"(CM[^RT].|MS.|.*Ital|.MT2)"就导致Ital不翻译了.

上面那个$v2是小概率错误，给缓存删掉再翻译一次就好了

**Comment by noenif** [comment]
> > > 这个确实不太好处理，默认策略是直接跳过斜体的
> > 
> > 
> > 默认跳过吗.我本来有一本书斜体翻译会多出来 ![image](https://private-user-images.githubusercontent.com/25174520/395480318-3190a4bc-6072-45e4-9196-33d08ed5ba49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNzc3NTUsIm5iZiI6MTczNDA3NzQ1NSwicGF0aCI6Ii8yNTE3NDUyMC8zOTU0ODAzMTgtMzE5MGE0YmMtNjA3Mi00NWU0LTkxOTYtMzNkMDhlZDViYTQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDA4MTA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5YzQ3NGUzOTgyOGZkMDAxMTM3MWJiMDI5YzQ0YmFiMTY5NjBlOTM0YjRlNTMwYWQyNmU3Nzc5NGFjMzcwNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QKn4w6vVQITwEZ6vktiPT83RZKaMe82otFVIfXCEhzI) 然后我去设置了"(CM[^RT]._|MS._|.*Ital)",他就正常了翻译. ![image](https://private-user-images.githubusercontent.com/25174520/395481048-99ae6174-a914-4ed6-84c2-b16cba55d0f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNzc3NTUsIm5iZiI6MTczNDA3NzQ1NSwicGF0aCI6Ii8yNTE3NDUyMC8zOTU0ODEwNDgtOTlhZTYxNzQtYTkxNC00ZWQ2LTg0YzItYjE2Y2JhNTVkMGY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDA4MTA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4ZjFjOWNlMDU3ZWVkNzgxM2E3MzM3YzcxM2NlOGYyZTc3NzI5MzI3MjM4YTMyZDFkOWQ4ZTMzNTUzMWMzM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bK6cyVXfsqn_eIzFOyn8JBg9PDBsQ4gi5HuP_jZM6d4) 但这种情况他是正常翻译的啊.
> > 然后我再那本算法书上.使用"(CM[^RT].|MS.|.*Ital|.MT2)"就导致Ital不翻译了.
> 
> 上面那个$v2是小概率错误，给缓存删掉再翻译一次就好了

确实删除了缓存就好了.  -f 就是不翻译是吗?

**Comment by Byaidu** [comment]
对的

**Comment by noenif** [comment]
> 对的

我知道了,那能不能这样.加一个出版社的字段来控制-f,因为同一个出版社的字体排版差不多.但是也会出现在不同时期比如改革后,字体变换.
需要一个列表或者字典来控制.

pdf读取的时候可以获取,或者让用户自己选择出版社,这个是属于自己维护的一个表.

**Comment by Byaidu** [comment]
啊这，你可以写个py脚本来判断，直接传入参数调用pdf2zh.translate方法就好

**Comment by noenif** [comment]
> 确实删除了缓存就好了. -f 就是不翻译是吗?


> > > 这个确实不太好处理，默认策略是直接跳过斜体的
> > 
> > 
> > 默认跳过吗.我本来有一本书斜体翻译会多出来 ![image](https://private-user-images.githubusercontent.com/25174520/395480318-3190a4bc-6072-45e4-9196-33d08ed5ba49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNzc3NTUsIm5iZiI6MTczNDA3NzQ1NSwicGF0aCI6Ii8yNTE3NDUyMC8zOTU0ODAzMTgtMzE5MGE0YmMtNjA3Mi00NWU0LTkxOTYtMzNkMDhlZDViYTQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDA4MTA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5YzQ3NGUzOTgyOGZkMDAxMTM3MWJiMDI5YzQ0YmFiMTY5NjBlOTM0YjRlNTMwYWQyNmU3Nzc5NGFjMzcwNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QKn4w6vVQITwEZ6vktiPT83RZKaMe82otFVIfXCEhzI) 然后我去设置了"(CM[^RT]._|MS._|.*Ital)",他就正常了翻译. ![image](https://private-user-images.githubusercontent.com/25174520/395481048-99ae6174-a914-4ed6-84c2-b16cba55d0f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNzc3NTUsIm5iZiI6MTczNDA3NzQ1NSwicGF0aCI6Ii8yNTE3NDUyMC8zOTU0ODEwNDgtOTlhZTYxNzQtYTkxNC00ZWQ2LTg0YzItYjE2Y2JhNTVkMGY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDA4MTA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4ZjFjOWNlMDU3ZWVkNzgxM2E3MzM3YzcxM2NlOGYyZTc3NzI5MzI3MjM4YTMyZDFkOWQ4ZTMzNTUzMWMzM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bK6cyVXfsqn_eIzFOyn8JBg9PDBsQ4gi5HuP_jZM6d4) 但这种情况他是正常翻译的啊.
> > 然后我再那本算法书上.使用"(CM[^RT].|MS.|.*Ital|.MT2)"就导致Ital不翻译了.
> 
> 上面那个$v2是小概率错误，给缓存删掉再翻译一次就好了


![image](https://github.com/user-attachments/assets/9d36f022-c7dc-4ad9-9a9a-44fa8aa94e8d)
![image](https://github.com/user-attachments/assets/bfc7d1ca-231f-42a1-94b6-a2f2ba02abf6)

老哥,这个情况其实就是-f 不翻译导致的吗?

这个情况还比较多,今天,我刚才删除了缓存还是不行.还是同一个地方.显示这个问题.大佬能否查看下.
[Cognitive Neuroscience 5th ed The Biology of the Mind_45-54.pdf](https://github.com/user-attachments/files/18125939/Cognitive.Neuroscience.5th.ed.The.Biology.of.the.Mind_45-54.pdf)

**Comment by Byaidu** [comment]
是这样，这个东西是远程翻译服务的问题，你可以换个翻译服务看看

**Comment by noenif** [comment]
> 是这样，这个东西是远程翻译服务的问题，你可以换个翻译服务看看

我用的deepl


> 是这样，这个东西是远程翻译服务的问题，你可以换个翻译服务看看

确实老哥
![image](https://github.com/user-attachments/assets/828717ac-3dc6-4550-80c0-7b90468b9ad9)
这张图我用的openai  是qwen72b

deepl是这张图
![image](https://github.com/user-attachments/assets/1a17664f-f583-4135-847c-e828d5f5714c)


老哥有好点的接口吗?介绍一波.

**Comment by noenif** [comment]
> 是这样，这个东西是远程翻译服务的问题，你可以换个翻译服务看看

确实老哥
![image](https://github.com/user-attachments/assets/828717ac-3dc6-4550-80c0-7b90468b9ad9)
这张图我用的openai  是qwen72b

deepl是这张图
![image](https://github.com/user-attachments/assets/1a17664f-f583-4135-847c-e828d5f5714c)


老哥有好点的接口吗?介绍一波.
