### ISSUE TITLE
下载出现乱码

### ISSUE THREAD

**Issue by xiaosy-astro** [Byaidu/PDFMathTranslate#222]
### 问题描述

随便下载一篇论文翻译成中文，预览页面没有问题：

<img width="614" alt="image" src="https://github.com/user-attachments/assets/e9aca793-dd20-4c49-835e-829bed249b03" />

下载后显示的全是乱码

<img width="596" alt="image" src="https://github.com/user-attachments/assets/222db1b5-d977-4250-a0cb-e3200f05aff2" />

这要如何解决？

**Comment by Byaidu** [comment]
换个标准的pdf阅读器

**Comment by xiaosy-astro** [comment]
换个pdf阅读器就行，已解决，感谢🙏

> 换个标准的pdf阅读器
