### ISSUE TITLE
Add more languages

### ISSUE THREAD

**Issue by Eunice-Wyy** [Byaidu/PDFMathTranslate#223]
## 问题描述
Is there anyway I can add new languages into gui.py? When I run '_pdf2zh -i_', the language map did not change at all.

**Comment by Byaidu** [comment]
you need to install the project using develop mode `pip install -e .`

**Comment by kkpo4553** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the `lang_map` dictionary in `gui.py` to include more languages and made it easier to add new languages in the future. Also updated the `translate_file` function to use the new `lang_map`.

You can review changes in this commit: https://github.com/kkpo4553/Byaidu-PDFMathTranslate-223/commit/55c03ce84479e939be50232b298ebc5374281554.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by Eunice-Wyy** [comment]
@Byaidu I did that and now i have a new error:

AttributeError: 'WindowsPath' object has no attribute 'startswith'

**Comment by hellofinch** [comment]
Do you run in the Windows?
file or link？

**Comment by Eunice-Wyy** [comment]
@hellofinch I run 'pdf2zh -i' which gives me the ui, and proceed to upload the file from the file_input components.

**Comment by hellofinch** [comment]
Oh! I reproduce it.
Please wait to fix it. It will not take long.
: )

**Comment by hellofinch** [comment]
@Eunice-Wyy Here is the solution. You need fix like this before new PR.
In high_level.py: line63-71
```
def check_files(files: List[str]) -> List[str]:
    files = [
        f for f in files if not str(f).startswith("http://")
    ]  # exclude online files, http
    files = [
        f for f in files if not str(f).startswith("https://")
    ]  # exclude online files, https
    missing_files = [file for file in files if not os.path.exists(file)]
    return missing_files
```

`f.startswith("http://")` to `str(f).startswith("http://")`
`f.startswith("https://")` to `str(f).startswith("https://")`
After you fix, restart the GUI.
I will PR ASAP.

**Comment by Eunice-Wyy** [comment]
Yes, it works! Thank you!
