### ISSUE TITLE
如何使yolo模型运行到GPU上

### ISSUE THREAD

**Issue by 1091492188** [Byaidu/PDFMathTranslate#224]
真心请问，因为测试有些论文，要10几分钟，有点慢

**Comment by Byaidu** [comment]
瓶颈在网络上，不是yolo模型

**Comment by 1091492188** [comment]
这个网络是指使用国外翻译API吗，关键我使用的是国内的API

**Comment by 1091492188** [comment]
![image](https://github.com/user-attachments/assets/29e36479-8f13-4bb4-ba2c-b84db6c96bc6)
你可以看看，速度还是比较慢的

**Comment by hellofinch** [comment]
API无论国内国外都会限制单位时间内请求的数量，还有一种可能是这个issue中提到的内容。https://github.com/Byaidu/PDFMathTranslate/issues/216

**Comment by awwaawwa** [comment]
我初步看了一下，CUDA+苹果CoreML是肯定能跑，DirectML onnxruntime有支持，但是还没看pypi上的有没有这个支持。后续有时间后会profile一下看看。我估摸着把各步骤并行起来后就看不见这个瓶颈了。后续有时间的话我应该会改改然后发pr

**Comment by imClumsyPanda** [comment]
https://onnxruntime.ai/docs/execution-providers/CoreML-ExecutionProvider.html#configuration-options-new-api

使用coreML疑似可以参考上述代码，但是不确定如何判断是否使用了coreML与提升效果，因此目前仅在本地尝试过，暂未发起pr

**Comment by awwaawwa** [comment]
> https://onnxruntime.ai/docs/execution-providers/CoreML-ExecutionProvider.html#configuration-options-new-api
> 
> 使用coreML疑似可以参考上述代码，但是不确定如何判断是否使用了coreML与提升效果，因此目前仅在本地尝试过，暂未发起pr

我本地也试过，在 https://github.com/Byaidu/PDFMathTranslate/pull/330 打满 20qps 后，用 CoreML 可以大幅降低 CPU 占用。后续我会将相关代码在这个 PR 里合进去。（and，也会试试 DirectML）
