### ISSUE TITLE
可否使用{v} 来替换$v$

### ISSUE THREAD

**Issue by noenif** [Byaidu/PDFMathTranslate#229]
我测试了openai和deepl是可以的

![image](https://github.com/user-attachments/assets/e9470c97-6c33-404a-b6ea-03d6591a0b4f)
openai 翻译的 这个划线的标题头是因为没有传递数据导致的.

![image](https://github.com/user-attachments/assets/fb178455-0eef-4cb9-9c28-eabdd23ecce9)

![image](https://github.com/user-attachments/assets/70e92ebb-02d0-4250-a3a9-d68a7825082e)

具体其他接口未测试过.详细请大佬评估.

**Comment by Byaidu** [comment]
感谢反馈，已改进 https://github.com/Byaidu/PDFMathTranslate/commit/b63ff573fcec4be3c9f0fc678942b2868eebec63
