### ISSUE TITLE
gemini api 支持

### ISSUE THREAD

**Issue by asukaminato0721** [Byaidu/PDFMathTranslate#230]
## 功能描述
请描述需要添加的功能，以及是否有类似项目可以参考

支持 gemini api, 在 readme 里没提到, <https://ai.google.dev/pricing?hl=zh-cn#1_5flash>

类似项目: <https://github.com/pot-app/pot-desktop/blob/b213fd342049326bdac0989ff8494ab5ed232449/src/services/translate/geminipro/index.jsx#L9>

看上去加在这里就行 <https://github.com/Byaidu/PDFMathTranslate/blob/main/pdf2zh/translator.py>

**Comment by Byaidu** [comment]
感谢反馈，已添加 https://github.com/Byaidu/PDFMathTranslate/commit/3a23b4fbef403ba935aeddbe1519004f8e89100e
