### ISSUE TITLE
重复出现 ERROR : pdf2zh.converter:Expecting value: Line 1 column 1 ( char 0 )

### ISSUE THREAD

**Issue by Tozniz** [Byaidu/PDFMathTranslate#231]
## 问题

进行翻译时 重复出现 ERROR : pdf2zh.converter:Expecting value: Line 1 column 1 ( char 0 )

[YM.pdf](https://github.com/user-attachments/files/18135058/YM.pdf)
![screenshot](https://github.com/user-attachments/assets/8be7d361-55d8-46f4-98fa-65b5daad31c7)

**Comment by Nebulas2002** [comment]
兄弟咋解决的
