### ISSUE TITLE
无法翻译

### ISSUE THREAD

**Issue by Moonquake2021** [Byaidu/PDFMathTranslate#233]
## 问题描述
请对问题进行描述，并提供日志或截图
请确认 issues 中没有相同问题且完整阅读 wiki
**本项目不处理网络环境引发的问题**（例如 empty translation result/connection reset/check_hostname requires server_hostname/certificate verify failed/unable to connect to proxy/LocalEntryNotFoundError）

## 测试文档
> [!IMPORTANT]
> 请提供用于复现测试的 PDF 文档
采用第三种方式安装，命令窗口提示ERROR:pdf2zh.converter:Expecting value: line 1 column 1 (char 0)，请教该问题该怎么解决

**Comment by Byaidu** [comment]
https://github.com/Byaidu/PDFMathTranslate/issues/179
