### ISSUE TITLE
翻译后的 PDF 文本覆盖原文（高质量扫描）

### ISSUE THREAD

**Issue by eliasjudin** [Byaidu/PDFMathTranslate#235]
我尝试使用本项目对一个高质量扫描的 PDF 进行翻译，但翻译结果中的文本覆盖在原文之上，导致无法正常阅读。可能是由于该 PDF 没有文本组件，仅包含扫描的图像。

附上原始 PDF 文件和翻译后的 PDF 文件以供参考。

[original.pdf](https://github.com/user-attachments/files/18139305/original.pdf)

[pdf2zh.pdf](https://github.com/user-attachments/files/18139306/pdf2zh.pdf)

```
pdf2zh original.pdf -li ru -lo en -p
 2 -f "(CM[^R]|(MS|XY|MT|BL|RM|EU|LA|RS)[A-Z]|LINE|LCIRCLE|TeX-|rsfs|
txsy|wasy|stmary|.*Mono|.*Code|.*Ital|.*Sym|.*Math)"
```

**Comment by Byaidu** [comment]
https://github.com/Byaidu/PDFMathTranslate/issues/19

**Comment by hellofinch** [comment]
scanned file not support well. https://github.com/Byaidu/PDFMathTranslate/issues/19

**Comment by eliasjudin** [comment]
> scanned file not support well. https://github.com/Byaidu/PDFMathTranslate/issues/19

so the file requires a text layer? if i ocr to add the text layer will it work?

**Comment by hellofinch** [comment]
I'm not sure. The texts were extracted from PDF, not from the picture.
