### ISSUE TITLE
翻译文件出问题 ERROR:pdf2zh.converter:0

### ISSUE THREAD

**Issue by hziheng** [Byaidu/PDFMathTranslate#236]
## 问题描述
1. 用goole翻译没问题，但是用bing翻译直接error：
日志显示
ERROR:pdf2zh.converter:0

2. 如果用bing翻译，一直在error，此时无法打断或者阻止程序中断，刷新网页后，重新调用google翻译，也会卡住，因为程序内部还在报错ERROR:pdf2zh.converter:0这个问题

**Comment by Byaidu** [comment]
https://github.com/Byaidu/PDFMathTranslate/issues/134
