### ISSUE TITLE
Implement/add the Brazilian Portuguese (PT-BR) language.

### ISSUE THREAD

**Issue by felipedantas-pi** [Byaidu/PDFMathTranslate#237]
## Suggestion
I would like to know if it is possible to implement/add the Brazilian Portuguese (PT-BR) language?

**Comment by Byaidu** [comment]
https://github.com/Byaidu/PDFMathTranslate?tab=readme-ov-file#specify-source-and-target-languages

Use the option `-lo pt-BR`
