### ISSUE TITLE
命令行安装后无法使用

### ISSUE THREAD

**Issue by Yu-kio** [Byaidu/PDFMathTranslate#238]
您好 请问通过pip安装后，在命令行直接键入pdf2zh  -i 无法使用，已确认加入环境变量，
小白求助

 from cryptography.hazmat.bindings._rust import openssl as rust_openssl
ImportError: DLL load failed while importing _rust: 找不到指定的程序。

**Comment by Byaidu** [comment]
可以开个新的python环境重装，或者换个使用方法
