### ISSUE TITLE
后期是否会支持"图片类PDF"进行翻译

### ISSUE THREAD

**Issue by adddp** [Byaidu/PDFMathTranslate#239]
## 功能描述
请描述需要添加的功能，以及是否有类似项目可以参考
现在PDF里是图片的话 是无法进行翻译的，我看到有很多PDF强制ORC文字的py插件，后期是否会利用这类插件 间接的支持图片类PDF？

**Comment by hellofinch** [comment]
https://github.com/Byaidu/PDFMathTranslate/issues/19
会有，`help wanted`
