### ISSUE TITLE
在Docker镜像构建时预下载HF模型

### ISSUE THREAD

**Issue by awwaawwa** [Byaidu/PDFMathTranslate#247]
## 功能描述
请描述需要添加的功能，以及是否有类似项目可以参考

在Docker镜像构建时预下载HF模型，解决 https://github.com/Byaidu/PDFMathTranslate/issues/184 这种问题。比如说 [gpt_academic](https://github.com/binary-husky/gpt_academic/blob/98e5cb7b7750b89025103d0c5865f29d6457b83a/docs/GithubAction%2BNoLocal%2BLatex#L30C1-L32C1) 就做了这个处理。

- [x] 优化docker构建
- [ ] 利用 [github-cache](https://docs.docker.com/build/ci/github-actions/cache/#github-cache)
- [x] 输出个log

**Comment by reycn** [comment]
我记得群里有一位朋友自己实现了一下，但他没有提交 PR

**Comment by awwaawwa** [comment]
https://github.com/Byaidu/PDFMathTranslate/pull/276

**Comment by reycn** [comment]
The feature has been implemented by @awwaawwa in [PR#276](https://github.com/Byaidu/PDFMathTranslate/pull/276). Thanks!!!
