### ISSUE TITLE
ollama 出现ERROR

### ISSUE THREAD

**Issue by ying06** [Byaidu/PDFMathTranslate#25]
不使用ollama选项时，转换正常，效果很好。
![ollama_error](https://github.com/user-attachments/assets/9287cc81-5379-4f19-b483-65fa714c9d27)
使用ollama 选项时，出现这个错误，且运行一直继续。
ollama version 是0.4，操作系统是win 11，使用模型是gemma2，pull下来的，对话正常。
[
![ollama_version](https://github.com/user-attachments/assets/cdfe4247-4a15-4fd5-86d5-935fc1207333)
](url)

**Comment by Byaidu** [comment]
应该是 ollama 0.4 版本有 bug，建议降级到 0.3 看看

**Comment by ying06** [comment]
> 应该是 ollama 0.4 版本有 bug，建议降级到 0.3 看看

请问在哪里设置ollama的HOST和PORT呢？有时需要远程连接ollama。

**Comment by Byaidu** [comment]
参考 https://github.com/ollama/ollama-python 改一下 [translator.py](https://github.com/Byaidu/PDFMathTranslate/blob/main/pdf2zh/translator.py#L114)

**Comment by wenbopeng** [comment]
> > 参考 https://github.com/ollama/ollama-python 改一下 [translator.py](https://github.com/Byaidu/PDFMathTranslate/blob/main/pdf2zh/translator.py#L114)
> 
> thanks，非常有用。

请问大佬如何设置呀

**Comment by wenbopeng** [comment]
我也是 `RROR:pdf2zh.converter:`
