### ISSUE TITLE
前端“取消翻译”按钮/详细进度显示

### ISSUE THREAD

**Issue by timelic** [Byaidu/PDFMathTranslate#250]
前端页面中没有取消按钮进程，也没有任何刷新按钮，在等待时候没法知道到底是出了什么问题。可能等待五分钟之后发现是网络卡了或者后端报错，而前端没有显示。

想要更详细的进度显示，如“扫描中”/“翻译中”/“生成文件中”。而非只是一个囊括一切的纯数字进度条。

**Comment by hellofinch** [comment]
https://github.com/Byaidu/PDFMathTranslate/pull/240
接下来的版本中会有哦，请期待。
: )

**Comment by awwaawwa** [comment]
我后面搓 https://github.com/Byaidu/PDFMathTranslate/issues/216#issuecomment-2543347690 的时候考虑一下详细进度追踪

**Comment by awwaawwa** [comment]
不知道为啥，现版的取消我没法用

**Comment by reycn** [comment]
The feature has been implemented by @hellofinch in [PR#240](https://github.com/Byaidu/PDFMathTranslate/pull/240).

Thanks!!
