### ISSUE TITLE
theme.css, style.css和index.js三个文件的url无法被反代修改端口

### ISSUE THREAD

**Issue by f1ynng8** [Byaidu/PDFMathTranslate#256]
## 问题描述
请对问题进行描述，并提供日志或截图
请确认 issues 中没有相同问题且完整阅读 wiki
**本项目不处理网络环境引发的问题**（例如 empty translation result/connection reset/check_hostname requires server_hostname/certificate verify failed/unable to connect to proxy/LocalEntryNotFoundError）

通过nginx反代https后如果不是默认端口，某些文件无法获得，这些文件似乎是被固定了host端口。
大部分文件例如下面这文件是可以正确被反代url及端口从而正常访问的：
![image](https://github.com/user-attachments/assets/c6d9be4b-44bd-443e-b5cd-d901beb26eb5)
但是下面三个文件都被固定了端口而无法通过反代来指定端口：
![image](https://github.com/user-attachments/assets/c7fbc75b-a3b5-444b-b351-875158b1f156)
![image](https://github.com/user-attachments/assets/4ebc4f12-2a14-4d17-85f7-cc1b0c44144c)

## 测试文档
> [!IMPORTANT]
> 请提供用于复现测试的 PDF 文档

**Comment by Byaidu** [comment]
尝试下设置 proxy_set_header X-Forwarded-Port

**Comment by f1ynng8** [comment]
> 尝试下设置 proxy_set_header X-Forwarded-Port

感谢，我检查了确实已经设置了proxy_set_header X-Forwarded-Port，而且除了这三个文件外，其它所有文件都正常转发。
```
location / {
 add_header       X-Served-By $host;
 proxy_set_header Host $host;
 proxy_set_header X-Forwarded-Scheme $scheme;
 proxy_set_header X-Forwarded-Proto  $scheme;
 proxy_set_header X-Forwarded-Port $server_port;
 proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
 proxy_set_header X-Real-IP          $remote_addr;
 proxy_pass       $forward_scheme://$server:$port$request_uri;
}
```

另外从生成的前端文件来看，似乎是源代码里固定了。
<img width="1353" alt="image" src="https://github.com/user-attachments/assets/be849eee-1f09-41a2-b3d1-cef9cfb0fbdc" />

**Comment by Byaidu** [comment]
这里你可能需要到gradio项目下反馈了

**Comment by f1ynng8** [comment]
感谢，我去看一下。

**Comment by f1ynng8** [comment]
找到解决方法了，其它人如果遇到反代的问题可以参考gradio的解决方案：
https://www.gradio.app/guides/running-gradio-on-your-web-server-with-nginx

> Note: The $host variable does not include the host port. If you are serving your Gradio application on a raw IP address and port, you should use the $http_host variable instead, in these lines:

```
proxy_set_header Host $http_host;
proxy_set_header X-Forwarded-Host $http_host;
```

**Comment by brucemomo** [comment]
内网nas，Nginx-Proxy-Manager反代设置，供参考：

location / {
    proxy_pass http://127.0.0.1:7860/;  # Gradio应用的本地地址和端口
    proxy_buffering off;
    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
}

**Comment by Maincine** [comment]
route_utils.py  改下root_url = root_url.replace("http://", "https//")  
注释掉 
if get first header value(request,"x-forwarded-proto" "https":

**Comment by f1ynng8** [comment]
另一个解决方案是不要用nginx做https反代，直接用caddy。
