### ISSUE TITLE
使用命令 pdf2zh -i 的命令，提示ModuleNotFoundError: No module named 'pymupdf'

### ISSUE THREAD

**Issue by PadricZ** [Byaidu/PDFMathTranslate#259]
## 问题描述
1.MacOS 15.2,Python环境为3.11，使用pip3 install pdf2zh安装软件
2.安装成功后，使用pdf2zh -i命令启动gui工具
3.提示ModuleNotFoundError: No module named 'pymupdf'
4.
<img width="927" alt="image" src="https://github.com/user-attachments/assets/67004753-4115-42db-a01d-013a33cdc56c" />

## 测试文档
> [!IMPORTANT]
> 请提供用于复现测试的 PDF 文档

**Comment by Byaidu** [comment]
pip install -U pymupdf

**Comment by PadricZ** [comment]
> pip install -U pymupdf
非常感谢，可以使用了
