### ISSUE TITLE
翻译的时候存在未翻译的情况，BaseTranslator基类建议增加批量翻译

### ISSUE THREAD

**Issue by Williamsunsir** [Byaidu/PDFMathTranslate#26]
# 翻译的时候存在未翻译的情况，BaseTranslator基类建议增加批量翻译
# 测试版本：V1.6.9
# 示例全文下载地址：https://elifesciences.org/articles/45779#downloads

## 文本未翻译
![image](https://github.com/user-attachments/assets/f25c29c2-4ef4-470c-a085-e543c3b2d799)
![image](https://github.com/user-attachments/assets/e91e76e9-aa6d-4a1e-a72c-5c7cfc64c65c)

## BaseTranslator基类建议增加批量翻译
现在绝大多数的翻译引擎已经支持批量翻译的功能了，单次可以翻译整页，比如deepl
![image](https://github.com/user-attachments/assets/aa77551c-02af-494c-af54-475b01ecb203)

**Comment by Byaidu** [comment]
文本未翻译的原因是那个“Abstract”的字体是12号，但是后面正文字体是9号，所以被当成角标处理了……暂时没想到简单的识别办法

deepl 愿意的话可以加个 PR，主要是我不经常用这个

**Comment by Byaidu** [comment]
还有一种类似的情况，有些阴间书喜欢放大章节的第一个段落的首字母，导致整个段落炸掉

**Comment by reycn** [comment]
暂时关闭 Issue 因为我们已经单独作为 feature issue 等待开源帮助实现 （https://github.com/Byaidu/PDFMathTranslate/issues/81），并解决了第二个问题（https://github.com/Byaidu/PDFMathTranslate/issues/86）。
