### ISSUE TITLE
允许用户自定义prompt

### ISSUE THREAD

**Issue by timelic** [Byaidu/PDFMathTranslate#260]
- 默认翻译prompt有可能导致翻译为繁体中文。
- 部分内容（人名、论文引用）其实应该保留原文。
- 希望允许用户自定义不同翻译源的Prompt。

**Comment by timelic** [comment]
<img width="752" alt="截屏2024-12-17 20 59 07" src="https://github.com/user-attachments/assets/04437206-49fe-48d7-b29a-2f32dc5630db" />

<img width="840" alt="截屏2024-12-17 20 59 23" src="https://github.com/user-attachments/assets/85709620-c50c-4eb5-a508-1fa711a653c0" />

**Comment by reycn** [comment]
The feature has been implemented in [PR#275](https://github.com/Byaidu/PDFMathTranslate/pull/275)
