### ISSUE TITLE
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on

### ISSUE THREAD

**Issue by lizhichao999** [Byaidu/PDFMathTranslate#263]
## 问题描述
请对问题进行描述，并提供日志或截图
pdf2zh -i 启动报错，提示没网，离线下载模型哪有地址
## 测试文档
> [!IMPORTANT]
> 请提供用于复现测试的 PDF 文档
![企业微信截图_17344828995499](https://github.com/user-attachments/assets/64fea683-c2ad-4a62-8e9a-aa52c12bd141)
![企业微信截图_17344829247467](https://github.com/user-attachments/assets/925bd1ca-e04d-410e-aa4c-328bffea78b6)

**Comment by lizhichao999** [comment]
![企业微信截图_17344838879528](https://github.com/user-attachments/assets/5454ea07-418e-4f04-a17c-afb02d81a382)
已下载模型到这个目录，还是会连接requests.exceptions.ConnectTimeout: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /wybxc/DocLayout-YOLO-DocStructBench-onnx/resolve/main/doclayout_yolo_docstructbench_imgsz1024.onnx (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000209F8B9F050>, 'Connection to huggingface.co timed out. (connect timeout=1)'))"), '(Request ID: 2292093f-32a1-4991-94d8-1c1ba8c3e7c8)')

**Comment by hellofinch** [comment]
执行`pdf2zh -i`之前，运行一下这个`set HF_ENDPOINT=https://hf-mirror.com`
https://github.com/Byaidu/PDFMathTranslate/issues/134
