### ISSUE TITLE
扫描件检测&输出警告

### ISSUE THREAD

**Issue by awwaawwa** [Byaidu/PDFMathTranslate#264]
既然目前处理扫描件存在许多技术难题，那搞个检测&输出个暂时无法处理的提示？

**Comment by hellofinch** [comment]
其实应该是可以弄的，现在的模型可以提取出不同类型文本的位置，然后ocr也是可以复用这个框的。
我之前没搞定的地方在于怎么生成一个新的pdf页。

**Comment by awwaawwa** [comment]
这样啊

**Comment by hellofinch** [comment]
OCR我之前甩了一段在那个help wanted issue里，可以直接拿去用。
现在的这个pdf的解析我没看明白怎么做的，但是注意一下box的框框和ocr用的框框不太一样。box的框框我记得会小一些，不能用box的框框给ocr，会出错。

**Comment by reycn** [comment]
合并讨论至 [Issue#19](https://github.com/Byaidu/PDFMathTranslate/issues/19)
