### ISSUE TITLE
(Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000200612F9510>, 'Connection to translate.google.com timed out. (connect timeout=None)')

### ISSUE THREAD

**Issue by lizhichao999** [Byaidu/PDFMathTranslate#265]
## 问题描述
请对问题进行描述，并提供日志或截图
C:\Users\Administrator>d:

D:\lizc\pdf>set USE_MODELSCOPE=1 pdf2zh

D:\lizc\pdf>pdf2zh test.pdf
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]ERROR:pdf2zh.converter:HTTPConnectionPool(host='translate.google.com', port=80): Max retries exceeded with url: /m?tl=zh-CN&sl=en&q=The+Cranford+ladies+have+only+an+occasional+little+quarrel%2C+spirited+out+in+a+few+peppery++words+and+angry+jerks+of+the+head%3B+just+enough+to+prevent+the+even+tenor+of+their+lives+from++becoming+too+flat.+Their+dress+is+very+independent+of+fashion%3B+as+they+observe%2C+%E2%80%9CWhat+does++it+signify+how+we+dress+here+at+Cranford%2C+where+everybody+knows+us%3F%E2%80%9D+And+if+they+go+from++home%2C+their+reason+is+equally+cogent%2C+%E2%80%9CWhat+does+it+signify+how+we+dress+here%2C+where+nobody++knows+us%3F%E2%80%9D+The+materials+of+their+clothes+are%2C+in+general%2C+good+and+plain%2C+and+most+of+them++are+nearly+as+scrupulous+as+Miss+Tyler%2C+of+cleanly+memory%3B+but+I+will+answer+for+it%2C+the+last++gigot%2C+the+last+tight+and+scanty+petticoat+in+wear+in+England%2C+was+seen+in+Cranford%E2%80%94and++seen+without+a+smile. (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000200612E3310>, 'Connection to translate.google.com timed out. (connect timeout=None)'))已经下载到本地的模型，还是要请求远程吗

**Comment by hellofinch** [comment]
pypi包还没更新应该，请稍等下一个版本。
: )

**Comment by hellofinch** [comment]
而且这个问题是google连接不到，不是模型的问题。

**Comment by Byaidu** [comment]
https://github.com/Byaidu/PDFMathTranslate/issues/134

**Comment by iBQ-github** [comment]
我的问题跟你一样，不太明白#134的解决办法，我的chrome能正常访问google所有网站（GHpler ON），1.8.8版本使用正常，升级到1.9.0就报错了

**Comment by hellofinch** [comment]
可是是最近政策影响到了谷歌的翻译服务？境内不能直连了？
