### ISSUE TITLE
Docker 网页是否可以支持自定义 翻译页面范围

### ISSUE THREAD

**Issue by akoura123** [Byaidu/PDFMathTranslate#267]
## 功能描述
目前docker网页只提供 All , First , First 5 pages 三个选项，是否可以支持自定义输入 [start, end] 指定页面范围的翻译，这对排除一些不需要的内容很有用（比如paper末尾的引用列表等等）

**Comment by reycn** [comment]
The feature has been implemented by @hellofinch in [PR](https://github.com/Byaidu/PDFMathTranslate/pull/275).

Thank you so much.
