### ISSUE TITLE
Ubuntu 22.04 下载的pdf中文显示异常

### ISSUE THREAD

**Issue by Rui-li023** [Byaidu/PDFMathTranslate#272]
您好，

首先，我想对这个项目表示感谢。它非常有用。

但是在Ubuntu 22.04环境下使用的过程中遇到了一个问题：

1. 创建了虚拟环境并通过pip安装了必要的包。
2. 使用sudo命令运行web服务。
3. 利用ollama进行翻译，在预览中显示正常且翻译成功。

然而，下载PDF文件后，所有的中文字符都丢失了。

预览结果：

![image](https://github.com/user-attachments/assets/d40effb2-ede0-487a-9666-e8ad729a4dbc)

下载后文档结果：

![image](https://github.com/user-attachments/assets/5be97041-0f63-406f-82f9-16e5ce3d4fc6)

能否请解决这个问题？我认为这可能是由于PDF生成过程中字体嵌入或编码设置的问题，但我不确定。非常感谢您的帮助！

感谢您花时间处理此事。

**Comment by hellofinch** [comment]
试试别的PDF阅读器和系统看看，可能是显示的问题

**Comment by Rui-li023** [comment]
> 试试别的PDF阅读器和系统看看，可能是显示的问题

好像是这样的，使用Firefox可以打开，但是使用edge会出现上面的显示问题

**Comment by Byaidu** [comment]
> > 试试别的PDF阅读器和系统看看，可能是显示的问题
> 
> 好像是这样的，使用Firefox可以打开，但是使用edge会出现上面的显示问题

可以更新一下 edge 的版本看看

**Comment by reycn** [comment]
As all comments are showing that the issue was not introduced by our program, closed. THank you for raising it!
