### ISSUE TITLE
https://pdf2zh.com中的gradio-pdf是修改过的版本吗

### ISSUE THREAD

**Issue by myhloli** [Byaidu/PDFMathTranslate#274]
看到网站里gradio-pdf是关闭上传按钮和上传功能的，看了下pdf2zh/gui.py 没找到相关的代码
问下这个是使用了修改过的版本吗？

**Comment by myhloli** [comment]
> 不是哦，只是把interactive关了而已。目前只是用了preview的功能，别的功能没有用到。 : ) [freddyaboulton/gradio-pdf#31](https://github.com/freddyaboulton/gradio-pdf/issues/31)

好吧，0.20才修。。我说之前关了也没反应。。。谢谢了

**Comment by hellofinch** [comment]
目前现在cmap获取在中国大陆还有问题，得挂代理。我反馈了，不知道什么时候修。

**Comment by myhloli** [comment]
> 目前现在cmap获取在中国大陆还有问题，得挂代理。我反馈了，不知道什么时候修。

还有个https://cdn.jsdelivr.net/gh/freddyaboulton/gradio-pdf@main/pdf.worker.min.mjs 在大陆访问也是断断续续的被墙，我试了下改成https://gcore.jsdelivr.net/gh/freddyaboulton/gradio-pdf@main/pdf.worker.min.mjs 就好了😂，加上之前关不掉上传按钮的问题，我本来想自己mod下，结果发现这个还不是直接直接setup就能打包的。。

**Comment by hellofinch** [comment]
😂是的，我当时也想自己改后来一看文档，我选择求救。
