### ISSUE TITLE
修改GitHub Action相关文件，方便fork仓库启用docker publish Action

### ISSUE THREAD

**Issue by awwaawwa** [Byaidu/PDFMathTranslate#278]
当前的docker-publish.yml中IMAGE_NAME，REGISTRY等都是写死的，fork的仓库其实不太方便用这个action。

**Comment by reycn** [comment]
当 fork 用户需要发布自定义镜像的时候，修改文件可以达到同样目的？

**Comment by Byaidu** [comment]
fork大概不会有用action上传的需求吧（

**Comment by reycn** [comment]
Agree. Issue closed for now and reopen if it needs further discussion. Thanks anyway!
