### ISSUE TITLE
使用 GitHub Action 自动格式化代码

### ISSUE THREAD

**Issue by awwaawwa** [Byaidu/PDFMathTranslate#279]
使用 GitHub Action 自动格式化代码

**Comment by awwaawwa** [comment]
docs: https://black.readthedocs.io/en/stable/integrations/github_actions.html

**Comment by reycn** [comment]
Implemented in [CMT#a4f0415ab3cac7a4abe72cd54d647585d2071dfa](https://github.com/Byaidu/PDFMathTranslate/commit/a4f0415ab3cac7a4abe72cd54d647585d2071dfa). Thanks!!

**Comment by Jensonss** [comment]
你好请问你这个代码格式化怎么使用？
