### ISSUE TITLE
非标准PDF会导致翻译失效

### ISSUE THREAD

**Issue by whyOnism001** [Byaidu/PDFMathTranslate#280]
## 问题描述
非标准的扫描件和Word转PDF的文件翻译会无法识别，并且对于艺术字/手写体无法翻译

## 测试文档
> 非标
[13.pdf](https://github.com/user-attachments/files/18183535/13.pdf)

> 请提供用于复现测试的 PDF 文档

**Comment by Byaidu** [comment]
https://github.com/Byaidu/PDFMathTranslate/issues/19

暂时不支持扫描档，后续会有ocr实现
