### ISSUE TITLE
我在hellogithub上成功推荐了作者的项目

### ISSUE THREAD

**Issue by kashima19960** [Byaidu/PDFMathTranslate#281]
## 说明
我在hellogithub上推荐了作者的项目
![image](https://github.com/user-attachments/assets/bba2dd80-0240-4c5c-a091-4a76f02c10d4)
现在已经成功在[hellogithub首页](https://hellogithub.com/repository/8ec2cfd3ef744762bf531232fa32bc47)了,作者可以去认领一下，增加这个项目的曝光度哦😊
![image](https://github.com/user-attachments/assets/088df74a-0cfc-4b9c-a79a-79c663a30ee6)

**Comment by reycn** [comment]
Thank you!

**Comment by Byaidu** [comment]
感谢支持
