### ISSUE TITLE
翻译出来还是英文

### ISSUE THREAD

**Issue by yshi100** [Byaidu/PDFMathTranslate#296]
## 问题描述
翻译出来还是英文

## 测试文档

[Deployment from Scratch (Josef Strzibny) (Z-Library).pdf](https://github.com/user-attachments/files/18193692/Deployment.from.Scratch.Josef.Strzibny.Z-Library.pdf)

**Comment by charles7668** [comment]
pdf 上的文字跟图片不合

![圖片](https://github.com/user-attachments/assets/db86a948-3ee7-4aef-afc0-8931be62954b)

![圖片](https://github.com/user-attachments/assets/06e45c16-3bf9-43af-96ff-5fec4b50ba4a)

**Comment by reycn** [comment]
The issue has been closed & merged into the OCR issue: https://github.com/Byaidu/PDFMathTranslate/issues/19
