### ISSUE TITLE
请求帮助：尝试修改默认中文字体会导致乱码

### ISSUE THREAD

**Issue by timelic** [Byaidu/PDFMathTranslate#299]
尝试加入一个思源宋体：

```
# high_level.py

# 加载自定义字体文件
font_path = "./SourceHanSerifCN-Medium.ttf"
font_name = "source_han_serif_sc_medium"

resfont_map = {
    "zh-cn": font_name,
    "zh-hans": font_name,
    "zh": font_name,
    ...
}

def translate_stream(
...
):
    font_list = [("tiro", None)]
    noto = None
    if lang_out.lower() in resfont_map:  # CJK
        resfont = resfont_map[lang_out.lower()]
        ttf_path = None
        if resfont == font_name:
            ttf_path = font_path
        font_list.append((resfont, ttf_path))

```

可以看到字体成功嵌入了，但是出现了乱码：

<img width="606" alt="截屏2024-12-20 11 20 14" src="https://github.com/user-attachments/assets/7eb3df35-b6be-494d-85e8-6c1dff8eca6d" />

我的字体文件：https://github.com/adobe-fonts/source-han-serif/releases

**Comment by Byaidu** [comment]
你需要用noto那侧来加载外部字体

**Comment by timelic** [comment]
> 你需要用noto那侧来加载外部字体

不是完全明白这个意思：

```py
    elif lang_out.lower() in noto_list:  # noto
        resfont = "noto"
        # docker
        # ttf_path = "/app/GoNotoKurrent-Regular.ttf"
        ttf_path = font_path
        if not os.path.exists(ttf_path):
            ttf_path = os.path.join(tempfile.gettempdir(), "GoNotoKurrent-Regular.ttf")
        if not os.path.exists(ttf_path):
            print("Downloading Noto font...")
            urllib.request.urlretrieve(
                "https://github.com/satbyy/go-noto-universal/releases/download/v7.0/GoNotoKurrent-Regular.ttf",
                ttf_path,
            )
        font_list.append(("noto", ttf_path))
        noto = Font("noto", ttf_path)
```

但是noto这边不是对应了非中文的语言吗，于是用noto来覆盖

**Comment by Byaidu** [comment]
嗯是这样的，他这个PDF内部编码有两个规则，一个是china-ss这种内部字体，另一个是xx.ttf这种外部字体（支持包括中文的所有编码）

你需要用第二种方案来加载，也就是直接把noto文件替换成自己的，再让所有语言统一走noto编码

**Comment by timelic** [comment]
@Byaidu 这确实有效，非常感谢！

不过这引入了一个新的问题，就是PDF文件变大。

pymupdf官网上有[page.subset_fonts](https://pymupdf.readthedocs.io/en/latest/document.html#Document.subset_fonts)方法，但是似乎不起效。

**Comment by timelic** [comment]
> 变大这个细节就不要在意了，能用就行（

确实如此！

你们会有计划使用内嵌的中文字体吗？或者是做成一个可选项。因为现在PDF在Mac和Linux上阅读都变成了默认的黑体。

**Comment by Byaidu** [comment]
可以的，现在默认使用的china-ss这种，主要是考虑空间因素，但确实有很多问题（比如渲染效果不统一或者直接变成空白）

如果将嵌入外部字体作为可选项加入当然是可以的

**Comment by timelic** [comment]
挺好的！很希望会有官方的支持，因为确实影响阅读效果。

**Comment by Byaidu** [comment]
可以考虑加完发个pr，因为我们再单独实现一遍有点重复工作了（

**Comment by timelic** [comment]
> 可以考虑加完发个pr，因为我们再单独实现一遍有点重复工作了（

感觉还是更熟悉代码的人来做吧，我只是很粗暴地修改了字体。如果想做成通用功能还是要仔细想想的，包括文件大小、是否只应用于简中、会不会造成新的显示问题。

**Comment by timelic** [comment]
字符子集化失败的原因是PyMuPDF的bug，已提交issue，待反馈

https://github.com/pymupdf/PyMuPDF/issues/4173
