### ISSUE TITLE
流程图打乱，引用文献重叠

### ISSUE THREAD

**Issue by Williamsunsir** [Byaidu/PDFMathTranslate#3]
原文地址：https://onlinelibrary.wiley.com/doi/pdf/10.1155/2022/5860364

## 流程图问题
![image](https://github.com/user-attachments/assets/d5dd37be-9611-436b-9aca-eca82203c34c)
![image](https://github.com/user-attachments/assets/6539e573-7eaa-436b-b50f-7d45a67d800a)

## 超出问题
![image](https://github.com/user-attachments/assets/55fe85ab-642f-4636-9974-f075a10ac50f)
![image](https://github.com/user-attachments/assets/d2e0ad57-202d-40f9-b5df-cbc59bfd4de3)

## 重叠问题
![image](https://github.com/user-attachments/assets/94d2ef69-ab24-4a36-96cf-7f2131fd47aa)
![image](https://github.com/user-attachments/assets/aecc3646-5318-4262-858b-0b3ef4bd1c55)

## 优化建议
1. 可以增加微软网页翻译API，可以批量进行翻译，就是翻译效果差点

**Comment by Byaidu** [comment]
感谢反馈，超出边界和重叠问题刚才修复了

但是流程图修起来有点麻烦，因为不是很容易区分公式线条和图形线条，可能过段时间才会解决

**Comment by Williamsunsir** [comment]
好的，谢谢

我在测试小语种的过程中发现重叠的情况还是蛮多的，下方是附件
[349f6b423d9b26df.pdf](https://github.com/user-attachments/files/17390840/349f6b423d9b26df.pdf)

并且在翻译的过程中我建议可以考虑批量翻译的情况，比如微软，deelp 都是可以支持多文本输入并且一次性翻译，减少请求次数，提高翻译的效率，如果需要key我可以免费提供

**Comment by Byaidu** [comment]
小语种可以调一下 -c 翻译选项，要不然非 ascii 会被当成公式跳过

```bash
pdf2zh 349f6b423d9b26df.pdf -li auto -c "#"
```

不过工具的主要目标还是翻译英文文献，所以小语种效果烂一点也没关系吧（x

找了一圈没找到好用的多后端翻译库，如果愿意的话可以发个 pr 来加上翻译服务选项

**Comment by Williamsunsir** [comment]
好的，没有弄过pr，有一个deelp 的api key可以提供

**Comment by Byaidu** [comment]
把 key 放上来分分钟就被薅烂，而且那个额度翻一本书都不太够（

之前在看本地的翻译服务，不过 ollama 的效果好像不太好，所以就还没用上

**Comment by Williamsunsir** [comment]
10亿字符，提供你用来做测试，所以不会做公开，如果需要，最好是可以私发你

**Comment by Byaidu** [comment]
嗯嗯那我试试，发我资料页邮箱就可以

**Comment by Byaidu** [comment]
![image](https://github.com/user-attachments/assets/01f0be79-19c4-4a0d-9440-41d7ce71ba9b)

发现了一个很简单的解法，现在图表的问题也修好了

**Comment by Williamsunsir** [comment]
nice，能说一下你的思路吗

**Comment by Byaidu** [comment]
图表里一般是多个线条组合在一起，比如一连串 l 指令再接 S 指令结束，但是公式线条都是独立的，只有一条 l 指令接 S 指令结束

所以我们可以在 S 指令结束的时候判断一下绘图栈里是不是只有一条水平的黑色线段就可以了

**Comment by Williamsunsir** [comment]
谢谢
