### ISSUE TITLE
小bug，如果书本名字如果包含空格会报错。

### ISSUE THREAD

**Issue by luchenwei9266** [Byaidu/PDFMathTranslate#30]
![image](https://github.com/user-attachments/assets/3b0088a1-66be-46c3-a25c-dd07dee43424)

系统：Windows 10 64位
Python：3.10.11

改成不带空格的就名字救没事了

**Comment by Byaidu** [comment]
命令行传参需要引号 pdf2zh "LLM Engineers Handbook.pdf"
