### ISSUE TITLE
如何导入本地的DocLayout-YOLO-DocStructBench-onnx模型而不通过huggingface导入

### ISSUE THREAD

**Issue by 15692280859** [Byaidu/PDFMathTranslate#300]
由于在内网测试，我从huggingface中下载了DocLayout-YOLO-DocStructBench-onnx模型，他应该放入哪个路径让程序可以直接读取本地模型，而不通过网络从huggingface中下载？

**Comment by 15692280859** [comment]
> 什么方式使用？docker还是pip安装？

pip安装

**Comment by hellofinch** [comment]
linux下的话保存的位置在~/.cache/huggingface
你在有网络的地方下载然后放在这个路径下就行

**Comment by 15692280859** [comment]
是否支持windows系统呢，我尝试将doclayout-yolo-docStructbench_imgsz1024.onnx放入~/.cache/huggingface 以及~/.cache/huggingface/hub都会从huggingface中请求下载

**Comment by hellofinch** [comment]
哦，文件结构不对。
![image](https://github.com/user-attachments/assets/00955fe4-331f-4290-ac6a-9ac3702b6dd2)

**Comment by awwaawwa** [comment]
可以试试在一台有公网的电脑上从 HF 加载模型，然后将 ~/.cache/huggingface 目录打包并复制到内网机器上

**Comment by awwaawwa** [comment]
注意到 [doclayout.py](https://github.com/Byaidu/PDFMathTranslate/blob/66d6b80f7818328d338c5fbd2789a5bc5d556296/pdf2zh/doclayout.py#L85C1-L86C30) 中写到：
```python
            pth = hf_hub_download(repo_id=repo_id, filename=filename, etag_timeout=1)
        return OnnxModel(pth)
```

其中，`pth` 是 onnx 文件 路径。或许也可以尝试本地修改此代码，直接返回 `OnnxModel(path)` 来解决问题。

建议后续给cli添加一个参数，允许手动指定 onnx 模型路径。（如果没有有缘人愿意写得话，我有空了可以写）
