### ISSUE TITLE
部分行内公式翻译后乱码

### ISSUE THREAD

**Issue by starxjys** [Byaidu/PDFMathTranslate#303]
### 问题1

**行间公式翻译问题**

部分问题图片

> 原文档

![image](https://github.com/user-attachments/assets/549f6129-ca51-4959-b99c-8b1d7895a0f0)

> 翻译后（官网google翻译）

![image](https://github.com/user-attachments/assets/def88d35-8034-4693-94d0-f4c64c060100)

### 问题2

**翻译后部分页面无法使用Adobe Acrobat Pro读取**，其他应用正常

![image](https://github.com/user-attachments/assets/9cd324ba-ee55-4520-b3a8-d075c9041fe1)

## 测试文档
> [!IMPORTANT]
> [测试文档1.pdf](https://github.com/user-attachments/files/18207515/1.pdf)
> [测试文档2.pdf](https://github.com/user-attachments/files/18207522/2.pdf)

我把页面单独摘出来两页

**Comment by starxjys** [comment]
研究了一下，好像mineru的识别就有问题(v0.8.1)，用最新版提取markdown就识别正确了。也许与这个有关

**Comment by Byaidu** [comment]
字体被混淆过了，这个暂时没法处理
