### ISSUE TITLE
所有的 Arxiv 论文的水印都会错位

### ISSUE THREAD

**Issue by timelic** [Byaidu/PDFMathTranslate#306]
## 问题描述

Arxiv会在每一份PDF的首页的侧边添加水印，这个水印是竖着的。但是进行翻译会导致它被强行翻译从而出问题。

<img width="548" alt="截屏2024-12-20 20 42 42" src="https://github.com/user-attachments/assets/d5507478-b589-465c-af4b-8266867640e0" />

## 测试文档
> [!IMPORTANT]
> 请提供用于复现测试的 PDF 文档

[Informer, Beyond Efficient Transformer for Long Sequence Time-Series Forecasting, Haoyi Zhou et al., 2020, v3.pdf](https://github.com/user-attachments/files/18210828/Informer.Beyond.Efficient.Transformer.for.Long.Sequence.Time-Series.Forecasting.Haoyi.Zhou.et.al.2020.v3.pdf)

**Comment by Byaidu** [comment]
这个是 feature （确信

**Comment by timelic** [comment]
哈哈哈哈哈哈哈哈我的天

**Comment by awwaawwa** [comment]
Fixed, just wait patiently
https://github.com/Byaidu/PDFMathTranslate/issues/406#issuecomment-2577562760
