### ISSUE TITLE
翻译后出现很多线段。

### ISSUE THREAD

**Issue by LiuhongjiAdersarial** [Byaidu/PDFMathTranslate#308]
![2110 14120v2 尺度证书可扩展的认证防御对抗对抗补丁与稀疏的表面层-mono conv 1](https://github.com/user-attachments/assets/e195fc17-59f5-42bf-be07-d02a24c53e47)
 请问为啥会出现这么多线段？

**Comment by LiuhongjiAdersarial** [comment]
【lstk】这个参数是全局线条。
在convert.py中，449 行，注销掉。
#ops += f"ET q 1 0 0 1 {l.pts[0][0]:f} {l.pts[0][1]:f} cm [] 0 d 0 J {l.linewidth:f} w 0 0 m {l.pts[1][0] - l.pts[0][0]:f} {l.pts[1][1] - l.pts[0][1]:f} l S Q BT "
但是有一点问题，就是表格没有了第一横行的横线。
引用的格式没了，全堆一起了，实际上，引用可以不用翻译。
![image](https://github.com/user-attachments/assets/b4a63953-2779-40a5-996e-5468be5af157)

**Comment by Byaidu** [comment]
别加 -d 参数

**Comment by Byaidu** [comment]
目前这个布局模型区分不出来正文和引用的区别，所以就统一翻译了

**Comment by LiuhongjiAdersarial** [comment]
非常棒的项目，是我用过最好的arxiv翻译。希望继续优化下去。加油
