### ISSUE TITLE
some formatting issues.

### ISSUE THREAD

**Issue by llleonzhao** [Byaidu/PDFMathTranslate#31]
![telegram-cloud-photo-size-1-5012867463620177258-y](https://github.com/user-attachments/assets/caa1b13d-064b-41f6-b3d0-43120d16ee89)

The text is overlapping.

**Comment by Byaidu** [comment]
日语排版有难度的，有需要可以手动调整字体大小和间隔 https://github.com/Byaidu/PDFMathTranslate/blob/main/pdf2zh/converter.py#L586
