### ISSUE TITLE
Python中新增函数只进行mono翻译或dual翻译

### ISSUE THREAD

**Issue by MemorXuxu** [Byaidu/PDFMathTranslate#314]
## 功能描述
请描述需要添加的功能，以及是否有类似项目可以参考
在high_level.py 中，看到有translate 和 translate_stream 这两个函数。通过这个函数，得到的是两个文件
有没有可能提供一个选项，或者一个新的函数，比如，translate_mono 和 translate_dual
这样的话，就可以只翻译得到一个版本，感觉这个应该是比较容易实现的，
谢谢！

**Comment by Byaidu** [comment]
只保存dual的stream到本地就可以实现需要的效果了

**Comment by MemorXuxu** [comment]
> 只保存dual的stream到本地就可以实现需要的效果了

好的，是的。我改了一下函数，把函数名字和后续write这一块修改。

```
def translate_mono( 
# 仅供参考别人参考
**
        doc_raw = open(file, "rb")
        s_raw = doc_raw.read()
        s_mono, s_dual = translate_stream(s_raw, **locals())
        file_mono = Path(output) / f"{filename}-mono.pdf"
        doc_mono = open(file_mono, "wb")
        doc_mono.write(s_mono)
        result_files.append((str(file_mono)))
)
```
# 
# 感谢作者！！
期待作者的Zotero集成，我现在就先写一个遍历Zotero进行批量翻译的py。毕竟我不太懂Zotero插件的开发语言，翻译后的文件索引到Zotero文件里面，还是不知道怎么解决。不过就先这么用着吧
