### ISSUE TITLE
Not all text is translated.

### ISSUE THREAD

**Issue by sstefanov** [Byaidu/PDFMathTranslate#317]
I tried online translator from pdf2zh.com with attached file. The text in the tables was not translated, for example on page 2.
Original file:
[ACM3128A_2X42W_1_失真_规格书__V1.1_PP.pdf](https://github.com/user-attachments/files/18221814/ACM3128A_2X42W_1_._.__V1.1_PP.pdf)
Translated file:
[ACM3128A_2X42W_en-mono.pdf](https://github.com/user-attachments/files/18221815/ACM3128A_2X42W_en-mono.pdf)

**Comment by gfhdhytghd** [comment]
This require OCR support

**Comment by sstefanov** [comment]
No, text is select-able in the original pdf.

**Comment by hellofinch** [comment]
https://github.com/Byaidu/PDFMathTranslate/issues/19
OCR WIP

**Comment by Byaidu** [comment]
table part is intentionally left untranslated. otherwise, the abbreviated terms would be translated into strange results.

**Comment by sstefanov** [comment]
Is is possible to add some check box, for example, to include table part translation?

**Comment by Byaidu** [comment]
sure, we will provide a option to in future

**Comment by gfhdhytghd** [comment]
> No, text is select-able in the original pdf.不可以，文本可以在原始 pdf 中选择。

almost all pdf viewer have a built in OCR

**Comment by gfhdhytghd** [comment]
> No, text is select-able in the original pdf.

Almost all PDF viewer have a built in OCR
