### ISSUE TITLE
how to uninstall this service?

### ISSUE THREAD

**Issue by aaron2wh** [Byaidu/PDFMathTranslate#328]

**Comment by aaron2wh** [comment]
I'm on a silicon Mac

**Comment by timelic** [comment]
`pip uninstall pdf2zh`

**Comment by milk2715093695** [comment]
To uninstall this service, run the following command in your terminal:

```bash
pip uninstall pdf2zh
```

If you installed it within a virtual environment, make sure to activate the virtual environment first before running the command.

Additionally, if you want to remove any unused dependencies that were installed along with the package, you can use:

```bash
pip-autoremove pdf2zh -y
```

This will remove the package along with any dependencies that are no longer needed.

**Comment by aaron2wh** [comment]
thanks, you mean first pip uninstall pdf2zh then pip-autoremove pdf2zh -y to clean uninstall or just pip-autoremove pdf2zh -y without the first command is OK?

**Comment by milk2715093695** [comment]
> thanks, you mean first pip uninstall pdf2zh then pip-autoremove pdf2zh -y to clean uninstall or just pip-autoremove pdf2zh -y without the first command is OK?

You’re welcome! You can just use:

```bash
pip-autoremove pdf2zh -y
```

This command will automatically uninstall pdf2zh and remove its unused dependencies in one step. There’s no need to run pip uninstall pdf2zh first.

However, if you already ran the pip uninstall pdf2zh command, running pip-autoremove pdf2zh -y afterward is still fine—it will clean up the unused dependencies regardless.

**Comment by aaron2wh** [comment]
one more question, maybe due to python version, when I install pdf2zh I should use 
`pip3 install pdf2zh  `
instead of pip install pdf2zh  
but when I try to run `pip-autoremove pdf2zh -y` or `pip3-autoremove pdf2zh -y`
it both prompt 
zsh: command not found: pip-autoremove  or 
zsh: command not found: pip3-autoremove
so what command should I use in my situation?

**Comment by milk2715093695** [comment]
> one more question, maybe due to python version, when I install pdf2zh I should use `pip3 install pdf2zh ` instead of pip install pdf2zh but when I try to run `pip-autoremove pdf2zh -y` or `pip3-autoremove pdf2zh -y` it both prompt zsh: command not found: pip-autoremove or zsh: command not found: pip3-autoremove so what command should I use in my situation?

I apologize for not explaining it clearly earlier. To clarify, pip-autoremove is itself a package specifically for cleaning up unnecessary dependencies. If you haven’t installed it yet, you’ll need to install it first:

```bash
pip install pip-autoremove
```

After that, you can use it like this:

```bash
pip-autoremove pdf2zh -y
```

This will uninstall pdf2zh and remove any unused dependencies.

However, I understand this might feel a bit inconvenient—you need to install a new package just to clean up the old one. If that’s a concern, you can stick to manually uninstalling pdf2zh with:

```
pip uninstall pdf2zh
```

While this won’t remove unused dependencies, it’s a simpler approach if you don’t want to install extra tools. And it's much easier.

**Comment by milk2715093695** [comment]
By the way, in Python 3, it’s normal to use pip3 instead of pip. This is standard behavior to distinguish it from Python 2’s pip.
