### ISSUE TITLE
我修改了gui.py里面的内容，但是页面好像没有发生改变

### ISSUE THREAD

**Issue by abandon-alt** [Byaidu/PDFMathTranslate#331]
![image](https://github.com/user-attachments/assets/df69ee74-ed54-4a63-88e7-d68dab65a917)
我将google修改为openai然后将English修改为Chinese，重新启动之后页面没有发生变化
![image](https://github.com/user-attachments/assets/540d3330-0cc6-42da-a8af-de9115bce596)

**Comment by hellofinch** [comment]
vlaue 应该是没对应上，要是想自定义的话仔细看一下translator.py里的内容。

**Comment by abandon-alt** [comment]
> vlaue 应该是没对应上，要是想自定义的话仔细看一下 translator.py 里的内容。

如果我想默认用openai应该把value改成什么呢，求大佬指点。
我在translator里面只找到了修改默认变量的代码
![image](https://github.com/user-attachments/assets/0df3f9d2-1a86-41e1-82f8-ec9af858e075)

**Comment by hellofinch** [comment]
好像是bug，我研究一下，要是bug的话，请再等一等。

**Comment by hellofinch** [comment]
我知道为什么改了没反应了，但是我不清楚为什么有这样的设置，可能需要讨论一下为什么。
对于你的问题，你需要做两步：
1. 注释掉95行到98行
2. 把value改成OpenAI
应该就可以解决你的问题。

**Comment by abandon-alt** [comment]
> 我知道为什么改了没反应了，但是我不清楚为什么有这样的设置，可能需要讨论一下为什么。 对于你的问题，你需要做两步：
> 
> 1. 注释掉95行到98行
> 2. 把value改成OpenAI
> 
> 应该就可以解决你的问题。 : )

我下载了最新的gui.py，修改value为openai，但是默认的还是google
![image](https://github.com/user-attachments/assets/5ded1d7f-2f10-48f1-9045-51e490450b41)

**Comment by Byaidu** [comment]
pip install -e .

**Comment by abandon-alt** [comment]
> pip install -e .

我用的是方法二，这个命令在哪里输入呢

**Comment by Byaidu** [comment]
方法二可能不方便改代码，建议用方法一

**Comment by abandon-alt** [comment]
> 方法二可能不方便改代码，建议用方法一

好的，我试试

**Comment by abandon-alt** [comment]
> 方法二可能不方便改代码，建议用方法一

我使用了方法一，默认确实是openai了，但是不会出现填写api的那一行，得切换成其他的再切回来openai才行
![image](https://github.com/user-attachments/assets/bfa58583-673f-43e0-b54f-e261733e8e28)
![image](https://github.com/user-attachments/assets/bc61c575-7b1f-4538-aa99-cca78cc6b5a7)
