### ISSUE TITLE
Zotero

### ISSUE THREAD

**Issue by zhuwenhao** [Byaidu/PDFMathTranslate#335]
## 功能描述
您好！请问是否可以提供一个Zotero插件？对于经常使用Zotero查阅论文的人来说，这将非常有帮助。
Hello, could you provide a Zotero plugin? It would be very helpful for those who frequently use Zotero to read papers.

**Comment by timelic** [comment]
see https://github.com/Byaidu/PDFMathTranslate/issues/205

**Comment by Byaidu** [comment]
我也在用zotero阅读，但是目前看起来还没有人在开发插件

不过我们提供了API用于接入，有兴趣的话你可以自己写一个插件试试

**Comment by fly-pigTH** [comment]
Is anyone up for giving it a try? QWQ！

**Comment by guaguastandup** [comment]
我写了一个插件，需要自己在后端run一下python脚本，欢迎使用：https://github.com/guaguastandup/zotero-pdf2zh
