### ISSUE TITLE
重复ERROR:pdf2zh.converter:Empty translation result

### ISSUE THREAD

**Issue by yshi100** [Byaidu/PDFMathTranslate#34]
ckpt = torch.load(file, map_location="cpu")
  1%|▉                                                                                | 5/440 [00:14<19:00,  2.62s/it]ERROR:pdf2zh.converter:Empty translation result
  7%|█████▎                                                                          | 29/440 [01:38<15:18,  2.23s/it]ERROR:pdf2zh.converter:Empty translation result
 10%|████████▎                                                                       | 46/440 [02:32<22:38,  3.45s/it]ERROR:pdf2zh.converter:Empty translation result
 11%|████████▉                                                                       | 49/440 [02:59<48:36,  7.46s/it]ERROR:pdf2zh.converter:Empty translation result
 19%|███████████████                                                                 | 83/440 [05:29<20:09,  3.39s/it]ERROR:pdf2zh.converter:Empty translation result
 22%|█████████████████▊                                                              | 98/440 [06:12<14:04,  2.47s/it]ERROR:pdf2zh.converter:Empty translation result
ERROR:pdf2zh.converter:Empty translation result
ERROR:pdf2zh.converter:Empty translation result
ERROR:pdf2zh.converter:Empty translation result
ERROR:pdf2zh.converter:Empty translation result
ERROR:pdf2zh.converter:Empty translation result
ERROR:pdf2zh.converter:Empty translation result
ERROR:pdf2zh.converter:Empty translation result

**Comment by Byaidu** [comment]
ip 被 ban 了，换个节点或者换个翻译服务

**Comment by yshi100** [comment]
多谢

**Comment by anbian123** [comment]
Command output: 0%|          | 0/1 [00:00<?, ?it/s]ERROR:pdf2zh.converter:[SSL] record layer failure (_ssl.c:997)
这个报错遇了吗
