### ISSUE TITLE
选择其他翻译服务 如 Bing，使用的还是google

### ISSUE THREAD

**Issue by BeamBrother** [Byaidu/PDFMathTranslate#346]
docker 部署 最新版，页面进行转译，调用接口是Bing
![image](https://github.com/user-attachments/assets/3177d4cf-6fd3-47ba-a406-e2c961ac2dd1)

但是服务打印出来的还是 谷歌
![image](https://github.com/user-attachments/assets/a44254e8-b83d-4443-aa81-1b15db520898)

**Comment by hellofinch** [comment]
最新版指的是1.8.8吗？如果是自己打包的镜像的话，两天前有过代码更新，这个问题已经解决了。
https://github.com/Byaidu/PDFMathTranslate/commit/f94c6e10477be3a45ff322ff281f77a547bd4ce1

**Comment by BeamBrother** [comment]
> 最新版指的是1.8.8吗？如果是自己打包的镜像的话，两天前有过代码更新，这个问题已经解决了。 [f94c6e1](https://github.com/Byaidu/PDFMathTranslate/commit/f94c6e10477be3a45ff322ff281f77a547bd4ce1)

是的，1.8.8。那我这边重新试一遍

**Comment by BeamBrother** [comment]
> 最新版指的是1.8.8吗？如果是自己打包的镜像的话，两天前有过代码更新，这个问题已经解决了。 [f94c6e1](https://github.com/Byaidu/PDFMathTranslate/commit/f94c6e10477be3a45ff322ff281f77a547bd4ce1)

docker镜像是不是没更新？我昨天拉的镜像

**Comment by hellofinch** [comment]
docker镜像随着release一起更新。1.8.8的话这个地方还没加上去，应该没问题呀？

**Comment by BeamBrother** [comment]
> docker镜像随着release一起更新。1.8.8的话这个地方还没加上去，应该没问题呀？

**Comment by BeamBrother** [comment]
> docker镜像随着release一起更新。1.8.8的话这个地方还没加上去，应该没问题呀？

重新构建后解决了

**Comment by BeamBrother** [comment]
> docker镜像随着release一起更新。1.8.8的话这个地方还没加上去，应该没问题呀？

重新构建后解决了
