### ISSUE TITLE
无法使用--prompt 参数来指定 prompt.txt文件

### ISSUE THREAD

**Issue by fr58386612** [Byaidu/PDFMathTranslate#350]
![Clip_2024-12-26_16-43-08](https://github.com/user-attachments/assets/20f178b2-1533-4c37-b95a-ebe6dff5a0ee)

**Comment by hellofinch** [comment]
--prompt 开关更新了。

**Comment by fr58386612** [comment]
我的需求是翻译小众的语言，大模型本来是支持的，但是该工具上没有这个小众语言，请问我应该怎么配置？

**Comment by hellofinch** [comment]
https://github.com/Byaidu/PDFMathTranslate/blob/main/docs/ADVANCED.md#custom-prompt
目前默认的prompt没有指定输入语言，只指定了输出语言。如果需要自定义输入语言的话， 目前只能通过修改程序里的语言列表添加。

**Comment by fr58386612** [comment]
能否考虑增加自行添加源语言类型，满足更多的源语言支持

**Comment by hellofinch** [comment]
可以加个enhancement @Byaidu @Wybxc

**Comment by Byaidu** [comment]
-li/-lo不是就支持多语言吗？

**Comment by fr58386612** [comment]
不支持  缅甸语、越南语这些啊

**Comment by Byaidu** [comment]
![image](https://github.com/user-attachments/assets/87d7162b-5ed8-4555-879a-de6843dd69a8)

pdf2zh example.pdf -lo vi

？怎么就不支持了

**Comment by hellofinch** [comment]
说的可能是UI吧？

**Comment by Byaidu** [comment]
那他标题写的不是命令行？

**Comment by hellofinch** [comment]
看错了。。。
