### ISSUE TITLE
修改了translator.py和gui.py让默认设置是openai开头，但是不能正常翻译

### ISSUE THREAD

**Issue by abandon-alt** [Byaidu/PDFMathTranslate#351]
![image](https://github.com/user-attachments/assets/8534b330-fd88-4cf8-ba3d-27717b58fb35)
这是改完之后进去的图片
![image](https://github.com/user-attachments/assets/5662363f-4227-4113-a16a-50904b9f4372)
这是点击翻译之后的错误

**Comment by Byaidu** [comment]
带文件反馈
