### ISSUE TITLE
应该是字体问题，被翻译的PDF在Mac下的Edge浏览器打开中文不显示

### ISSUE THREAD

**Issue by rooly2022** [Byaidu/PDFMathTranslate#354]
## 问题描述
测试了下，在windows下的虚拟环境下可以成功翻译为中文的pdf，但是这个pdf文件在MacOS下用edge浏览器打开是看不到中文的，可能是字体的问题。用系统自带的预览和chrome打开都可以看到中文。

作者可以测试下。

**Comment by Byaidu** [comment]
没有mac，不过下个版本可能会解决（

**Comment by rooly2022** [comment]
> 没有mac，不过下个版本可能会解决（

好的，谢谢，等待更新后测试下。
