### ISSUE TITLE
翻译无效

### ISSUE THREAD

**Issue by wx-11** [Byaidu/PDFMathTranslate#358]
## 问题描述
使用测试站点/以及自建服务 谷歌/bing/openai密钥 没效果 而且gui没有预览
![image](https://github.com/user-attachments/assets/31eea34f-2bd5-4704-8a65-2750c7831287)

## 测试文档

[033-Teacher efficacy_ its meaning and measure.pdf](https://github.com/user-attachments/files/18258594/033-Teacher.efficacy_.its.meaning.and.measure.pdf)

**Comment by Byaidu** [comment]
翻译文档不需要ocr

**Comment by hellofinch** [comment]
https://github.com/Byaidu/PDFMathTranslate/issues/19
OCR WIP

**Comment by hellofinch** [comment]
可以，后边的那几页都是扫描件，暂时确实处理不了。

**Comment by hellofinch** [comment]
准确描述应该是我这里也没有出结果，但是可以看出来，后边论文正文都是扫描件。

**Comment by Byaidu** [comment]
![image](https://github.com/user-attachments/assets/d18bd178-c8f4-45b8-9224-748604717af5)

一眼扫描件，别试了

**Comment by hellofinch** [comment]
第一页不是扫描件，确实没出来很奇怪。
![image](https://github.com/user-attachments/assets/ed476c89-37eb-4679-bd61-f859ff09090e)

**Comment by hellofinch** [comment]
后边那些都是扫描件，第一页上有什么东西做了特别判断吗？

**Comment by Byaidu** [comment]
是这样，因为第一段根本没有正文……

**Comment by Byaidu** [comment]
没有，公式部分和装饰部分显然是不应该处理的，所以为什么不处理非正文部分呢
