### ISSUE TITLE
进度条100%后疑似死循环？

### ISSUE THREAD

**Issue by Kwansy98** [Byaidu/PDFMathTranslate#359]
## 问题描述
我本地部署了一个qwen模型用于翻译，测试小pdf翻译成功，然后翻译25MB的intel手册的前5页，进度条100%后卡死，并且一直在给大模型发送请求。
set OPENAI_BASE_URL=http://127.0.0.1:1234/v1
set OPENAI_API_KEY=xx
set OPENAI_MODEL=Qwen/Qwen2.5-Coder-3B-Instruct-GGUF
pdf2zh Desktop\intel2024.pdf -li en -lo zh -t 1 -p 1-5 -s openai  -o intel_zh.pdf

![image](https://github.com/user-attachments/assets/d5ac9f16-af50-448f-8db8-194dcc00cb25)

## 测试文档

测试文档是intel开发手册（25MB）
https://cdrdv2-public.intel.com/835781/325462-sdm-vol-1-2abcd-3abcd-4.pdf

**Comment by Byaidu** [comment]
建议换个模型

**Comment by zkang529** [comment]
最后怎么解决的呢

**Comment by Kwansy98** [comment]
> 最后怎么解决的呢

换了qwen 7b，模型设置输出限制2048，上下文10000，温度0

set OPENAI_BASE_URL=http://127.0.0.1:1234/v1
set OPENAI_API_KEY=xx
set OPENAI_MODEL=lmstudio-community/Qwen2.5-Coder-7B-Instruct-GGUF
pdf2zh Desktop\intel2024.pdf -li en -lo zh -t 1 -s openai
