### ISSUE TITLE
翻译的文件会有 源文本: 翻译文本: 的字样胡乱插入在不同地方

### ISSUE THREAD

**Issue by Atul-8** [Byaidu/PDFMathTranslate#361]
## 问题描述
我在个人电脑使用pip部署, 翻译出来的一个文件会有文本乱码;
使用的翻译api是zhipu的
![图片](https://github.com/user-attachments/assets/9249be8a-acc0-4ac9-9a89-12e609ac463f)

## 测试文档
> [!IMPORTANT]
> 请提供用于复现测试的 PDF 文档
https://www.qstcorp.com/upload/pdf/202301/13-52-25%20QMI8658A%20Datasheet%20Rev%20A.pdf

**Comment by Byaidu** [comment]
https://github.com/Byaidu/PDFMathTranslate/issues/367

**Comment by Atul-8** [comment]
我重新升级到 1.8.8版本就解决了
