### ISSUE TITLE
翻译后出现多余的信息

### ISSUE THREAD

**Issue by WallBreakerNO4** [Byaidu/PDFMathTranslate#367]
## 问题描述
在翻译后，出现多余的信息

![image](https://github.com/user-attachments/assets/a1025704-4c62-4dcd-ab56-3d6cb4cbe99d)

## 测试文档

[Chap1_Introduction_to_Mobile_Computing.pdf](https://github.com/user-attachments/files/18266260/Chap1_Introduction_to_Mobile_Computing.pdf)

**Comment by WallBreakerNO4** [comment]
使用 Ollama + qwen2.5 7b 翻译
![image](https://github.com/user-attachments/assets/b8decde3-61b8-46c9-9b25-db9ac38380d2)

**Comment by imClumsyPanda** [comment]
感觉应该是qwen2.5本身回复翻译时产生了多余内容。

目前测试过qwen2.5和gemma2，个人感觉gemma2效果更好些
