### ISSUE TITLE
Source and Translated Text appearing simultaneously

### ISSUE THREAD

**Issue by guillevazquezg** [Byaidu/PDFMathTranslate#369]
## Problem Description
When running `pdf2zh original.pdf` the generated document writes the translated text on top of the original untranslated text. 

For example, for this text in the original pdf:

<img width="575" alt="image" src="https://github.com/user-attachments/assets/9307fb1e-e5de-4014-927e-4dad68103c52" />

It generated this:

<img width="604" alt="image" src="https://github.com/user-attachments/assets/c883a6a0-2b69-4b19-b96a-a9e6557b9684" />

As you can see, both the base text before performing the translation (English) and the translated text (Chinese) appear in `original-mono.pdf` in the same position. The desired result would be that only the translated text in Chinese appears.

## Test Document
Source PDF file: [original.pdf](https://github.com/user-attachments/files/18268064/original.pdf)

**Comment by Byaidu** [comment]
https://github.com/Byaidu/PDFMathTranslate/issues/19
