### ISSUE TITLE
编程代码段有时候会重叠显示

### ISSUE THREAD

**Issue by fivestrong** [Byaidu/PDFMathTranslate#37]
## 问题描述
请对问题进行描述，并提供日志或截图
**本项目不处理网络环境引发的问题**（例如 Empty translation result/Connection reset）

翻译包含编程代码块儿的部分，有些时候会产生代码重叠的问题（并不是所有代码都会出现这个问题）。
![image](https://github.com/user-attachments/assets/47b0bd6a-543b-40c0-b702-e147fff81cbf)

## 测试文档
> [!IMPORTANT]
> 请提供用于复现测试的 PDF 文档

[test.pdf](https://github.com/user-attachments/files/17710151/test.pdf)
[test-zh.pdf](https://github.com/user-attachments/files/17710153/test-zh.pdf)

**Comment by Byaidu** [comment]
有的时候这个布局分析模型的识别效果不太稳定

**Comment by Byaidu** [comment]
![image](https://github.com/user-attachments/assets/9e31bd1e-1fd6-4df4-a524-f4062b0867c6)

已修复，请等待新版本发布
