### ISSUE TITLE
能否修改openai或者deepl的默认第三方自定义接口地址

### ISSUE THREAD

**Issue by gkngkngkn** [Byaidu/PDFMathTranslate#370]
用的便携版gui，在选择openai或者deepl翻译的时候，DEEPL_SERVER_URL填写的是官方默认地址，每次我需要手动把他改成第三方接口地址，能否修改默认地址为自定义的，需要在哪里修改？ 还有就是打开gui后能否默认选择为openai或者deepl，而不是google，谢谢！

**Comment by Byaidu** [comment]
启动脚本里设置DEEPL_SERVER_URL变量
