### ISSUE TITLE
翻译识别不出 → .呈现乱码

### ISSUE THREAD

**Issue by Atul-8** [Byaidu/PDFMathTranslate#372]
## 问题描述
如图: 对于箭头会乱码成 ❓
![图片](https://github.com/user-attachments/assets/c95ec751-adb5-451d-9505-118569773647)
## 测试文档
> [!IMPORTANT]
> 请提供用于复现测试的 PDF 文档
https://www.qstcorp.com/upload/pdf/202301/13-52-25%20QMI8658A%20Datasheet%20Rev%20A.pdf

**Comment by Byaidu** [comment]
![image](https://github.com/user-attachments/assets/70417169-2504-4e2b-ae72-b775ad812e55)

pdf 自身的问题，直接复制文字也是乱码
