### ISSUE TITLE
翻译的文件没有覆盖英文,直接再下面显示译文导致文字重叠

### ISSUE THREAD

**Issue by Atul-8** [Byaidu/PDFMathTranslate#373]
## 问题描述
如图:翻译的文件没有覆盖英文,直接再下面显示译文导致文字重叠;

![图片](https://github.com/user-attachments/assets/e41ac3ec-ad23-4cfb-ace3-ce7926bd32c0)

## 测试文档
> [!IMPORTANT]
> 请提供用于复现测试的 PDF 文档
https://www.qstcorp.com/upload/pdf/202301/13-52-25%20QMI8658A%20Datasheet%20Rev%20A.pdf

**Comment by Byaidu** [comment]
尽量别用llm翻译，翻译效果不好控制
