### ISSUE TITLE
Setup Error

### ISSUE THREAD

**Issue by ZhangPeterGree** [Byaidu/PDFMathTranslate#374]
![Screenshot From 2024-12-30 00-54-27](https://github.com/user-attachments/assets/5053255a-1e3c-4c1d-9ed3-4673469f7f42)
![Screenshot From 2024-12-30 00-57-15](https://github.com/user-attachments/assets/1dcf65fd-357b-4cd7-8f28-f19618d09e0b)

**Comment by Byaidu** [comment]
网络问题
