### ISSUE TITLE
web 页面怎么下载全量的翻译后的 pdf?

### ISSUE THREAD

**Issue by jlcoo** [Byaidu/PDFMathTranslate#376]
## 功能描述
请描述需要添加的功能，以及是否有类似项目可以参考
当前web页面貌似只能下载第一页和第二页的pdf，怎么快速下载全量的pdf? 或者有一个原文和翻译后的对比版本？
![image](https://github.com/user-attachments/assets/aecc7b57-5610-4476-a99f-dbe3e3c2a12e)

**Comment by hellofinch** [comment]
没有理解你的需求，你是自己部署的还是用的online demo？

**Comment by Byaidu** [comment]
页面左下角

**Comment by jlcoo** [comment]
> 页面左下角
左下角下载后只有一页的pdf呀，不是所有页的pdf

**Comment by jlcoo** [comment]
> 没有理解你的需求，你是自己部署的还是用的online demo？

自己部署和online demo 下载后都只有单页翻译后的结果，没有全部翻译后的结果

**Comment by hellofinch** [comment]
PDF文件是扫描件吗？扫描件的话处理不了。
