### ISSUE TITLE
Api: Suppressing TQDM Console Output when Creating .exe without Console

### ISSUE THREAD

**Issue by Jose-Maria-Martins** [Byaidu/PDFMathTranslate#381]
I'm working on creating a .exe file without a console window, but I'm encountering an issue with the TQDM library. When I try to run the executable without the console, I get the following error:

NoneType error: 'NoneType' object has no attribute 'write'

This error occurs because TQDM is attempting to write output to the console. However, when I compile with a console, everything works fine, and I don't face the issue.

Is there a way to suppress the need for TQDM to write to the console, or to redirect the output to prevent this error when running the .exe without the console?

I would appreciate any insights or suggestions on how to resolve this.

**Comment by Byaidu** [comment]
You can patch the code https://github.com/Byaidu/PDFMathTranslate/blob/main/pdf2zh/high_level.py#L121
