### ISSUE TITLE
多处代码显示重叠

### ISSUE THREAD

**Issue by yshi100** [Byaidu/PDFMathTranslate#39]
![1](https://github.com/user-attachments/assets/22a7909e-1e64-409e-a43d-c3d53ed7376d)
[Uploading Modern Front-End Development for Rails Hotwire, Stimulus, Turbo, and React, 2nd Edition (Noel Rappin) (Z-Library).pdf…]()

**Comment by yshi100** [comment]
转换后的代码能保持原来的配色吗？

**Comment by Byaidu** [comment]
暂时不能，以后可能会加上颜色支持
