### ISSUE TITLE
加入免费的glm4-flash模型进行翻译

### ISSUE THREAD

**Issue by kashima19960** [Byaidu/PDFMathTranslate#42]
## 功能描述
智谱清言的glm-4-flash模型的api是免费开放使用的，作为ai翻译来说非常强力，希望作者能考虑一下，添加glm-4-flash的使用方法
![image](https://github.com/user-attachments/assets/7a7dc9ab-2dff-4598-bf8b-80aee60e84bc)

## reference
[glm接口文档](https://open.bigmodel.cn/dev/api/normal-model/glm-4)

**Comment by Byaidu** [comment]
可以配置 openai 的环境变量直接使用
https://open.bigmodel.cn/dev/api/thirdparty-frame/openai-sdk
