### ISSUE TITLE
多文档时应当可以并行，或者允许设置并行请求。

### ISSUE THREAD

**Issue by etjec4** [Byaidu/PDFMathTranslate#43]
如题

**Comment by Byaidu** [comment]
多开几个进程就并行了

**Comment by reycn** [comment]
This feature ([multi-threads](https://github.com/Byaidu/PDFMathTranslate#threads)) has been finished by Byaidu. Now your can specify the number of threads by `-t 1` etc.


这个功能（[多线程](https://github.com/Byaidu/PDFMathTranslate#threads)）已经由Byaidu完成。现在你可以通过 `-t 1` 等来指定线程数。
