### ISSUE TITLE
 ckpt = torch.load(file, map_location="cpu")

### ISSUE THREAD

**Issue by colin4k** [Byaidu/PDFMathTranslate#44]
## 问题描述
启动后控制台有显示“ ckpt = torch.load(file, map_location="cpu")”，然后加载模型速度很慢，我是Ubuntu下有4080s，如何才能使用GPU？

## 测试文档
已安装 CUDN 12 & cudnn

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Tue_Feb_27_16:19:38_PST_2024
Cuda compilation tools, release 12.4, V12.4.99
Build cuda_12.4.r12.4/compiler.33961263_0

**Comment by CLDYG7240** [comment]
有同样的问题 可以优化一下吗？

**Comment by reycn** [comment]
Fixed @ [PR#66](https://github.com/Byaidu/PDFMathTranslate/pull/66)

@colin4k @CLDYG7240 @Byaidu
