### ISSUE TITLE
APA参考文献部分会有问题，格式不匹配

### ISSUE THREAD

**Issue by zifeiyu1999** [Byaidu/PDFMathTranslate#45]
## 问题描述
没有自动换行，参考文献全部识别为一个段落
![image](https://github.com/user-attachments/assets/3b3c732d-6165-411d-b19a-84c32e40a119)

**Comment by zifeiyu1999** [comment]
文件名好像还不能有空格，不然会报错，找不到文件

**Comment by Byaidu** [comment]
已知问题，可以暂时先看双语文档的原文部分

文件名包含空格请参考 https://github.com/Byaidu/PDFMathTranslate/issues/30
