### ISSUE TITLE
deeplx报错

### ISSUE THREAD

**Issue by xxsunyxx** [Byaidu/PDFMathTranslate#46]
## 问题描述
请对问题进行描述，并提供日志或截图
**本项目不处理网络环境引发的问题**（例如 Empty translation result/Connection reset）
 D:\>set DEEPL_SERVER_URL=https://deeplx.papercar.top/translate

(para) D:\>pdf2zh geo.pdf -s deepl
C:\anaconda\envs\para\lib\site-packages\doclayout_yolo\nn\tasks.py:733: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckpt = torch.load(file, map_location="cpu")
  0%|▏                                                                                 | 1/337 [00:01<11:01,  1.97s/it]ERROR:pdf2zh.converter:int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
ERROR:pdf2zh.converter:int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
ERROR:pdf2zh.converter:int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
ERROR:pdf2zh.converter:int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
ERROR:pdf2zh.converter:int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
ERROR:pdf2zh.converter:int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
ERROR:pdf2zh.converter:int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
ERROR:pdf2zh.converter:int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
ERROR:pdf2zh.converter:int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
ERROR:pdf2zh.converter:int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
ERROR:pdf2zh.converter:int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
ERROR:pdf2zh.converter:int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

## 测试文档
> [!IMPORTANT]
> 请提供用于复现测试的 PDF 文档
[Schaums outline of geometry (Barnett Rich, Christopher Thomas) (Z-Library).pdf](https://github.com/user-attachments/files/17743376/Schaums.outline.of.geometry.Barnett.Rich.Christopher.Thomas.Z-Library.pdf)

恭喜你爆star了,我的长江老板已经给你推了

**Comment by Byaidu** [comment]
那个后面的 /translate 会自动加的，你只需要设置前面的部分就好了

set DEEPL_SERVER_URL=https://deeplx.papercar.top

**Comment by Byaidu** [comment]
```
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
INFO:deepl:Request to DeepL API method=POST url=https://deeplx.papercar.top/v2/translate
DEBUG:deepl:Request details data={} json={'target_lang': 'ZH', 'source_lang': 'EN', 'text': ['eometry '], 'show_billed_characters': True}
INFO:deepl:Request to DeepL API method=POST url=https://deeplx.papercar.top/v2/translate
DEBUG:deepl:Request details data={} json={'target_lang': 'ZH', 'source_lang': 'EN', 'text': ['G'], 'show_billed_characters': True}
INFO:deepl:DeepL API response status_code=200 url=https://deeplx.papercar.top/v2/translate
DEBUG:deepl:Response details content={"translations":[{"detected_source_language":"","text":"G"}]}
ERROR:pdf2zh.converter:int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
Traceback (most recent call last):
  File "c:\users\apple\desktop\pdfmathtranslate\pdf2zh\converter.py", line 521, in worker
    new=self.translator.translate(s)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\apple\desktop\pdfmathtranslate\pdf2zh\translator.py", line 65, in translate
    response = self.client.translate_text(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apple\AppData\Local\Programs\Python\Python311\Lib\site-packages\deepl\translator.py", line 464, in translate_text
    billed_characters = int(translation.get("billed_characters"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
好像是 deepl 好像请求到 v2 接口上了，等下我看看怎么改

**Comment by Byaidu** [comment]
应该修好了，是上游 deepl 的问题

**Comment by xxsunyxx** [comment]
有卡的机器在跑别的,一会试试反馈

**Comment by xxsunyxx** [comment]
经过确认deeplx没法承载较高的负荷(远程调用和自有的deeplx都不太行)跑这本跑个开头就死了,2-3页的paper还可以. 如果开发分布式的请求,有点不道德.
如我一般翻书的..基本不太行

**Comment by Byaidu** [comment]
确实，我这里也是，还以为是我网的问题……
