### ISSUE TITLE
feat (gui): supports gui

### ISSUE THREAD

**Issue by reycn** [Byaidu/PDFMathTranslate#47]
## Description
Support GUI-based interactions for users to translate their PDFs locally.

Similar functions were provided by the following projects:

1. https://github.com/immersive-translate/immersive-translate

I can implement if I have time in the near future.

**Comment by Hunlongyu** [comment]
准备用什么技术栈开发 GUI 吗？
我是 C++、Python、JS 开发者，熟悉 QT、Pyside6 开发，可以帮忙开发 GUI。贡献pr

**Comment by reycn** [comment]
Done
