### ISSUE TITLE
我想在完全离线的内网使用，但好像刚开始运行pdf2zh时要下载一个文件，请问是下载哪个文件，放到哪里呢？

### ISSUE THREAD

**Issue by ying06** [Byaidu/PDFMathTranslate#48]
如题。
办公时只能用内网，不能连接到互联网。
另外，使用ollama本地模型翻译时，远慢于google在线模型，有什么加速方法么？

**Comment by Byaidu** [comment]
https://github.com/Byaidu/PDFMathTranslate/blob/main/pdf2zh/pdf2zh.py#L73

不知道为什么会有离线办公还需要翻译文档的场景，建议找网管开个规则

**Comment by JiNanPiWang** [comment]
> https://github.com/Byaidu/PDFMathTranslate/blob/main/pdf2zh/pdf2zh.py#L73
> 
> 不知道为什么会有离线办公还需要翻译文档的场景，建议找网管开个规则

有一些保密文档是英文的，而且很长，实在是看不懂

**Comment by ying06** [comment]
> > https://github.com/Byaidu/PDFMathTranslate/blob/main/pdf2zh/pdf2zh.py#L73
> > 不知道为什么会有离线办公还需要翻译文档的场景，建议找网管开个规则
> 
> 有一些保密文档是英文的，而且很长，实在是看不懂

是在物理断网的情况下做科研，确实有点funny，还经常BM检查。。。
