### ISSUE TITLE
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by sj-ganwh** [Byaidu/PDFMathTranslate#49]
## 问题描述
Issue:
![image](https://github.com/user-attachments/assets/7243950f-66ea-4e53-9841-679f7f352667)

## 测试文档
Solution: 
`sudo apt install libgl1-mesa-glx`

**Comment by hellofinch** [comment]
Missing `libgl1-mesa-glx` in ubuntu 24.04, the problem still pops out.

**Comment by benpaodewoniu** [comment]
if you are ubuntu24.04,you can try sudo apt install -y libgl1
