### ISSUE TITLE
翻译之后页面偏离

### ISSUE THREAD

**Issue by Williamsunsir** [Byaidu/PDFMathTranslate#5]
![image](https://github.com/user-attachments/assets/b59b2e32-ea59-4826-906e-1b166a6a9673)

附件如下：
[b8c2b4c5cdf340d5.pdf](https://github.com/user-attachments/files/17394868/b8c2b4c5cdf340d5.pdf)

**Comment by Byaidu** [comment]
现在应该修好了

**Comment by Williamsunsir** [comment]
非常感谢，已经正常
