### ISSUE TITLE
deeplx的DEEPL_AUTH_KEY怎么获得

### ISSUE THREAD

**Issue by ygc666666** [Byaidu/PDFMathTranslate#50]
DEEPL_AUTH_KEY怎么设置，需要deepl pro账号吗

**Comment by Byaidu** [comment]
如果 deeplx 的提供者没有设置鉴权，可以随便填一个 key 进去

**Comment by Byaidu** [comment]
> The auth_key was designed for project DeepLX (link available in the readme doc) only, instead of the official version. 
> 
> 
> 
> auth_key 是为 DeepLX 项目设计的（链接在自述文档中可用），而不是官方版本。

deeplx 那个好像被我改糊了……现在可能只有官方 deepl 服务能用

你看看要不要再单独实现一个 deeplx 的逻辑加回来（

**Comment by reycn** [comment]
> > The auth_key was designed for project DeepLX (link available in the readme doc) only, instead of the official version.
> > auth_key 是为 DeepLX 项目设计的（链接在自述文档中可用），而不是官方版本。
> 
> deeplx 那个好像被我改糊了……现在可能只有官方 deepl 服务能用
> 
> 你看看要不要再单独实现一个 deeplx 的逻辑加回来（

...........

**Comment by reycn** [comment]
Done
