### ISSUE TITLE
行内公式识别问题？

### ISSUE THREAD

**Issue by wendribss** [Byaidu/PDFMathTranslate#51]
在识别过程中行间公式识别正常且排版正常，但是行内公式识别存在错误且出现大量横线遮挡文字和公式部分，请问应该如何处理呢？

![image](https://github.com/user-attachments/assets/4dbce98a-4bbf-4e10-9bdf-bcbaef6fb273)

![image](https://github.com/user-attachments/assets/b91faa63-b5fc-497a-9219-a41397634c28)

**Comment by Byaidu** [comment]
目前行内多行公式还在进一步优化，不过大部份简单公式应该是没问题的

**Comment by wendribss** [comment]
好的，非常感谢
