### ISSUE TITLE
ERROR:pdf2zh.converter:'str' object has no attribute 'choices'

### ISSUE THREAD

**Issue by itning** [Byaidu/PDFMathTranslate#56]
## 问题描述
使用openapi gpt4o
C:\Users\a\anaconda3\envs\pdf2zh\Lib\site-packages\doclayout_yolo\nn\tasks.py:733: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckpt = torch.load(file, map_location="cpu")
  0%|                                                                                           | 0/69 [00:00<?, ?it/s]ERROR:pdf2zh.converter:'str' object has no attribute 'choices'
ERROR:pdf2zh.converter:'str' object has no attribute 'choices'
ERROR:pdf2zh.converter:'str' object has no attribute 'choices'
ERROR:pdf2zh.converter:'str' object has no attribute 'choices'
## 测试文档
> [!IMPORTANT]
> 请提供用于复现测试的 PDF 文档
[a.pdf](https://github.com/user-attachments/files/17790384/a.pdf)

**Comment by reycn** [comment]
Not replicated. Please check your configurations.
未能复现。请检查您的配置。

Command： `pdf2zh './a.pdf' -s openai:gpt-4o -p 1`
命令： `pdf2zh './a.pdf' -s openai:gpt-4o -p 1`

Results attached:
结果如下
[a-zh.pdf](https://github.com/user-attachments/files/17810907/a-zh.pdf)

**Comment by shi1001** [comment]
出现 `ERROR:pdf2zh.converter:'str' object has no attribute 'choices'` 错误，表明在 `pdf2zh` 库的 `converter` 模块中，代码试图调用字符串（`str`）对象的 `.choices` 属性，但字符串类型并没有这个属性。以下是具体原因和解决方案：

---

### **错误原因**
1. **参数类型错误**  
   - 你传递给 `pdf2zh` 的某个函数的参数应该是 **列表（list）** 或 **可迭代对象**，但实际传递的是一个 **字符串（str）**。
   - 例如，某个选项参数需要接受多个值（如 `choices=["A", "B", "C"]`），但你直接传递了字符串 `"A"` 而非列表 `["A"]`。

2. **库的预期行为**  
   - 库内部可能调用了类似 `random.choices()` 的方法，但误将字符串作为参数传递，导致尝试访问 `.choices` 属性时失败。

---

### **解决方案**
#### 1. 检查参数类型
   - 检查调用 `pdf2zh` 函数时传递的参数，尤其是涉及多选的参数（如翻译选项、输出格式等），确保其类型为 **列表** 而非字符串。
   - **错误示例**：
     ```python
     translate_pdf(input_file, output_file, options="A")
     ```
   - **正确示例**：
     ```python
     translate_pdf(input_file, output_file, options=["A"])
     ```

#### 2. 查阅文档或源码
   - 查看 `pdf2zh` 的官方文档，确认参数要求。例如，某些参数可能需要以下形式：
     ```python
     # 正确格式（列表）
     options = ["translate", "preserve_layout"]
     ```

   - 如果文档不明确，可直接检查库的源码（通常在 `pdf2zh/converter.py` 中），找到报错位置附近对参数的处理逻辑，确认参数类型要求。

#### 3. 更新库版本
   - 可能是旧版本 `pdf2zh` 的 Bug，尝试升级到最新版本：
     ```bash
     pip install --upgrade pdf2zh
     ```

#### 4. 示例调试
   假设你的代码如下：
   ```python
   from pdf2zh import Converter
   converter = Converter()
   converter.convert("input.pdf", "output.pdf", mode="fast")  # 错误：mode 应为列表
   ```
   - **修正后**：
     ```python
     converter.convert("input.pdf", "output.pdf", mode=["fast"])  # 传递列表
     ```

---

### **排查步骤**
1. **定位报错位置**  
   根据报错信息 `pdf2zh.converter`，检查代码中调用 `Converter` 类的部分，例如：
   ```python
   # 你的代码中可能类似这样
   converter = Converter()
   converter.convert("input.pdf", options="some_string")  # 错误点
   ```

2. **检查参数列表**  
   确认所有类似 `options`、`mode`、`choices` 的参数是否按文档要求传递为列表。

3. **使用默认参数测试**  
   暂时移除自定义参数，用默认配置测试是否能正常运行：
   ```python
   converter.convert("input.pdf", "output.pdf")  # 不传额外参数
   ```
   如果默认配置正常，则问题出在自定义参数的类型上。

---

### **常见场景**
- **场景 1**：配置翻译选项时误传字符串  
  ```python
  # 错误
  translate_options = "ignore_images"
  # 正确
  translate_options = ["ignore_images"]
  ```

- **场景 2**：指定输出格式时未用列表  
  ```python
  # 错误
  output_format = "markdown"
  # 正确
  output_format = ["markdown"]
  ```

---

### 总结
此错误本质是 **参数类型不匹配**，重点检查调用 `pdf2zh` 函数时传递的参数是否为列表格式。如果问题仍未解决，请提供调用 `pdf2zh` 的具体代码片段，我会进一步帮你分析！

**Comment by shi1001** [comment]
[

[S709-white-paper-180524.pdf](https://github.com/user-attachments/files/18814421/S709-white-paper-180524.pdf)

](url)

**Comment by hellofinch** [comment]
GPT生成的内容就没有必要复制了吧。。。。
