### ISSUE TITLE
行内公式乱码问题

### ISSUE THREAD

**Issue by wangjinbaor** [Byaidu/PDFMathTranslate#59]
## 问题描述
请对问题进行描述，并提供日志或截图
**本项目不处理网络环境引发的问题**（例如 Empty translation result/Connection reset）
开发者您好，对文献进行翻译时，行内公式乱码
![image](https://github.com/user-attachments/assets/f8abc108-081d-4778-a1f3-ecec14882683)

## 测试文档
> [!IMPORTANT]
> 请提供用于复现测试的 PDF 文档
[pdf.pdf](https://github.com/user-attachments/files/17796998/pdf.pdf)

**Comment by Byaidu** [comment]
已修复，感谢反馈
