### ISSUE TITLE
layoutparser 加载模型的时候可以使用GPU吗

### ISSUE THREAD

**Issue by Williamsunsir** [Byaidu/PDFMathTranslate#6]
![image](https://github.com/user-attachments/assets/bd1747b3-c96b-400c-ad5c-b3a9ea48087c)
我开了10个进程之后，CPU占用率特别高，如果我开线程的话，在写入每页的翻译结果的时候就会很慢很卡，有时候我都怀疑是我的翻译问题。

**Comment by Williamsunsir** [comment]
![image](https://github.com/user-attachments/assets/bcf76e8b-c93a-43e3-af6e-fb73a0d3b4e5)
CPU占用情况，2台服务器，每个服务器开启了10个进程

**Comment by Byaidu** [comment]
我去，哥们你怎么一下翻译这么多，什么需求这是

**Comment by Williamsunsir** [comment]
手里有一堆文献需要做双语，目前尝试了N种翻译的方法，其中也包含了pdf转word再转回pdf，我发现还是通过布局识别这种方法，还原还是最好，并且兼顾了翻译速度和翻译效果

**Comment by Byaidu** [comment]
https://github.com/Layout-Parser/layout-parser/blob/04e28168d820eea3a1ff1e098078323e7b48648b/src/layoutparser/models/effdet/layoutmodel.py#L131

应该是有在用 GPU 的，不确定的话可以这里断一下看看

**Comment by Williamsunsir** [comment]
> https://github.com/Layout-Parser/layout-parser/blob/04e28168d820eea3a1ff1e098078323e7b48648b/src/layoutparser/models/effdet/layoutmodel.py#L131
> 
> 应该是有在用 GPU 的，不确定的话可以这里断一下看看

等会我做个测试

**Comment by Byaidu** [comment]
> 手里有一堆文献需要做双语，目前尝试了N种翻译的方法，其中也包含了pdf转word再转回pdf，我发现还是通过布局识别这种方法，还原还是最好，并且兼顾了翻译速度和翻译效果

确实，感觉现有的翻译服务又贵又烂，都不知道哪来的自信收费，实在没忍住自己花两天时间手搓了一个出来

**Comment by Williamsunsir** [comment]
我在翻译上做了一些改动，批量翻译非常适合文档翻译这块，我等把代码贡献出来

**Comment by Byaidu** [comment]
感谢感谢！

**Comment by Williamsunsir** [comment]
壮大开源项目，开源万岁

**Comment by clareliu1234** [comment]
> > 手里有一堆文献需要做双语，目前尝试了N种翻译的方法，其中也包含了pdf转word再转回pdf，我发现还是通过布局识别这种方法，还原还是最好，并且兼顾了翻译速度和翻译效果
> 
> 确实，感觉现有的翻译服务又贵又烂，都不知道哪来的自信收费，实在没忍住自己花两天时间手搓了一个出来

老哥，牛的，刚试了一下，效果确实很可以，老哥你这是用的谷歌的翻译？
