### ISSUE TITLE
在1%就报错

### ISSUE THREAD

**Issue by yshi100** [Byaidu/PDFMathTranslate#61]
ckpt = torch.load(file, map_location="cpu")
  1%|█                                                                                | 8/583 [00:04<04:32,  2.11it/s]ERROR:pdf2zh.converter:Empty translation result
ERROR:pdf2zh.converter:
[Uploading mastering-ubuntu-server-4th.pdf…]()
Empty translation result

**Comment by Byaidu** [comment]
## 问题描述
请对问题进行描述，并提供日志或截图
**本项目不处理网络环境引发的问题**（例如 Empty translation result/Connection reset）

## 测试文档
> [!IMPORTANT]
> 请提供用于复现测试的 PDF 文档

**Comment by yshi100** [comment]
pdf2zh mastering-ubuntu-server-4th.pdf
/home/yshi/.pyenv/versions/3.12.0/lib/python3.12/site-packages/doclayout_yolo/nn/tasks.py:733: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckpt = torch.load(file, map_location="cpu")
  1%|█                                                                                | 8/583 [00:04<04:32,  2.11it/s]ERROR:pdf2zh.converter:Empty translation result
ERROR:pdf2zh.converter:Empty translation result
ERROR:pdf2zh.converter:Empty translation result
ERROR:pdf2zh.converter:Empty translation result
ERROR:pdf2zh.converter:Empty translation result
ERROR:pdf2zh.converter:Empty translation result
ERROR:pdf2zh.converter:Empty translation result
ERROR:pdf2zh.converter:Empty translation result

**Comment by yshi100** [comment]
[Uploading mastering-ubuntu-server-4th.pdf…]()

**Comment by yshi100** [comment]
没有报Connection reset， 其它文件可以转，

**Comment by Byaidu** [comment]
那麻烦传个我能点进去下载的链接

**Comment by yshi100** [comment]
[Uploading mastering-ubuntu-server-4th.pdf…]()

**Comment by yshi100** [comment]
[
[Uploading mastering-ubuntu-server-4th.pdf…]()
](url)

**Comment by yshi100** [comment]
[mastering-ubuntu-server-4th.pdf](https://github.com/user-attachments/files/17801760/mastering-ubuntu-server-4th.pdf)

**Comment by Byaidu** [comment]
已修复

**Comment by Byaidu** [comment]
> 没有报Connection reset， 其它文件可以转，

之前不好意思了，下次可以先说明排除网络问题

**Comment by yshi100** [comment]
感谢修复
