### ISSUE TITLE
译文存在大量重叠

### ISSUE THREAD

**Issue by night-cruise** [Byaidu/PDFMathTranslate#62]
## 问题描述

中文PDF：
![屏幕截图 2024-11-19 020453](https://github.com/user-attachments/assets/fc4a1adf-f012-44d0-a91c-8e34d0054879)

中英文对照PDF：
![屏幕截图 2024-11-19 020559](https://github.com/user-attachments/assets/65227965-73cc-4f79-b68a-c9a63ea762fc)

## 测试文档

[vm-ft.pdf](https://github.com/user-attachments/files/17804535/vm-ft.pdf)

**Comment by Byaidu** [comment]
![image](https://github.com/user-attachments/assets/f0409471-fd8f-4191-89d3-001b310628b3)

看起来是 pdfminer 解析器的问题，我看看怎么修

**Comment by DuanH98** [comment]
类似但不同问题，且转换PDF/A后仍存在。
![image](https://github.com/user-attachments/assets/791dd67c-bbdf-4746-aec6-20233231b412)

[Test.pdf](https://github.com/user-attachments/files/18117052/Test.pdf)

**Comment by hellofinch** [comment]
> 类似但不同问题，且转换PDF/A后仍存在。 ![image](https://private-user-images.githubusercontent.com/16163941/395313577-791dd67c-bbdf-4746-aec6-20233231b412.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwODExMDQsIm5iZiI6MTczNDA4MDgwNCwicGF0aCI6Ii8xNjE2Mzk0MS8zOTUzMTM1NzctNzkxZGQ2N2MtYmJkZi00NzQ2LWFlYzYtMjAyMzMyMzFiNDEyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDA5MDY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4YjBhOWJlYTcyYTE0Y2UzNjhhMjI1YTQyZjg5MjE3YjlmZWNjZWJiNjBhMjA2YzY3MzI4NmIyMGExMWNiM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yBe7lPrgWPTy-xzKfRMUPoAe7zffIGfW256krsk_rVs)
> 
> [Test.pdf](https://github.com/user-attachments/files/18117052/Test.pdf)

这个好像是扫描件吧？暂时还不太能处理。
https://github.com/Byaidu/PDFMathTranslate/issues/19
