### ISSUE TITLE
目前表格直接跳过

### ISSUE THREAD

**Issue by yz-Python** [Byaidu/PDFMathTranslate#63]
## 功能描述
请描述需要添加的功能，以及是否有类似项目可以参考
我发现目前表格也无法进行翻译，各位大佬有什么好的建议吗

**Comment by Byaidu** [comment]
表格是故意设计成不翻译的…要不然实验数据会乱掉

**Comment by yz-Python** [comment]
哦哦哦 那代码是不是把vcls=['abandon','figure','table','isolate_formula','formula_caption']
这个里面的 table去掉 就可以了呀

**Comment by Byaidu** [comment]
对的

**Comment by yz-Python** [comment]
我试一下 谢谢大佬
