### ISSUE TITLE
进度条走完了但是并没有翻译

### ISSUE THREAD

**Issue by GeorgeRudd** [Byaidu/PDFMathTranslate#64]
麻烦作者看下，进度条走完了，但是查看输出的文档发现并没有翻译
文件：
[1.pdf](https://github.com/user-attachments/files/17808700/1.pdf)

**Comment by Byaidu** [comment]
![image](https://github.com/user-attachments/assets/8275c352-7547-4e08-be18-7ec050fa6a61)

目前还不能翻译这种扫描版的 PDF，参考 https://github.com/Byaidu/PDFMathTranslate/issues/19
