### ISSUE TITLE
无法正常排版旋转页面

### ISSUE THREAD

**Issue by clareliu1234** [Byaidu/PDFMathTranslate#65]
## 问题描述
请对问题进行描述，并提供日志或截图
横版本的表格识别的内容，变成竖向排版了
可能是版面分析模型的效果不好？大佬有没有考虑换一个版面分析模型，感觉mineru做的版面分析模型pdf-extract还可以
![image](https://github.com/user-attachments/assets/dac533b4-57b0-440b-8b6a-b19d7044b305)

**本项目不处理网络环境引发的问题**（例如 Empty translation result/Connection reset）

## 测试文档
下面是复现的文档
[3.pdf](https://github.com/user-attachments/files/17808715/3.pdf)

> [!IMPORTANT]
> 请提供用于复现测试的 PDF 文档

**Comment by Byaidu** [comment]
https://github.com/Byaidu/PDFMathTranslate/issues/327
