### ISSUE TITLE
想出个网页版，这样子可以和一些软件可能配合更好一些

### ISSUE THREAD

**Issue by hhxy11** [Byaidu/PDFMathTranslate#67]
## 功能描述
请描述需要添加的功能，以及是否有类似项目可以参考

类似这样子，封装成docker镜像，然后浏览器访问7860，妥妥的selfhost，完全无需命令行。

然后出网页版，可以更方便在浏览器
或者是，和flomo，obsidian，这些在线笔记合并在一起🤔然后这样子不用两个页面来回切换了

我们也可以就是，两个网页切换，不用多个东西这样子一直来回切换了

**Comment by Byaidu** [comment]
可以的，之前想集成 zotero 来着，结果发现 firefox 的 api 有点搞

docker 应该肯快就会上，之后有时间会看看能不能集成 obsidian 之类的

**Comment by reycn** [comment]
We've added GUI support (`pdf2zh -i`)that enables you to drag and translate directly in the browser, eliminating the need to switch between terminals and browsers. Let's check if it works.

我们添加了图形用户界面支持 (`pdf2zh -i`)，使您可以直接在浏览器中拖动和翻译，无需在终端和浏览器之间切换。让我们来看看它是否有效。

**Comment by Byaidu** [comment]
已支持 docker
