### ISSUE TITLE
翻译后的输出文件，中文英文都重叠在一起，没法看

### ISSUE THREAD

**Issue by GhostDavid** [Byaidu/PDFMathTranslate#69]
## 问题描述
翻译后两个文件，中文英文都重叠在一起
example-zh如下图
![image](https://github.com/user-attachments/assets/5cd5b07f-647e-45e2-b2aa-3f84c8fab2ff)

example-dual如下图
page1
![image](https://github.com/user-attachments/assets/9ab1d134-9798-4c72-9bc5-73ad78aac059)
page2
![image](https://github.com/user-attachments/assets/030a96b1-cbcc-49bb-b88e-553007ff98e8)

## 测试文档
> [!IMPORTANT]
> 请提供用于复现测试的 PDF 文档
[example.pdf](https://github.com/user-attachments/files/17813348/example.pdf)

操作过程截图
![image](https://github.com/user-attachments/assets/8958a6c5-2249-4a1f-8a85-72ae7b6fab04)

**Comment by Byaidu** [comment]
![image](https://github.com/user-attachments/assets/c3f2e909-c088-4097-abf7-bc6050739570)

你这个文档是扫描件，目前没办法处理……

**Comment by GhostDavid** [comment]
@Byaidu 我这个不是扫描件呀，我没理解是怎么定义扫描件？是指文字不能复制的图片pdf么，如果是的话，我这个不是扫描件，就是正常的论文pdf。如果有其他定义，请告知我一下，谢谢

**Comment by GhostDavid** [comment]
@Byaidu 了解了，是我的问题，可能是我的pdf软件是自带ocr的，导致我以为是个非扫描件。找了篇正常论文后，能正常翻译了
