### ISSUE TITLE
译文貌似分隔符未剔除干净

### ISSUE THREAD

**Issue by Williamsunsir** [Byaidu/PDFMathTranslate#7]
# 译文貌似分隔符未剔除干净
版本：1.4.6
![image](https://github.com/user-attachments/assets/9fe1fd4c-3cf5-4780-aa91-c3495e373d4f)
原文地址：https://link.springer.com/content/pdf/10.1007/s11440-016-0494-0.pdf

**Comment by Byaidu** [comment]
![image](https://github.com/user-attachments/assets/f0612b20-d8d2-4bce-a1ff-b4fd72082c95)

有些翻译器对 md 支持不太好，公式标记有概率炸掉，就会出现一堆 $ 了

**Comment by Byaidu** [comment]
更新了下大小写敏感，现在应该会好一点

**Comment by Williamsunsir** [comment]
# 原文
![image](https://github.com/user-attachments/assets/75497d86-0fa4-40c0-8360-f109b814da24)

# 测试版本：1.4.8
![image](https://github.com/user-attachments/assets/cd419a92-3e2d-4a60-b469-d7f988a70a33)


#  测试版本：1.4.7
![image](https://github.com/user-attachments/assets/6fd03a66-e334-4c56-aa97-7cf388bc3e67)

**Comment by Byaidu** [comment]
啊这，怎么还不如上个版本了

**Comment by Williamsunsir** [comment]
是的啊，可能是测试样例不如我这么多，所以发现不了这么多问题

**Comment by Byaidu** [comment]
![image](https://github.com/user-attachments/assets/728ebbb0-f077-48e6-a34f-ac6db1a42533)

你开下 -d 选项看看呢，我这里 1.4.8 是可以正常保留公式的

**Comment by Williamsunsir** [comment]
![image](https://github.com/user-attachments/assets/1abfa2e4-33a2-483f-aa17-e824c87d3be4)
我是直接修改源码在我程序里边使用的

**Comment by Byaidu** [comment]
盲猜是公式识别改烂了，你看看其他文档正不正常呢

**Comment by Williamsunsir** [comment]
我找到问题了，我发现是翻译引擎将分割符$v27$给翻译了

**Comment by Williamsunsir** [comment]
使用微软翻译发现他不管什么内容都翻译，所以类似"$v27$"的分隔符就会被翻译，但是"$#27$" 就不会被翻译

**Comment by Williamsunsir** [comment]
我在翻译函数上做了单独的替换之后就正常了，微软翻译非常智能，额呃呃呃
![image](https://github.com/user-attachments/assets/10e2ddfa-a1e1-4523-877f-271e0d5e19e6)
![image](https://github.com/user-attachments/assets/9ac11f43-a339-4825-a42d-36f89f4d61f6)
![image](https://github.com/user-attachments/assets/6cf465b4-6611-4bc5-847f-5bd17968015e)
