### ISSUE TITLE
fix (docker): label latest missing

### ISSUE THREAD

**Issue by reycn** [Byaidu/PDFMathTranslate#74]
## Feature
Add label `latest` for docker images

## Related Issue
- [Comment to #70](https://github.com/Byaidu/PDFMathTranslate/issues/70#issuecomment-2487584766)

## Replication 
- `docker pull byaidu/pdf2zh:1.7.6` succeed
- `docker pull byaidu/pdf2zh` failed, with the following outputs

	```bash
	Using default tag: latest
	Error response from daemon: manifest for byaidu/pdf2zh:latest not found: manifest unknown: manifest unknown
	```

**Comment by Byaidu** [comment]
现在应该可以了
