### ISSUE TITLE
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your settings to allow access to localhost.

### ISSUE THREAD

**Issue by BaseBlank** [Byaidu/PDFMathTranslate#77]
## 问题描述
启动UI界面，
pdf2zh -i
错误
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your p settings to allow access to localhost.

## 解决方案
找到D:\Anaconda\anaconda3\envs\worktools\Lib\site-packages\pdf2zh\gui.py
将303与308行的0.0.0.0修改为127.0.0.1

**Comment by WillowWL** [comment]
请问如果输入了http://localhost:7860/显示拒绝连接是什么问题呢？
pdf2zh -i这个是直接输入在浏览器网址就行吗，为啥我一输入就是普通搜索浏览器界面
（实在抱歉打扰，本人水平实在是差，很麻烦打扰了）

**Comment by WillowWL** [comment]
> 请问如果输入了[http://localhost:7860/显示拒绝连接是什么问题呢？](http://localhost:7860/%E6%98%BE%E7%A4%BA%E6%8B%92%E7%BB%9D%E8%BF%9E%E6%8E%A5%E6%98%AF%E4%BB%80%E4%B9%88%E9%97%AE%E9%A2%98%E5%91%A2%EF%BC%9F) pdf2zh -i这个是直接输入在浏览器网址就行吗，为啥我一输入就是普通搜索浏览器界面 （实在抱歉打扰，本人水平实在是差，很麻烦打扰了）

**解决方案（一种替代法）**
在命令行中，找到输入地址（gui.py所在地址）运行python gui.py

**Comment by BaseBlank** [comment]
系统网络设置被用的软件修改了
我是在虚拟环境中安装的pdf2z，
你也可以直接安装，都行，然后找到安装的pdf2z的gui.py，拷贝一份备份，之后按照楼上的修改.py文件
将303与308行的0.0.0.0修改为127.0.0.1
之后在CMD里进入你的python环境，输入pdf2zh -i，不是在浏览器输入，
之后CMD会生成一个网址，自动跳转本地浏览器。

**Comment by WillowWL** [comment]
您好，您的邮件我已收到。顺祝时祺

**Comment by BaseBlank** [comment]
如果系统设置没有修改，直接
之后在CMD里进入你的python环境，输入pdf2zh -i，不是在浏览器输入，
之后CMD会生成一个网址，自动跳转本地浏览器。
就可以

**Comment by WillowWL** [comment]
> 如果系统设置没有修改，直接 之后在CMD里进入你的python环境，输入pdf2zh -i，不是在浏览器输入， 之后CMD会生成一个网址，自动跳转本地浏览器。 就可以

非常感谢，我会进行尝试，再次表示感谢

**Comment by reycn** [comment]
We've fixed the current issue [@commit#24bff394c1892b9aafe52647565ddfdf5eaa20f4](https://github.com/Byaidu/PDFMathTranslate/commit/24bff394c1892b9aafe52647565ddfdf5eaa20f4).
我们已修复当前问题 [@commit#24bff394c1892b9aafe52647565ddfdf5eaa20f4](https://github.com/Byaidu/PDFMathTranslate/commit/24bff394c1892b9aafe52647565ddfdf5eaa20f4)


Could you please help us see if it works now?
请问您能帮忙试试现在可以吗？

**Comment by Byaidu** [comment]
https://github.com/Byaidu/PDFMathTranslate/wiki/FAQ---%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#localhost-is-not-accessible--localhost-%E6%97%A0%E6%B3%95%E8%AE%BF%E9%97%AE

排查了一下，一般可能是代理软件占用 localhost 导致的

**Comment by WillowWL** [comment]
> https://github.com/Byaidu/PDFMathTranslate/wiki/FAQ---%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#localhost-is-not-accessible--localhost-%E6%97%A0%E6%B3%95%E8%AE%BF%E9%97%AE
> 
> 排查了一下，一般可能是代理软件占用 localhost 导致的
感谢您的回复，经过尝试应该是代理软件的问题。现在可以直接通过浏览器http://localhost:7860/进行使用了。

**Comment by BaseBlank** [comment]
@reycn 
pip install git+https://github.com/Byaidu/PDFMathTranslate.git
***

Installing collected packages: pdf2zh
  Attempting uninstall: pdf2zh
    Found existing installation: pdf2zh 1.7.6
    Uninstalling pdf2zh-1.7.6:
      Successfully uninstalled pdf2zh-1.7.6
Successfully installed pdf2zh-1.7.7

***
已经升级最新版本1.7.7
通过pdf2zh -i已经可以正常启动GUI界面。



但是会有一点minor bug，不过不影响使用；
就是在创建本地端口启动的过程中，会被微软windows defender扫描警告。
<img width="389" alt="github提交" src="https://github.com/user-attachments/assets/4a2b7f91-ed9c-4df5-90b2-d540ef063fcd">


Thank you for your excellent work！！！
