### ISSUE TITLE
使用web的GUI无法导入文件

### ISSUE THREAD

**Issue by pomolnc** [Byaidu/PDFMathTranslate#83]
## 问题描述
![image](https://github.com/user-attachments/assets/ac4b3bad-1d7c-498b-8758-ceaf11c689ea)

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\pydantic\type_adapter.py", line 254, in _init_core_attrs
    self.core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')
  File "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\pydantic\type_adapter.py", line 54, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

Traceback (most   recent call last):
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\uvicorn\protocols\http\h11_impl.py",   line 403, in run_asgi
result = await app(  # type:   ignore[func-returns-value]
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\uvicorn\middleware\proxy_headers.py",   line 60, in __call__
return await self.app(scope, receive, send)
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\fastapi\applications.py",   line 1054, in __call__
await super().__call__(scope, receive, send)
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\starlette\applications.py",   line 113, in __call__
await self.middleware_stack(scope, receive, send)
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\starlette\middleware\errors.py",   line 187, in __call__
raise exc
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\starlette\middleware\errors.py",   line 165, in __call__
await self.app(scope, receive, _send)
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\gradio\route_utils.py",   line 695, in __call__
await self.simple_response(scope, receive, send,   request_headers=headers)
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\gradio\route_utils.py",   line 711, in simple_response
await self.app(scope, receive, send)
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\starlette\middleware\exceptions.py",   line 62, in __call__
await wrap_app_handling_exceptions(self.app, conn)(scope, receive,   send)
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\starlette\_exception_handler.py",   line 53, in wrapped_app
raise exc
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\starlette\_exception_handler.py",   line 42, in wrapped_app
await app(scope, receive, sender)
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\starlette\routing.py",   line 715, in __call__
await self.middleware_stack(scope, receive, send)
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\starlette\routing.py",   line 735, in app
await route.handle(scope, receive, send)
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\starlette\routing.py",   line 288, in handle
await self.app(scope, receive, send)
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\starlette\routing.py",   line 76, in app
await wrap_app_handling_exceptions(app, request)(scope, receive, send)
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\starlette\_exception_handler.py",   line 53, in wrapped_app
raise exc
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\starlette\_exception_handler.py",   line 42, in wrapped_app
await app(scope, receive, sender)
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\starlette\routing.py",   line 73, in app
response = await f(request)
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\fastapi\routing.py",   line 291, in app
solved_result = await solve_dependencies(
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\fastapi\dependencies\utils.py",   line 666, in solve_dependencies
) = await request_body_to_args(    # body_params checked above
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\fastapi\dependencies\utils.py",   line 891, in request_body_to_args
fields_to_extract = get_cached_model_fields(first_field.type_)
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\fastapi\_compat.py",   line 659, in get_cached_model_fields
return get_model_fields(model)
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\fastapi\_compat.py",   line 285, in get_model_fields
return [
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\fastapi\_compat.py",   line 286, in <listcomp>
ModelField(field_info=field_info, name=name)
File "<string>", line 6, in __init__
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\fastapi\_compat.py",   line 111, in __post_init__
self._type_adapter: TypeAdapter[Any] = TypeAdapter(
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\pydantic\type_adapter.py",   line 222, in __init__
self._init_core_attrs(
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\pydantic\type_adapter.py",   line 273, in _init_core_attrs
core_schema = schema_generator.generate_schema(self._type)
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\pydantic\_internal\_generate_schema.py",   line 612, in generate_schema
schema = self._generate_schema_inner(obj)
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\pydantic\_internal\_generate_schema.py",   line 865, in _generate_schema_inner
return self._annotated_schema(obj)
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\pydantic\_internal\_generate_schema.py",   line 1972, in _annotated_schema
schema = self._apply_annotations(source_type, annotations)
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\pydantic\_internal\_generate_schema.py",   line 2051, in _apply_annotations
schema = get_inner_schema(source_type)
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\pydantic\_internal\_schema_generation_shared.py",   line 84, in __call__
schema = self._handler(source_type)
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\pydantic\_internal\_generate_schema.py",   line 2126, in new_handler
schema = metadata_get_schema(source, get_inner_schema)
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\pydantic\_internal\_generate_schema.py",   line 2122, in <lambda>
lambda source, handler: handler(source)
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\pydantic\_internal\_schema_generation_shared.py",   line 84, in __call__
schema = self._handler(source_type)
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\pydantic\_internal\_generate_schema.py",   line 2032, in inner_handler
schema = self._generate_schema_inner(obj)
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\pydantic\_internal\_generate_schema.py",   line 886, in _generate_schema_inner
return self.match_type(obj)
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\pydantic\_internal\_generate_schema.py",   line 988, in match_type
return self._match_generic_type(obj, origin)
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\pydantic\_internal\_generate_schema.py",   line 1016, in _match_generic_type
return self._union_schema(obj)
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\pydantic\_internal\_generate_schema.py",   line 1323, in _union_schema
choices.append(self.generate_schema(arg))
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\pydantic\_internal\_generate_schema.py",   line 612, in generate_schema
schema = self._generate_schema_inner(obj)
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\pydantic\_internal\_generate_schema.py",   line 886, in _generate_schema_inner
return self.match_type(obj)
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\pydantic\_internal\_generate_schema.py",   line 997, in match_type
return self._unknown_type_schema(obj)
File   "C:\Users\xxxxxxxxx\Miniconda3\lib\site-packages\pydantic\_internal\_generate_schema.py",   line 515, in _unknown_type_schema
raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError:   Unable to generate pydantic-core schema for <class   'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the   model_config to ignore this error or implement `__get_pydantic_core_schema__`   on your type to fully support it.
 
If you got this error by calling   handler(<some type>) within `__get_pydantic_core_schema__` then you   likely need to call `handler.generate_schema(<some type>)` since we do   not call `__get_pydantic_core_schema__` on `<some type>` otherwise to   avoid infinite recursion.
 
For further information visit   https://errors.pydantic.dev/2.10/u/schema-for-unknown-type

## 测试文档
> [!IMPORTANT]
> [Shapey et al_2021_Integrated multi-modality image-guided navigation for neurosurgery.pdf](https://github.com/user-attachments/files/17838990/Shapey.et.al_2021_Integrated.multi-modality.image-guided.navigation.for.neurosurgery.pdf)

**Comment by Byaidu** [comment]
可能是某个包的依赖管理有问题，建议开个新环境或者 docker

**Comment by pomolnc** [comment]
> 可能是某个包的依赖管理有问题，建议开个新环境或者 docker

感谢，用docker确实没这问题

**Comment by reycn** [comment]
手上暂时没有 Windows 来复现，可以麻烦您开一个新的 conda 环境试试吗？
有时候 conda 的冲突它自己以为解决了但是其实没有 hhh

**Comment by reycn** [comment]
暂时关闭 Issue，但如果有任何人帮忙复现我们可以重新开启。
Issue is temporarily closed, but we can turn it back on if anyone helps reproduce it.
