### ISSUE TITLE
feat (main): support onnx as torch's alternative

### ISSUE THREAD

**Issue by Wybxc** [Byaidu/PDFMathTranslate#85]
## 功能描述

用 ONNX 模型代替 torch 模型进行推理，避免引入巨大的 torch 依赖。

**Comment by Wybxc** [comment]
我可以帮忙完成这个问题并提交PR。

**Comment by Byaidu** [comment]
> 我可以帮忙完成这个问题并提交PR。

感谢支持！

**Comment by reycn** [comment]
看起来很 promising！唯一的担忧是这个框架的兼容性。torch 用得广泛跨平台兼容性好，这个 Byaidu 看看。

**Comment by Wybxc** [comment]
> 看起来很 promising！唯一的担忧是这个框架的兼容性。torch 用得广泛跨平台兼容性好，这个 Byaidu 看看。

可以将onnxruntime和torch都作为可选依赖，用户选择其一安装

**Comment by reycn** [comment]
- 可以考虑 `pip install phf2zh` 默认安装 torch （后续 onnx 几乎没有 bug 反馈可考虑切换）
  - `pip install 'phf2zh[onnx]'` 
  - `pip install 'phf2zh[torch]'` 
 
感觉这样比较好，你们觉得呢？

**Comment by Byaidu** [comment]
> - 可以考虑 `pip install phf2zh` 默认安装 torch （后续 onnx 几乎没有 bug 反馈可考虑切换）
> 
>   - `pip install 'phf2zh[onnx]'` 
> 
>   - `pip install 'phf2zh[torch]'` 
> 
>  
> 
> 参考 pandas 实现： https://arc.net/l/quote/fveaitzg
> 
> 
> 
> 感觉这样比较好，你们觉得呢？

我觉得没问题

**Comment by Wybxc** [comment]
调了一天终于把 onnx 推理的流程跑通了。

ONNX 的模型和推理已经发布在 [huggingface](https://huggingface.co/wybxc/DocLayout-YOLO-DocStructBench-onnx) 上，下一步就可以集成到这个项目中。

**Comment by Wybxc** [comment]
Python 似乎并不支持将一组可选依赖项设置为默认值。这意味着用户必须显式地执行 `pip install pdf2zh[torch]` 或 `pip install pdf2zh[onnx]`。这带来了几个问题：

1. 这是一个潜在的破坏性变更，因为包的安装方式发生了变化。
2. 如何处理用户没有安装可选依赖项或安装了多个可选依赖项的情况？对于前者，可以在运行时报错并提醒用户安装至少一个后端；对于后者，可能需要提供机制允许用户指定运行所需的后端。

**Comment by Byaidu** [comment]
> Python 似乎并不支持将一组可选依赖项设置为默认值。这意味着用户必须显式地执行 `pip install pdf2zh[torch]` 或 `pip install pdf2zh[onnx]`。这带来了几个问题：
> 
> 1. 这是一个潜在的破坏性变更，因为包的安装方式发生了变化。
> 2. 如何处理用户没有安装可选依赖项或安装了多个可选依赖项的情况？对于前者，可以在运行时报错并提醒用户安装至少一个后端；对于后者，可能需要提供机制允许用户指定运行所需的后端。

onnx 不大的话可以当成默认依赖（？
然后 torch 再手动指定就可以了
