### ISSUE TITLE
Duplicated content in the output

### ISSUE THREAD

**Issue by kowyo** [Byaidu/PDFMathTranslate#86]
## 问题描述

- [x] I have checked the wiki.
- [x] I have checked the same issues

In the output file, some content was duplicated, as #37 has mentioned, is this an issue of pdfminer?

## 测试文档

[Lin et al. - 2018 - All-optical machine learning using diffractive deep neural networks.pdf](https://github.com/user-attachments/files/17841056/Lin.et.al.-.2018.-.All-optical.machine.learning.using.diffractive.deep.neural.networks.pdf)

Origin:

<img width="702" alt="image" src="https://github.com/user-attachments/assets/7fc35002-377a-42f5-872f-b9cf11016633">

Translation:

<img width="703" alt="image" src="https://github.com/user-attachments/assets/9ba42993-cadd-45d4-93c8-b349f5e09639">

**Comment by Byaidu** [comment]
It is caused by special font size of the first character in the paragraph, as mentioned in https://github.com/Byaidu/PDFMathTranslate/issues/26#issuecomment-2466624709

**Comment by kowyo** [comment]
Thank you for the quick reply. I am good to close it as a duplication of #26. It's a wonderful work, so hopefully I can contribute to it in the future.

**Comment by Byaidu** [comment]
已修复

**Comment by kowyo** [comment]
我通过 pip 安装了版本  v1.7.9，翻译出来的文档仍然有相同问题

![image](https://github.com/user-attachments/assets/afb3c29a-c497-4797-8309-9f7d77645cd5)

**Comment by Byaidu** [comment]
稍等，正在推送新版本

**Comment by Byaidu** [comment]
已推送v1.8.0

**Comment by kowyo** [comment]
谢谢，我自己也编译了源码，效果真的太完美了，对比起有道翻译之类的工具。
