### ISSUE TITLE
docker部署无法翻译

### ISSUE THREAD

**Issue by pomolnc** [Byaidu/PDFMathTranslate#87]
## 问题描述
![image](https://github.com/user-attachments/assets/0ce8b6c2-3396-4594-af5a-fd8baaceb5b6)

运行日志：
Executing command: cd "/tmp/tmp0zu167cq" && pdf2zh "/tmp/tmp0zu167cq/input.pdf" -lo zh -s deeplx 

Files in temp directory: ['input.pdf']

Command output: Traceback (most recent call last):

Command output: File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 199, in _new_conn

Command output: sock = connection.create_connection(

Command output: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Command output: File "/usr/local/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection

Command output: raise err

Command output: File "/usr/local/lib/python3.12/site-packages/urllib3/util/connection.py", line 73, in create_connection

Command output: sock.connect(sa)

Command output: OSError: [Errno 101] Network is unreachable

Command output: 

Command output: The above exception was the direct cause of the following exception:

Command output: 

Command output: Traceback (most recent call last):

Command output: File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen

Command output: response = self._make_request(

Command output: ^^^^^^^^^^^^^^^^^^^

Command output: File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 490, in _make_request

Command output: raise new_e

Command output: File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 466, in _make_request

Command output: self._validate_conn(conn)

Command output: File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn

Command output: conn.connect()

Command output: File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 693, in connect

Command output: self.sock = sock = self._new_conn()

Command output: ^^^^^^^^^^^^^^^^

Command output: File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 214, in _new_conn

Command output: raise NewConnectionError(

Command output: urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f711946eba0>: Failed to establish a new connection: [Errno 101] Network is unreachable

Command output: 

Command output: The above exception was the direct cause of the following exception:

Command output: 

Command output: Traceback (most recent call last):

Command output: File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send

Command output: resp = conn.urlopen(

Command output: ^^^^^^^^^^^^^

Command output: File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen

Command output: retries = retries.increment(

Command output: ^^^^^^^^^^^^^^^^^^

Command output: File "/usr/local/lib/python3.12/site-packages/urllib3/util/retry.py", line 519, in increment

Command output: raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]

Command output: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Command output: urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /juliozhao/DocLayout-YOLO-DocStructBench/resolve/main/doclayout_yolo_docstructbench_imgsz1024.pt (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f711946eba0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

Command output: 

Command output: During handling of the above exception, another exception occurred:

Command output: 

Command output: Traceback (most recent call last):

Command output: File "/usr/local/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 1376, in _get_metadata_or_catch_error

Command output: metadata = get_hf_file_metadata(

Command output: ^^^^^^^^^^^^^^^^^^^^^

Command output: File "/usr/local/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn

Command output: return fn(*args, **kwargs)

Command output: ^^^^^^^^^^^^^^^^^^^

Command output: File "/usr/local/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 1296, in get_hf_file_metadata

Command output: r = _request_wrapper(

Command output: ^^^^^^^^^^^^^^^^^

Command output: File "/usr/local/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 277, in _request_wrapper

Command output: response = _request_wrapper(

Command output: ^^^^^^^^^^^^^^^^^

Command output: File "/usr/local/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 300, in _request_wrapper

Command output: response = get_session().request(method=method, url=url, **params)

Command output: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Command output: File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request

Command output: resp = self.send(prep, **send_kwargs)

Command output: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Command output: File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send

Command output: r = adapter.send(request, **kwargs)

Command output: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Command output: File "/usr/local/lib/python3.12/site-packages/huggingface_hub/utils/_http.py", line 93, in send

Command output: return super().send(request, *args, **kwargs)

Command output: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Command output: File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 700, in send

Command output: raise ConnectionError(e, request=request)

Command output: requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /juliozhao/DocLayout-YOLO-DocStructBench/resolve/main/doclayout_yolo_docstructbench_imgsz1024.pt (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f711946eba0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), '(Request ID: f8619d12-114f-4f2b-9d20-c0982f7645c0)')

Command output: 

Command output: The above exception was the direct cause of the following exception:

Command output: 

Command output: Traceback (most recent call last):

Command output: File "/usr/local/bin/pdf2zh", line 8, in <module>

Command output: sys.exit(main())

Command output: ^^^^^^

Command output: File "/usr/local/lib/python3.12/site-packages/pdf2zh/pdf2zh.py", line 262, in main

Command output: extract_text(**vars(parsed_args))

Command output: File "/usr/local/lib/python3.12/site-packages/pdf2zh/pdf2zh.py", line 87, in extract_text

Command output: pth = hf_hub_download(repo_id="juliozhao/DocLayout-YOLO-DocStructBench", filename="doclayout_yolo_docstructbench_imgsz1024.pt")

Command output: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Command output: File "/usr/local/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn

Command output: return fn(*args, **kwargs)

Command output: ^^^^^^^^^^^^^^^^^^^

Command output: File "/usr/local/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 862, in hf_hub_download

Command output: return _hf_hub_download_to_cache_dir(

Command output: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Command output: File "/usr/local/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 969, in _hf_hub_download_to_cache_dir

Command output: _raise_on_head_call_error(head_call_error, force_download, local_files_only)

Command output: File "/usr/local/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 1487, in _raise_on_head_call_error

Command output: raise LocalEntryNotFoundError(

Command output: huggingface_hub.errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

Command completed with return code: 1

Files after translation: ['input.pdf']

Translation failed: Output file not found at /tmp/tmp0zu167cq/input-zh.pdf

环境：
镜像是byaidu/pdf2zh:latest
翻译服务用的镜像是ghcr.io/owo-network/deeplx:latest，使用的是deeplx免费的endpoint。
容器的网络模式都是默认的。
服务都是在家里的nas上，内网穿透访问（这个会影响吗）

## 测试文档
> [!IMPORTANT]
> 请提供用于复现测试的 PDF 文档

**Comment by Byaidu** [comment]
网络问题建议自行解决

**Comment by pomolnc** [comment]
> 网络问题建议自行解决

意思是需要科学上网嘛

**Comment by songyongshun** [comment]
需要能访问huggingface.co，你试试ping不通的话，那么设置下代理：
export HF_ENDPOINT=https://hf-mirror.com

**Comment by pomolnc** [comment]
> 需要能访问huggingface.co，你试试ping不通的话，那么设置下代理： export HF_ENDPOINT=https://hf-mirror.com

加上了容器的环境变量，改成一堆http 404的报错了


{'files': [PosixPath('pdf2zh_files/Mishra et al_2022_Virtual Reality in Neurosurgery.pdf')], 'pages': None, 'lang_in': 'auto', 'lang_out': 'zh', 'service': 'deeplx:', 'output': PosixPath('pdf2zh_files'), 'thread': 4, 'callback': <function translate.<locals>.progress_bar at 0x7f73f4b8dd00>}

  0%|          | 0/14 [00:00<?, ?it/s]HTTP error: 404

HTTP error: 404

HTTP error: 404

HTTP error: 404

HTTP error: 404

HTTP error: 404

HTTP error: 404

HTTP error: 404

HTTP error: 404

HTTP error: 404

HTTP error: 404

HTTP error: 404

HTTP error: 404

HTTP error: 404

HTTP error: 404

HTTP error: 404

HTTP error: 404

HTTP error: 404

HTTP error: 404

HTTP error: 404

HTTP error: 404

HTTP error: 404

HTTP error: 404

HTTP error: 404

HTTP error: 404

HTTP error: 404

HTTP error: 404

**Comment by pomolnc** [comment]
如果该网络问题是共性问题（感觉挺多人碰到），是不是可以把相关的问题和解决方案（没有的话也可以只是做提示）写在readme中

**Comment by Byaidu** [comment]
> 如果该网络问题是共性问题（感觉挺多人碰到），是不是可以把相关的问题和解决方案（没有的话也可以只是做提示）写在readme中

那可能 github 上 99% 的项目都要先说明怎么科学上网了，而且 issue 模板上也有指路 wiki 解决网络问题，但是很多人不看……

**Comment by pomolnc** [comment]
> > 如果该网络问题是共性问题（感觉挺多人碰到），是不是可以把相关的问题和解决方案（没有的话也可以只是做提示）写在readme中
> 
> 那可能 github 上 99% 的项目都要先说明怎么科学上网了，而且 issue 模板上也有指路 wiki 解决网络问题，但是很多人不看……

好的，我之前发现问题的时候没有看到有网络问题的处理方式

**Comment by humalian** [comment]
这个404的问题咋解决呀？
