### ISSUE TITLE
部分内容不会被翻译

### ISSUE THREAD

**Issue by ZhiYuan1688** [Byaidu/PDFMathTranslate#9]
当前版本：1.5.4
当前系统：Windows 11

## 部分内容不会被翻译

![image](https://github.com/user-attachments/assets/e83f011e-36ee-417e-a810-d5dcfb08bf8e)

## 排版很多这种情况
![image](https://github.com/user-attachments/assets/6b0e0f45-4298-4ed1-8340-3ba6b2cac074)
![image](https://github.com/user-attachments/assets/e6266df3-488b-42c4-8c36-1552e7f6ef23)
![image](https://github.com/user-attachments/assets/33513ddb-47e4-4573-8518-91873500c77c)

可能是翻译过后段落长度比原文段落长度短的原因

原始文件
[pdftest.pdf](https://github.com/user-attachments/files/17498914/pdftest.pdf)

**Comment by ZhiYuan1688** [comment]
希望能接入LLM翻译

**Comment by Byaidu** [comment]
这个是因为行距太大被划分成不同的段落了，之后会加入 ocr 分析改善一下

**Comment by Byaidu** [comment]
已解决
