### ISSUE TITLE
NameError: name 'pymupdf' is not defined

### ISSUE THREAD

**Issue by shihuaijin** [Byaidu/PDFMathTranslate#97]
## NameError: name 'pymupdf' is not defined
大神 求助
![1732234017364](https://github.com/user-attachments/assets/6d06a708-a4b4-4798-ab4f-32327a65033c)

**Comment by Byaidu** [comment]
pip install -U pymupdf

**Comment by reycn** [comment]
楼上的解决方案应该可以解决问题，暂时关闭 Issue
