### ISSUE TITLE
网页版无法使用，没有任何输出

### ISSUE THREAD

**Issue by killerljj** [Byaidu/PDFMathTranslate#98]
## 问题描述
请对问题进行描述，并提供日志或截图

网页版点击translate以后没有任何输出文档。

请确认 issues 中没有相同问题且完整阅读 wiki
**本项目不处理网络环境引发的问题**（例如 empty translation result/connection reset/check_hostname requires server_hostname/certificate verify failed）

## 测试文档
> [!IMPORTANT]
> 请提供用于复现测试的 PDF 文档
[Pioneering_Chiplet_Technology_and_Design_for_the_AMD_EPYC_and_Ryzen_Processor_Families__Industrial_Product.pdf](https://github.com/user-attachments/files/17853932/Pioneering_Chiplet_Technology_and_Design_for_the_AMD_EPYC_and_Ryzen_Processor_Families__Industrial_Product.pdf)

**Comment by reycn** [comment]
同样的文档未能复现。“网页版”是指的 demo 吗？那个这两天用的人有点多一直在排队。
