### ISSUE TITLE
论文首页翻译格式混乱，部分内容未翻译

### ISSUE THREAD

**Issue by ethanxyzhu** [Byaidu/PDFMathTranslate#99]
## 问题描述
如图，双栏带脚注的pdf发现不好识别似乎，试了两个pdf都有这个问题
![图片](https://github.com/user-attachments/assets/1399923e-d038-48dd-8a6d-97cf92bf7032)
![图片](https://github.com/user-attachments/assets/477cb3a8-879c-4d35-b574-cac2b752082f)

## 测试文档
1. [Samuel 等 - 2024 - Outer-loop admittance and motion control dual improvement via a multi-function observer.pdf](https://github.com/user-attachments/files/17854028/Samuel.-.2024.-.Outer-loop.admittance.and.motion.control.dual.improvement.via.a.multi-function.observer.pdf)
2. [Chaudhuri 等 - 2021 - An attention-based deep sequential GRU model for sensor drift compensation.pdf](https://github.com/user-attachments/files/17854032/Chaudhuri.-.2021.-.An.attention-based.deep.sequential.GRU.model.for.sensor.drift.compensation.pdf)

**Comment by Byaidu** [comment]
参考 https://github.com/Byaidu/PDFMathTranslate/issues/86

**Comment by Byaidu** [comment]
已修复
